### ISSUE TITLE
Missing options from Markdown-it

### ISSUE THREAD

**Issue by JamieSharpe** [neilsustc/vscode-markdown#101]
Missing options from Markdown-It

In the [API for markdown-it](https://markdown-it.github.io/markdown-it/), there are options for typographer and quote styles.

Could these be implemented into the extension?

**Comment by neilsustc** [comment]
This extension uses the [same code](https://github.com/Microsoft/vscode/blob/master/extensions/markdown/src/markdownEngine.ts#L42-L58) (used by vscode) to render MD to HTML to make it consistent. Maybe you can open an issue in vscode repository.

**Comment by Lemmingh** [comment]
Duplicate of #823

And good news:
https://github.com/microsoft/vscode/issues/107328
