### ISSUE TITLE
failed to update toc

### ISSUE THREAD

**Issue by Benature** [neilsustc/vscode-markdown#102]
The  "Table of Contents (up to date)" didn't show after I creat a toc

**Comment by neilsustc** [comment]
Please check whether there is any error message in the console (menubar>help>toggle developer tools)

**Comment by Benature** [comment]
后面发现只有一个特定的文件是不能更新目录的,打开那个文件时会有这个报错
```
GET file:///D:/%E8%BD%AF%E4%BB%B6%E5%AE%89%E8%A3%85%E6%96%87%E4%BB%B6%E5%A4%B9/…20Code/resources/app/out/vs/workbench/electron-browser/bootstrap/undefined net::ERR_FILE_NOT_FOUND
```

**Comment by neilsustc** [comment]
能不能尝试，如果使用类似的文件名或者目录，是否会产生同样的问题（比如因为文件名是中文，或者路径有空格等等可能的原因）
你提供越多的信息我才好找到问题的原因呀

**Comment by Benature** [comment]
嗯嗯,我尝试删掉一部分再建目录,后来发现如果第一个标题标题是链接的网页的话就不能更新目录.
比如下面这个
```
# 1. [第一个标题](https://www.baidu.com)
# 2. [第二个标题](https://www.google.com)
```
如果是这样第一个标题没有链接
```
# 1. [第一个标题]
# 2. [第二个标题](https://www.google.com)
```
就可以更新目录,问题好像就在第一个一级标题,后面的一级标题有没有链接都不影响.

**Comment by neilsustc** [comment]
好的，这下我就明白了

**Comment by neilsustc** [comment]
Please try v1.1.0
