### ISSUE TITLE
suggestion to the order list

### ISSUE THREAD

**Issue by Benature** [neilsustc/vscode-markdown#104]
if I tab in a ordered list, it would go like this
```
1. a
2. b
    3. c
```
it would be better if it go like this (`tab` then the number change to 1)
```
1. a
2. b
    1. c
```

**Comment by neilsustc** [comment]
Looks similar to #32 but this is real-time renumbering.

**Comment by Benature** [comment]
moreover, if the first line isn't numbered as 1, it will not change to ordered list (in preview)
```
1. a
2. b3. c(the first line is not 1.)
 
1. a
2. b
    1. c(the first line is 1. )
```
so it's a bit troblemsome to change it everytime

**Comment by neilsustc** [comment]
Okay, I see
