### ISSUE TITLE
find a bug: when print to HTML, the output override the original content, in .MD file, .md file is fine.

### ISSUE THREAD

**Issue by valleygtc** [neilsustc/vscode-markdown#105]
When I use command ```print current document to HTML```  in command palette, in a .MD file, the output HTML doesn't store in an extra .html file, but override the origin .MD file.
If the file extension is .md, everything is ok.
Am I the only one who encounter this problem?
My OS is deepin Linux, VSCode version is1.19.0

I didn't find an error message anywhere.

**Comment by neilsustc** [comment]
A quick solution is to open `[your user dir]\.vscode-insiders\extensions\yzhang.markdown-all-in-one-1.0.5\out\src\print.js`, go to line 55, and replace `/\.md$/` with `/\.(md|MD|markdown)$/`.

I'll fix this in the next version after the vscode Feb stable build.

**Comment by neilsustc** [comment]
v1.1.0 released
