### ISSUE TITLE
LaTeX Math Support

### ISSUE THREAD

**Issue by lyy1994** [neilsustc/vscode-markdown#106]
It seems that current version does not support LaTeX Math, e.g., `$formula here$`.

It will be nice if you can support it.

**Comment by neilsustc** [comment]
A simple way is to add `<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'></script>` in your md file.
One thing to note is that the default inline math delimiter is `\(\)`, which should be `\\(\\)` in markdown.
(You can also use KaTeX)

**Comment by lyy1994** [comment]
Thanks! It helps a lot!

**Comment by visualer** [comment]
and please use MathJax if this feature is added, KaTeX is still rather incomplete

**Comment by neilsustc** [comment]
I just made a preview version. You can download [it](https://github.com/neilsustc/vscode-markdown/releases/download/beta/markdown-all-in-one-1.1.0-math.vsix) and have a try.
And... it uses KaTeX 😂

**Comment by visualer** [comment]
well preview isn't working, and print to html is good... tried to screencap but can't upload it, firewall you know, XD

adding script tag will evoke that security warning, while trying to click that warning and setting security level is totally useless, and that can only be disabled in command panel

**Comment by neilsustc** [comment]
Oh, I forgot that vscode v1.21.0 has problem applying custom (or extension contributed) stylesheets.
I'm using insider build and it seems to work well.
(By design, you don't have to add other scripts or stylesheets.)

**Comment by Splike** [comment]
+1 for this feature!

**Comment by neilsustc** [comment]
The preview build is available in the [releases page](https://github.com/neilsustc/vscode-markdown/releases). You can try it, and then tell me the result.
If it works well, I will release it soon.

**Comment by RoyiAvital** [comment]
Is the current version use KaTeX or MathJaX?

**Comment by yzhang-gh** [comment]
KaTeX

**Comment by RoyiAvital** [comment]
Any chance to add MathJaX support in addition to KaTeX?
Like letting the user to select the Math Rendering Engine?

MathJaX is almost fully compliant with LaTeX while KaTeX misses few abilities.

**Comment by yzhang-gh** [comment]
Unlikely. KaTeX is more promising than MathJaX. For the missing features, you can report them to the KaTeX repository. The only chance for MathJaX is there are some *really popular* features but not in the KaTeX's roadmap.

**Comment by RoyiAvital** [comment]
Too bad.
Because for me the most important thing is to have compatibility with LaTeX and StackExchaneg editor.
StackExchange is using MathJaX.

I don't see anything more promising in KaTeX than MathJaX.
I find KaTeX targeting casual Math writing while MathJaX targeting people expecting full LaTeX experience.

**Comment by yzhang-gh** [comment]
I don't expect everyone to have the same preference. Your request is just **not popular enough**.

You can open a new issue "Add MathJax option" and I am going to do it if I can see many votes.

If you really prefer MathJax, PR is welcomed.

**Comment by RoyiAvital** [comment]
I wish I had the programming knowledge to do it.
I'm a student using MarkDown for Math Writing.

What I can suggest, maybe, is copying the support from [Markdown Preview Enhanced](https://github.com/shd101wyy/vscode-markdown-preview-enhanced).

**Comment by AndyYangjd** [comment]
> 
> 
> I wish I had the programming knowledge to do it.
> I'm a student using MarkDown for Math Writing.
> 
> What I can suggest, maybe, is copying the support from [Markdown Preview Enhanced](https://github.com/shd101wyy/vscode-markdown-preview-enhanced).

Writing a article with markdown & MathJax is a very good idea for students in Sciences.
This combination is a good replacement for Latex in less formal situation.
But maybe it's not important for other domains.

**Comment by RoyiAvital** [comment]
Any chance buying you 2 coffees and a Beer would help :-)?

Really, the students among us would kill for MathJaX support.

Thank You.

**Comment by yzhang-gh** [comment]
Moved to #531.
