### ISSUE TITLE
Indented tables are not formatted

### ISSUE THREAD

**Issue by jsmedmar** [neilsustc/vscode-markdown#107]
## What is the problem?

Tables that are indented don't get formatted

## How can I reproduce it?

```markdown
1. A table inside a list element:

    | emoji | name |
    |-------|------|
    | 🔧 | wrench |
```

Then <kbd>alt</kbd> + <kbd>shift</kbd> + <kbd>f</kbd> .

**Comment by neilsustc** [comment]
I see
