### ISSUE TITLE
TOC不支持中文？

### ISSUE THREAD

**Issue by ppggff** [neilsustc/vscode-markdown#11]

**Comment by neilsustc** [comment]
是可以支持的，只不过一直没人提就没做😂

**Comment by neilsustc** [comment]
我打包了一个新版本，你可以先试试看有没有什么问题 [v0.7.3](https://github.com/neilsustc/vscode-markdown/releases/tag/v0.7.3)

**Comment by ppggff** [comment]
赞，我的例子没问题

**Comment by neilsustc** [comment]
行，那我就发布了 👍
