### ISSUE TITLE
Extensions on enter & backspace not found.

### ISSUE THREAD

**Issue by BillYang2016** [neilsustc/vscode-markdown#112]
# What is the problem?
After updated to the latest version of vscode,I can't input enter or backspace.  
The console showed these messages :
`command 'markdown.extension.onEnterKey' not found`
`command 'markdown.extension.onBackspaceKey' not found`

# How can I reproduce it?
1. Update vscode to 1.21.0.
2. Open an markdown file.
3. Press enter or backspace.

**Comment by neilsustc** [comment]
Since vscode v1.21.0 introduces a API change, you need to use v1.1.0 of this extension.
Can you confirm that your extension is already updated and reloaded?

**Comment by BillYang2016** [comment]
Thank you very much.
