### ISSUE TITLE
Running the contributed command:'markdown.extension.printToHtml' failed

### ISSUE THREAD

**Issue by zacjordaan** [neilsustc/vscode-markdown#113]
Command `Print current document to HTML` results in error message `Running the contributed command:'markdown.extension.printToHtml' failed`

This command worked fine prior to updating vscode to v1.21.0
I am using v1.1.0 of Markdown All In One

Suspect it is due to a new vscode change/bug in using setting 'markdown.styles', see here:
https://github.com/Microsoft/vscode/issues/45260#issuecomment-371438399

**Comment by neilsustc** [comment]
Do you see any error message in the console (menubar>help>toggle dev tools)?

**Comment by zacjordaan** [comment]
Dev tools only repeats the same error msg:
`Running the contributed command:'markdown.extension.printToHtml' failed.`

**Comment by neilsustc** [comment]
Maybe there is more information if you expand that message by clicking the triangle (if there is any).
Or it might be related with the user css as you said. Did you try to print with no custom css?
It is really hard to say what is wrong given only this simple error text.

**Comment by zacjordaan** [comment]
The additional information is not really helpful...
```js
e.onDidNotificationChange	@	notificationsAlerts.ts:39
(anonymous)	@	notificationsAlerts.ts:28
e.fire	@	event.ts:142
e.notify	@	notifications.ts:127
e.error	@	notificationService.ts:58
t.onError	@	commandsHandler.ts:326
(anonymous)	@	commandsHandler.ts:311
done	@	winjs.base.raw.js:1391
v	@	winjs.base.raw.js:1237
enter	@	winjs.base.raw.js:914
_run	@	winjs.base.raw.js:1081
_error	@	winjs.base.raw.js:1054
e.resolveErr	@	lazyPromise.ts:78
e._receiveReplyErr	@	rpcProtocol.ts:154
e._receiveOneMessage	@	rpcProtocol.ts:99
(anonymous)	@	rpcProtocol.ts:33
(anonymous)	@	rpcProtocol.ts:213
e.fire	@	event.ts:142
(anonymous)	@	ipc.net.ts:81
emitOne	@	events.js:96
emit	@	events.js:191
readableAddChunk	@	_stream_readable.js:178
Readable.push	@	_stream_readable.js:136
onread	@	net.js:560
```
**But**... printing without any custom stylesheets **does** work!

So this bug is indeed caused by the recent change to vscode preview styles permissions. Not much you can do about it until vscode is updated to account for it.

**Comment by neilsustc** [comment]
Thanks, I'll keep an eye on it. 😉

**Comment by zhongliwu** [comment]
Hi @neilsustc , the same issue happens again. Once I open the preview window, the error will appear.
See attached files for logs.
[issues.txt](https://github.com/neilsustc/vscode-markdown/files/1823917/issues.txt)

**Comment by neilsustc** [comment]
This seems to be an upstream issue. I would recommend to use vscode latest insider build.

**Comment by zhongliwu** [comment]
My vsc version is 1.12. Can you please tell me what do you mean 'latest insider build'?

**Comment by neilsustc** [comment]
1.12 seems to be a really old version. The latest stable version is v1.21.1 which might already resolve this issue.
<https://code.visualstudio.com/updates/v1_21>
<https://code.visualstudio.com/insiders/>

**Comment by AliDorostkar** [comment]
Hi,
This issue happens for me when I specify a css style sheet.

**Comment by zacjordaan** [comment]
I am running v1.21.1 but this issue persists:

*Running the contributed command:'markdown.extension.printToHtml' failed.*
The developer tools console reveals no useful information about the error.

In my USER SETTINGS I am using:
```javascript
    "markdown.styles": [
        ".vscode\\vsc-base.css",
        ".vscode\\vsc-gfm.css"
    ]
```
...this is probably where the error originates, since vscode has changed the way it allows references to external style sheets; refer to this thread for more background: [https://github.com/Microsoft/vscode/issues/45260](https://github.com/Microsoft/vscode/issues/45260)

**Comment by neilsustc** [comment]
Please try [v1.1.1-fix113](https://github.com/neilsustc/vscode-markdown/releases/download/beta/markdown-all-in-one-1.1.1-fix113.vsix)

**Comment by zacjordaan** [comment]
Unfortunately VSIX Installer Failed.
Probably not an issue from your side though... I'll dig a bit deeper and see if I can find the issue.
```
26/03/2018 13:51:44 - Microsoft VSIX Installer
26/03/2018 13:51:44 - -------------------------------------------
26/03/2018 13:51:45 - Initializing Install...
26/03/2018 13:51:45 - Extension Details...
26/03/2018 13:51:45 - 	Identifier         : markdown-all-in-one
26/03/2018 13:51:45 - 	Name               : Markdown All in One
26/03/2018 13:51:45 - 	Author             : yzhang
26/03/2018 13:51:45 - 	Version            : 1.1.1
26/03/2018 13:51:45 - 	Description        : All you need to write Markdown (keyboard shortcuts, table of contents, auto preview and more)
26/03/2018 13:51:45 - 	Locale             : en-US
26/03/2018 13:51:45 - 	MoreInfoURL        : 
26/03/2018 13:51:45 - 	InstalledByMSI     : False
26/03/2018 13:51:45 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
26/03/2018 13:51:45 - 
26/03/2018 13:51:45 - 	SignatureState     : Unsigned
26/03/2018 13:51:45 - 	Supported Products : 
26/03/2018 13:51:45 - 		Microsoft.VisualStudio.Code
26/03/2018 13:51:45 - 			Version : 
26/03/2018 13:51:45 - 
26/03/2018 13:51:45 - 	References         : 
26/03/2018 13:51:45 - Signature Details...
26/03/2018 13:51:45 - 	Extension is not signed.
26/03/2018 13:51:45 - 
26/03/2018 13:51:45 - Searching for applicable products...
26/03/2018 13:51:54 - Found installed product - Microsoft Visual Studio 2012 Shell (Integrated)
26/03/2018 13:51:54 - Found installed product - Microsoft Visual Studio Community 2015
26/03/2018 13:51:54 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
26/03/2018 13:51:54 - Found installed product - Global Location
26/03/2018 13:51:54 - Found installed product - ssms
26/03/2018 13:51:54 - Found installed product - ssms
26/03/2018 13:51:54 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by neilsustc** [comment]
You can try to uninstall first (then reload, install, reload)

**Comment by zacjordaan** [comment]
I managed to install it manually with the integrated `Install from VSIX` command but the original issue remains.

To be clear, your extension works when it uses it's own styling, but as soon as I reference my own css files in user settings `markdown.styles` then the error occurs.

**Comment by neilsustc** [comment]
I test it with vscode v1.21.1 portable.
Workspace setting:
```
"markdown.styles": [
    ".vscode\\bootstrap.min.css"
]
```
And it works well 😳.

---

Would you please have a look at `C:\Users\[username]\.vscode\extensions\yzhang.markdown-all-in-one-1.1.1\out\src\print.js` line 63. It should be `.concat(getCustomStyleSheets().map(s => isAbsolute(s) ? s : path.join(path.dirname(doc.fileName), s)));` instead of `.concat(getCustomStyleSheets())`

**Comment by zacjordaan** [comment]
Yes, line 63 contains the new code.

What I've tried, without any success:
- Place css reference in workspace instead of user settings
- Change markdown preview security setting to allow insecure content
- Reference only a *single* css file
- Use *bootstrap.min.css*
- Use a completely minimal/basic markdown file to test with

Since it works for you, the issue must be due to some difference in my installation of vscode.

If anybody else reports a problem then maybe we can figure out what that difference is. Until then I'll need to move on and just live without html export for a while.

Thanks for trying to help anyway.

**Comment by zacjordaan** [comment]
Ok, I'm getting closer to figuring this out: my markdown file was within a _subfolder_ beneath my root!

When trying to `Print current document to HTML` I receive the `Running the contributed command:'markdown.extension.printToHtml' failed.` error.

If I move my markdown document to _root_ and then try again, it _mostly_ works... no error received and the html file is created. However, my _custom_ css styles are not taking effect.

At least the primary error is gone... now I can look at the way that custom css styles are included in output and hopefully cross the finish line...

**Comment by zacjordaan** [comment]
Success!

My css styles (created many moons ago) had references to `.vscode-body` classes that _used_ to be required by the vscode preview.

Once I removed those, the preview continued to appear as desired _AND_ printing the current document to HTML worked perfectly.

Happy days! Thank you for your help.
My only suggestion is to allow operations from within subfolders but other than that, all is well again.

**Comment by neilsustc** [comment]
😀 Good to know.

Your finding makes much sense because the extension assumes your CSS files' paths are relative to the current doc. Maybe I need to catch these "file not found" error and tell user which file causes error instead of showing only "command failed"

**Comment by Rene-Sackers** [comment]
I still have issues with this.
This is my entire project structure:
![structure](https://i.imgur.com/MIjhiXX.png)

And this is my workspace settings file (.vscode\settings.json):
```
{
    "markdown.styles": ["style.css"]
}
```

And this is all that is in my .css file:
```
body {
    background: #333;
}
```

Giving me that same running the command failed message.

@zacjordaan mind sharing how your workspace looks, and what setting you ended up with for `"markdown.styles"`?

**Comment by neilsustc** [comment]
@Rene-Sackers Are you using the [fixed build](https://github.com/neilsustc/vscode-markdown/releases) (fix113). If it is, you will see a warning message saying which css file path is wrong.
And of course remember not to use a too old version of VSCode.

**Comment by Rene-Sackers** [comment]
@neilsustc My apologies, the fixed build works just fine ;) I somehow gathered that the fix was already in the released version.

**Comment by Rene-Sackers** [comment]
One more issue, the setting says `Relative paths are interpreted relative to the folder open in the explorer. If there is no open folder, they are interpreted relative to the location of the markdown file.`, but it seems to always be relative to the file for me.

With this folder structure:
![structure](https://i.imgur.com/pEsKCYy.png)

And this setting:
`"markdown.styles": ["style.css"]`

I can print `roottest.md`, but not `subtest.md`. But I can print `subtest.md` if I change the style.css to `..\\style.css`, and then roottest.md doesn't work anymore.

**Comment by neilsustc** [comment]
It now always parses paths w.r.t the MD file. I'll add a opened folder check later

**Comment by gusbemacbe** [comment]
I have the same problem as @zacjordaan.

I put the "github-markdown.css" inside the ".vscode" folder, and I put ".vscode/github-markdown.css" in the "markdown-style". I printed to HTML and I received the same alert of not being found. I have base64-encoded fonts inside the github-markdown.css. 

And I use 1.23 of VSCode Insiders.

Maybe it can be a bug.

**Comment by neilsustc** [comment]
What does the path look like in the alert message? It should be an absolute path. Does it point to your CSS?

**Comment by gusbemacbe** [comment]
> What does the path look like in the alert message?

I referred to @zacjordaan's error:

> When trying to Print current document to HTML I receive the Running the contributed command:'markdown.extension.printToHtml' failed. error.

![screen shot 2018-04-10 at 04 06 59](https://user-images.githubusercontent.com/2257024/38541215-c4b17858-3c74-11e8-9d7c-0c038bb4ad58.png)

![screen shot 2018-04-10 at 04 07 15](https://user-images.githubusercontent.com/2257024/38541224-cad8ee64-3c74-11e8-8a45-98ea4ae39884.png)

It used to work before, now after having added the base64-encoded webfonts, it has stopped of working. 

![screen shot 2018-04-10 at 04 09 19](https://user-images.githubusercontent.com/2257024/38541271-fbbc3d42-3c74-11e8-9474-1728def9fc48.png)

I have also used the absolute path, restarted, printed to HTML and received the same alert.

**Comment by neilsustc** [comment]
I think it might be another kind of issue. If the CSS path is wrong, you will see

![image](https://user-images.githubusercontent.com/7588612/38541852-dbf0ce70-3cd2-11e8-88fc-63acecdd5a0a.png)

It looks like your CSS path is correct but there is something else causing the error (maybe the webfont you mentioned).
Could you pack a simplified sample of files for me to test?

**Comment by gusbemacbe** [comment]
[Compacted pack in ZIP](https://github.com/neilsustc/vscode-markdown/files/1893388/Atletica.FACIC.zip)

**Comment by neilsustc** [comment]
Things work well on my PC, no error 😳.

Have you check the dev console (menu>help>toggle dev tools)? Any useful info there?

**Comment by gusbemacbe** [comment]
Here are the logs:

[-1523347784123.log](https://github.com/neilsustc/vscode-markdown/files/1893681/-1523347784123.log)
[-1523347784125.log](https://github.com/neilsustc/vscode-markdown/files/1893682/-1523347784125.log)

**Comment by gusbemacbe** [comment]
Here is the yellow alert: `Custom style '/Users/gusbemacbe/Pictures/Atlética FACIC/.vscode/atletica.css]' not found.`

**Comment by neilsustc** [comment]
For the error "command ... *failed*", it means there is internal error when executing the command.
For the error "command ... *not found*", it might because the extension is been loading, then you need to wait for 2 seconds.

If you can see the yellow alert, it means the command has been executed. Do you notice the last `]` in the path. I find a `"` is missing in the file you sent and add it when testing.

![image](https://user-images.githubusercontent.com/7588612/38545163-faab2726-3cdb-11e8-8479-616756fcc738.png)

**Comment by gusbemacbe** [comment]
Yes, I have noticed it, but I also have put " and did the same things — restarted, printed and received the same alerts until I disabled all the extensions, except this one, and I was able of printing.

**Comment by neilsustc** [comment]
Okay, so now my understanding is the only problem is that,
you get a yellow alert saying `/Users/gusbemacbe/Pictures/Atlética FACIC/.vscode/atletica.css` (no `]` any more) not found, but you can make sure the path is correct and file exists, right?
(You can open a new issue so that others people won't be bothered)

**Comment by gusbemacbe** [comment]
I had to discover one by one what caused your extension to fail. 

Now I have discovered an extension which caused your extension to stop of working. It is https://github.com/kamikillerto/vscode-colorize. 

It is unnecessary to open a new issue if we have the same problem for avoiding the duplicates.

**Comment by gusbemacbe** [comment]
Download this extension and test with this enabled extension and that same pack I shared to you.

**Comment by neilsustc** [comment]
Still no error... 😳

**Comment by gusbemacbe** [comment]
Maybe because you are a Windows user and I am a Mac user. There must not be error in VSCode on Windows, but there does on Mac. With Colorize enabled, print to HTML from Markdown doesn't work, but with Colorize disabled, it works.

**Comment by neilsustc** [comment]
I opened a new issue to track this. I will test it later when I have a chance.

**Comment by JeffRockatansky** [comment]
I am also having this issue for some reason. 
VS Code v1.24.1
Markdown All In One v1.4.0
Have a lot of errors in dev tools. 
Disabled every other extension - still doesn't work. 
Have a Russian Language Pack for Visual Studio Code from Microsoft. 
No custom css are being used.

**Comment by neilsustc** [comment]
@JeffRockatansky You can find the latest information in #205. Please install the debug version and try to find some messages starting with `[debug]`. Then I can know better why it fails. Thanks.

**Comment by DominikDitoIvosevic** [comment]
I would like to confirm that I'm still experiencing this issue. Tried fresh install and the command doesn't work

**Comment by yzhang-gh** [comment]
More information will be appreciated.

This issue is almost a year old and actually is a mix of many different issues.
So what is exactly your issue? "command **not found**" _or_ "command **failed**"?
Is there any other error message?

From your description, I guess it is more likely a "cmd not found" rather than "cmd failed" problem.
Feel free to open a new issue if needed.
