### ISSUE TITLE
cannot Enter with v1.1.0 version

### ISSUE THREAD

**Issue by liuyang1** [neilsustc/vscode-markdown#115]
after press "enter" key, it pop "command 'markdown.extension.onEnterKey' not found" message, and cannot insert "newline"

- install v1.1.0 version, last version don't have this issue. so it's regression.
- use all default config

workbench.main.js:sourcemap:4183 Extension `yzhang.markdown-all-in-one` failed to activate. Reason: unknown dependency `vscode.markdown-language-features`.
R._logMessageInConsole @ workbench.main.js:sourcemap:4183
workbench.main.js:sourcemap:253 [Extension Host] rejected promise not handled within 1 second
t.log @ workbench.main.js:sourcemap:253
workbench.main.js:sourcemap:1306   ERR Git model not found

**Comment by zhycen** [comment]
Same Issue, Cannot enter or delete.

**Comment by neilsustc** [comment]
You need to update vscode to v1.21.0 because the API is changed

**Comment by liuyang1** [comment]
Thanks! Sorry for duplicate reported issue.
