### ISSUE TITLE
bug: command 'markdown.extension.onBackspaceKey' not found

### ISSUE THREAD

**Issue by MisakaMikoto19090** [neilsustc/vscode-markdown#117]
常用的按键都会提示问题:

command 'markdown.extension.onBackspaceKey' not found
command 'markdown.extension.onEnterKey' not found
command 'markdown.extension.onTabKey' not found

同时开启的扩展
markdownlint
关闭后.依旧提示

**Comment by neilsustc** [comment]
新版本的插件需要 vscode v1.21.0，更新一下应该就可以了

**Comment by MisakaMikoto19090** [comment]
刚升级完.想反馈.没想到已经回复了.我把这个关掉了.作者大大辛苦了.

**Comment by neilsustc** [comment]
😀

**Comment by jsta** [comment]
For the non-chinese speakers finding this page from search engines, the solution is to upgrade vscode to v1.21.0

**Comment by MisakaMikoto19090** [comment]
thank you anyway @jsta. I figured it out a few moments later ,and closed this issue.

**Comment by maoxiaoke** [comment]
This is caused by markdown-all-in-one. Uninstall the extension were help.
