### ISSUE TITLE
[Bug] why am I getting the message: "visual code" markdown.extension.onbackspacekey not found

### ISSUE THREAD

**Issue by mwherman2000** [neilsustc/vscode-markdown#119]
"visual code" markdown.extension.onbackspacekey not found

Everytime I open a MD file

workbench.main.js:sourcemap:253 [Extension Host] Extension `yzhang.markdown-all-in-one` failed to activate. Reason: unknown dependency `vscodeac.markdown-language-features`.
t.log @ workbench.main.js:sourcemap:253
workbench.main.js:sourcemap:4183 Extension `yzhang.markdown-all-in-one` failed to activate. Reason: unknown dependency `vscode.markdown-language-features`.
R._logMessageInConsole @ workbench.main.js:sourcemap:4183

**Comment by neilsustc** [comment]
You need to update your vscode to latest v1.21.1
