### ISSUE TITLE
No outline if first-level title is missing

### ISSUE THREAD

**Issue by borisschapira** [neilsustc/vscode-markdown#120]
If the markdown file does not present a first-level title (one `#`), the ouline is not produced. Unfortunately, when using Static Site Generators like Jekyll or Hugo, the first level title is often managed by the front-matter title attribute, and the titles inside the document start at `##`.

Could you support that type of document, please (and thanks for all you've done so far, the plugin is very useful)?

## How can I reproduce it?

A document with only `##` titles has no outline on the VSCode Outline area.

## Is there any error message in the console? (from menubar -> Help -> Toggle Developer Tools)

No there isn't.

**Comment by neilsustc** [comment]
You can download and use [this preview version](https://github.com/neilsustc/vscode-markdown/releases/download/beta/markdown-aio-1.1.0-outline-fix.vsix).

**Comment by borisschapira** [comment]
Wonderful! Thank you very much!
