### ISSUE TITLE
Shortcut to end list

### ISSUE THREAD

**Issue by garyking** [neilsustc/vscode-markdown#121]
Please make it so that when editing a list item, if I hit a shortcut, then I'll move on to the next line and the list also ends. This is how Markdown lists work in the Sublime Text package, for example.

For instance, I have:

```markdown
- Test
```

With the cursor at the end of the item, I should be able to hit `cmd+Enter` to move to the next line and end the list, meaning the next line won't automatically add a `- ` at the start of it.

**Comment by neilsustc** [comment]
Just hit <kbd>Enter</kbd> again, the `- ` will be removed.

That means if you have this (using `|` to indicate cursor)

```markdown
- Test
- |
```

press <kbd>Enter</kbd>, you get

```markdown
- Test

|
```

I think this is better because it is a good habit to end list with an empty line

**Comment by garyking** [comment]
Okay fair enough, if it is a conscious design decision, then I can live with it.
