### ISSUE TITLE
List does not continue if there's a URL in the last item

### ISSUE THREAD

**Issue by garyking** [neilsustc/vscode-markdown#122]
Create a new Markdown file, with the following content:

```markdown
- [test](test) Test
```

Hit Enter at the end. The list ends, rather than adding a `- ` to begin a new item. This happens as long as the URL syntax is being used somewhere in the line.

**Comment by neilsustc** [comment]
Thanks for your report. You can download [the preview version](https://github.com/neilsustc/vscode-markdown/releases/download/beta/markdown-all-in-one-1.1.0-fix122.vsix) to fix this.
