### ISSUE TITLE
Change keyboard shortcut for bold and italics to not conflict with default VSC shortcuts

### ISSUE THREAD

**Issue by garyking** [neilsustc/vscode-markdown#123]
Please consider changing the default keyboard shortcuts for bold and italics so that they don't conflict with the default VSC shortcuts of "Toggle Side Bar" and "Select Line" respectively. I know I can change them myself though, if necessary, too.

Perhaps `Cmd+Shift+B` instead?

**Comment by neilsustc** [comment]
The default keybindings are assigned to mimic the behavior in other editor like Word, Caret etc.
I would suggest you to change them according to your preference.

**Comment by dslounge** [comment]
We can change them, but it's probably not great practice to override shortcuts that users are already accustomed to.
