### ISSUE TITLE
command 'markdown.extension.editing.toggleBold' not found

### ISSUE THREAD

**Issue by jgclark** [neilsustc/vscode-markdown#125]
Running v1.1.0 on macOS 10.12.6 I get "command 'markdown.extension.editing.toggleBold' not found" when pressing cmd-b. Ditto "command 'markdown.extension.editing.toggleItalic' not found" when pressing cmd-i.

I have tried un-installing and re-installing the extension, but it still happens.

extensionService.ts:787 Extension `yzhang.markdown-all-in-one` failed to activate. Reason: unknown dependency `vscode.markdown-language-features`

I'm too new to VSC to be able to try to work out what's gone wrong here.

**Comment by neilsustc** [comment]
You need to use the latest version of vscode (v1.21.1). Just update it and everything will work well.

**Comment by jgclark** [comment]
Oh, I'd checked for updates before posting this, and it reported there weren't any.  I'll now go and download 1.21.1 from the website. Many thanks.
