### ISSUE TITLE
When surrounding text with brackets, cursor should immediately move to the end of the URL

### ISSUE THREAD

**Issue by garyking** [neilsustc/vscode-markdown#126]
When surrounding text with brackets, the cursor should immediately move to the end of the URL, so we can quickly add the URL to it. Like in Sublime:

![markdown](https://user-images.githubusercontent.com/343940/37727680-dc76fd48-2d0e-11e8-8434-2954ef9364bd.gif)

**Comment by neilsustc** [comment]
I think you would like [this].
