### ISSUE TITLE
Hotkey to toggle full page Preview?

### ISSUE THREAD

**Issue by robertpeteuil** [neilsustc/vscode-markdown#127]
I just discovered your extension and its great support of markdown.  

Is there a way to set a hotkey to toggle a full-page preview?  Essentially, the equivalent of running the command "Markdown: Open Preview".

I'm switching from another extension [preview-vscode](https://github.com/searKing/preview-vscode) which hotkey's this and it's become part of my workflow.   However, their Markdown rendering is lacking, so I'm trying to switch to your extension.

Let me know if I'm overlooking something, or if its a feature you would need to add.

**Comment by neilsustc** [comment]
If you only want to **open** the preview, then `ctrl+shift+v`/`ctrl+k v` is the hotkey.
If you also like to close the preview using the same hotkey, #86 is the request (You already found it).

**Comment by neilsustc** [comment]
Please refer to #86 and try the beta version
