### ISSUE TITLE
Table of content with more than 9 items creates wrong output with ordered list

### ISSUE THREAD

**Issue by jonasbb** [neilsustc/vscode-markdown#131]
Using the option `"markdown.extension.toc.orderedList": true,` and having 10 or more headers in a file, produces this broken table of contents.
 Every time the file is saved another set of

```md
        10. [j](#j)
        11. [k](#k)
        12. [l](#l)
    2. [B](#b)
```

lines is appended to the table of contents.

```md
# Head

1. [Head](#head)
    1. [A](#a)
        1. [a](#a)
        2. [b](#b)
        3. [c](#c)
        4. [d](#d)
        5. [e](#e)
        6. [f](#f)
        7. [g](#g)
        8. [h](#h)
        9. [i](#i)
        10. [j](#j)
        11. [k](#k)
        12. [l](#l)
    2. [B](#b)
        10. [j](#j)
        11. [k](#k)
        12. [l](#l)
    2. [B](#b)
        10. [j](#j)
        11. [k](#k)
        12. [l](#l)
    2. [B](#b)

## A

### a
### b
### c
### d
### e
### f
### g
### h
### i
### j
### k
### l 

## B
```

This error does *not* happen for unordered lists.
I currently cannot test, if using the setting `"markdown.extension.orderedList.marker": "one",` would fix my problem, because this setting does not work on my system, see bug #130.

To reproduce this, just copy the markdown and safe it a couple of times.
I can reproduce this with VS Code Version 1.21.1 and the markdown extension version 1.1.1.
There are no errors in the developer tools console.

**Comment by neilsustc** [comment]
Please try the [beta version](https://github.com/neilsustc/vscode-markdown/releases/download/beta/markdown-all-in-one-1.1.1-fix130-131.vsix)

**Comment by jonasbb** [comment]
@neilsustc Thanks for the quick fixes of the bugs. Both bugs are gone with this beta version.
