### ISSUE TITLE
[Feature request] CriticMarkup support

### ISSUE THREAD

**Issue by rmrnc** [neilsustc/vscode-markdown#132]
Hi,
I wonder whether you'd be interested in supporting [CriticMarkup](http://criticmarkup.com/). Actually, I am not interested in tracking changes with Markup (after all, we have Git for that, right?), but highlighting text and comments would help with perusing and editing documents in a collaborative environment.
Ideally, the explorer outline would include (truncated) comments and highlights.

Makes sense?

**Comment by neilsustc** [comment]
It seems more like a dialect of Markdown (or simply a new Markup at all). And there are also many other variants of Markdown we already have.

So personally, I think it would be better to have a specialized extension to support it.
