### ISSUE TITLE
ToC broken because of emoji

### ISSUE THREAD

**Issue by mikederksen** [neilsustc/vscode-markdown#133]
When an emoji is used in a header, the table-of-content link will not be generated properly.

`# foo 💣` as header generates `    - [foo 💣](#foo-%F0%9F%92%A3)`, wich is invalid.
The solution would be to ignore the emoji. This does work: `    - [foo 💣](#foo-)`

Nope. The link is just broken

**Comment by neilsustc** [comment]
I guess `- [foo 💣](#foo-%F0%9F%92%A3)` works well within vscode preview, right?
And there is a setting `encodeUri` you can set to `false`. Then it will be `- [foo 💣](#foo-💣)`
See more information in #98.
