### ISSUE TITLE
Markdown preview hotkey conflicts with paste

### ISSUE THREAD

**Issue by SkeLLLa** [neilsustc/vscode-markdown#134]
Details:
    VSCode Version: 1.21
    OS Version: Linux

Steps to Reproduce:

    Hit Ctrl+Shift+V in a terminal window

Expected behavior:
Text from the clipboard is pasted into the terminal window.

Actual behavior:
'markdown.extension.togglePreview' is activated

Propositions:
* remove default keybinding from system-wide Ctrl+Shift+V
* replace it with something else
* add whem `"when": "editorLangId == 'markdown'"`

Also now it will be conflicting with built-in vscode markdown preview.

**Comment by neilsustc** [comment]
Thanks for reporting. You can install the [fixed version](https://github.com/neilsustc/vscode-markdown/releases/download/beta/markdown-all-in-one-1.1.1-fix134.vsix) now.
