### ISSUE TITLE
0.7.4版本在没有打开的workspace时无法工作

### ISSUE THREAD

**Issue by ppggff** [neilsustc/vscode-markdown#14]
提交”handle activation events by hand"使得没有打开workspace时无法工作，
例如，按回车键报类似找不到对应的触发函数的错误

---

Translated:
v0.7.4 won't work when a single file (rather than a folder) is opened.

**Comment by neilsustc** [comment]
哦，有道理！让我看看

**Comment by neilsustc** [comment]
This should be fixed in v0.7.5.

**Comment by Ytrog** [comment]
I still see this happen in 0.7.5 :(

**Comment by neilsustc** [comment]
I'll have a look now 😥

**Comment by neilsustc** [comment]
Please try v0.7.6

**Comment by wkevin** [comment]
0.7.6 still report warn：“command 'markdown.extension.onEnterKey' not found” in ubuntu

**Comment by neilsustc** [comment]
How do you open your Markdown file?

And could you have a look at the console to see if there is any error reported? (vscode menu>help>toggle developer tools)

**Comment by neilsustc** [comment]
Okay, finally I decide to go back to legacy activation events. There should be no problem now.
