### ISSUE TITLE
Extreme latency in 1.22.1 on input

### ISSUE THREAD

**Issue by erichiller** [neilsustc/vscode-markdown#141]
With the release of 1.22.1 whenever input is received is called the entire editor is slowed to the point that no futher input is accepted. The only fix is to either disable the extension.

I can make specified types of input work by disabling the relevant keys such as `onEnter` with:

```
{
  "key": "enter", 
  "command": "-markdown.extension.onEnterKey",
  "when": "editorTextFocus && !suggestWidgetVisible && editorLangId == 'markdown'" 
}
```

I found this with both `[enter]` and `[backspace]` so far

Potentially relevant settings:

```
	"editor.formatOnPaste": false,
	"editor.formatOnSave": false,
	"editor.autoIndent": true,
	"editor.formatOnType": false,

	"[markdown]": {
		"editor.detectIndentation": false,
		"editor.insertSpaces": true,
		"editor.tabSize": 4,
	},
	"markdown.extension.italic.indicator": "_",
	"markdown.extension.orderedList.marker": "ordered",
	"markdown.extension.toc.updateOnSave": false,
	"files.autoSave": "afterDelay",
	"files.autoSaveDelay": 1000,
```

Besides these, all that is done to reproduce is type any input and experience lag or lack of response from the editor.

**Comment by neilsustc** [comment]
I just tested it with the vscode v1.22.1 portable build and everything seems to work well.
Have you tried to disable other extensions except for this one?
I remember this issue was reported before when there is another extension (someone about GitHub?) but I can't find that issue now.

**Comment by erichiller** [comment]
Potentially the github styling template? Is there a programmatic way to check which extensions have hooks into a given keypress? or a given filetype? It would help narrow down the possibilities for me.

**Comment by neilsustc** [comment]
I remember that I have checked the conflicted extension and it didn't hook the key.
So it is still a mystery for me...
I suggest to test the mentioned GitHub extension first.
If it isn't... Then maybe binary search? 🤣

**Comment by neilsustc** [comment]
I guess you get my point.
If you have 16 other extensions, you only need at most 4 times to find out the bad extension (who conflicts with this extension). Just disable half of the untested extensions every time.
