### ISSUE TITLE
Allow to quote text

### ISSUE THREAD

**Issue by garyking** [neilsustc/vscode-markdown#142]
If we select text and hit single or double quotes, please quote the selected text, instead of replacing the selected text with a quote character. 

This would make it work like in other programming languages, then.

**Comment by neilsustc** [comment]
This is done by the vscode official Markdown extension.

You can do this by making a PR changing [line36](https://github.com/Microsoft/vscode/blob/master/extensions/markdown-basics/language-configuration.json#L36)

```
"surroundingPairs": [
	["(", ")"],
	["[", "]"],
	["`", "`"]
]
```

to

```
"surroundingPairs": [
	["(", ")"],
	["[", "]"],
	["`", "`"],
	["'", "'"],
	["\"", "\""]
]
```
