### ISSUE TITLE
Cycle Unordered List Markers

### ISSUE THREAD

**Issue by onomori** [neilsustc/vscode-markdown#145]
More of a feature request than a problem:

Would it be possible to cycle the unordered list markers when you press tab to indent? I see that there's a setting to change the list marker to -, +, or * and it's all working fine but I've gotten used to Sublime's and Atom's respective Markdown plugins to do that. For example:

```markdown
- Lorem ipsum
- Lorem ipsum
  + Lorem ipsum
  + Lorem ipsum
     * Lorem ipsum
  +  Lorem ipsum
-  Lorem ipsum
```

Likeso.

**Comment by neilsustc** [comment]
Could you provide a link of one of those extensions so I can know how it works?

**Comment by onomori** [comment]
Hmm, so I thought md-writer for Atom does this but apparently it doesn't. I vaguely remember having it but maybe I was using another plugin that I can't remember now.

[MarkdownEditing](https://github.com/SublimeText-Markdown/MarkdownEditing/) for Sublime does it though. Related part is defined [here](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/indent_list_multiitem.py) and it makes lists cycle *, +, - on <kbd>tab</kbd> or <kbd>shift + tab</kbd>

**Comment by neilsustc** [comment]
Thanks. But personally I don't like this idea. Maybe I would add a keybinding to switch the list marker.

**Comment by onomori** [comment]
Got it. Ultimately it's more of a visual preference than an actual problem and as long as it parses right, I'm cool with just dropping it. Keybinding to easily switch would be sweet though.

Either way, thanks for the consideration and good work!
