### ISSUE TITLE
Table Format Poor visualization When

### ISSUE THREAD

**Issue by occultskyrong** [neilsustc/vscode-markdown#146]

**Comment by neilsustc** [comment]
你可以到 [这里](https://github.com/be5invis/Sarasa-Gothic/releases) 下载 `sarasa-gothic-ttf-0.5.2.7z`，然后安装里面的 `Sarasa Mono SC`，重启 vscode，设置一下字体就好

**Comment by occultskyrong** [comment]
多谢。。我以为作者是个外国友人。。想着字体/全角的问题就不麻烦他了。。
0.0
谢了
