### ISSUE TITLE
ToC broken because of underscore

### ISSUE THREAD

**Issue by lufinima** [neilsustc/vscode-markdown#147]
When an underscore is used in a header, the table-of-content link will not be generated properly.

Using: 
# Section print\_forms
or
# Section `print_forms`
As header generates:
- [Section print\_forms](#section-printforms)
or
- [Section `print_forms`](#section-printforms)
Wich is invalid.

Apparently the solution seems to keep the underscore or replace the underscore with hyphen. 
This does work: 
- [Section print\_forms](#section-print-forms)
or
- [Section `print_forms`](#section-print-forms)
or
- [Section print\_forms](#section-print_forms)
or
- [Section `print_forms`](#section-print_forms)

Setting  "markdown.extension.toc.encodeUri": false doesn't work either.
The link is just broken

**Comment by neilsustc** [comment]
Could you please test [this fixed version](https://github.com/neilsustc/vscode-markdown/releases/download/beta/markdown-all-in-one-1.1.2-fix147.vsix)?

**Comment by lufinima** [comment]
The fix is working, thanks.

**Comment by lufinima** [comment]
However if "markdown.extension.toc.githubCompatibility": true, is doing the same as before

**Comment by neilsustc** [comment]
This should be fixed in v1.2.0 😉
