### ISSUE TITLE
[Outline view] Add "collapse all" menus command

### ISSUE THREAD

**Issue by ringcrl** [neilsustc/vscode-markdown#149]
![wx20180421-213932](https://user-images.githubusercontent.com/16740021/39084760-863a4ff0-45ac-11e8-9554-ec18d55d3cc0.png)

I'm a heavy user of markdown TOC, rely heavily on TOC to sort things out, and like to go deep from the outermost layer, folding other unrelated items while writing, so I can focus on the current situation.
 But now outline will expand all by default, easily disturb my view, want to add a default is folded mode.

A pr has already been submitted, but it seems possible to have a more flexible setup scheme, such as expanding several layers by default, to discuss how to set it up better

https://github.com/neilsustc/vscode-markdown/pull/148

**Comment by neilsustc** [comment]
Thanks for your effort 👍

I am wondering whether we can add a "collapse all" command just like vscode does for the file explorer

![image](https://user-images.githubusercontent.com/7588612/39085418-88bda65c-45b4-11e8-93b8-6357f41f4c9c.png)

That will be more useful than only providing a extra option to control the default collapse states. What do you think?

**Comment by ringcrl** [comment]
This is a great plan!

**Comment by neilsustc** [comment]
Would you like to implement it?

**Comment by ringcrl** [comment]
Yes,I will try to finish it later.

**Comment by neilsustc** [comment]
That is great.
Some useful resources:
<https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-view-sample>
For the icon, vscode seems to allow us to directly reference octicon icons, so <https://octicons.github.com/icon/fold/> is an option (maybe we can't, I haven't tried).

**Comment by ringcrl** [comment]
Thank you for providing useful resources, see the source code has the idea of implementation, after I will finish it

**Comment by neilsustc** [comment]
A small improvement ([beta version](https://github.com/neilsustc/vscode-markdown/releases/tag/beta))
