### ISSUE TITLE
Key value error

### ISSUE THREAD

**Issue by ElegantDandan** [neilsustc/vscode-markdown#15]
vs code error:
command 'markdown.extension.onEnterKey' not found
command 'markdown.extension.onTabKey' not found
command 'markdown.extension.onBackspaceKey' not found

**Comment by neilsustc** [comment]
I see. This bug is introduced with v0.7.4.
And I think we can track it in #14.
For the workaround, I would suggest to open a folder to edit Markdown files before I fix it (maybe tomorrow).
Thanks for your feedback!
