### ISSUE TITLE
1.2.0版本无法生成不转小写的TOC

### ISSUE THREAD

**Issue by othorizon** [neilsustc/vscode-markdown#150]
在1.2.0版本只有一个githubCompatibility选项，
但是我想生成可以兼容中文又不会把大写字母转换成小写字母的TOC怎么办？

**Comment by neilsustc** [comment]
因为**在链接里面**似乎大家都把字母小写了，如果不小写的话比如 GitHub 链接就有问题。
你是需要在哪种情况下想不要转成小写呢？

**Comment by othorizon** [comment]
@neilsustc 现在我也只能先小写了。

我是写blog用的，toc在网页上作为锚点用来跳转时会区分大小写，这种场景就很尴尬了。

**Comment by neilsustc** [comment]
对，因为我看很多地方生成锚点的时候都小写了
不过你写博客的工具不应该也是生成小写的锚点吗，比如 Jekyll

**Comment by othorizon** [comment]
@neilsustc 哈哈，谢谢了哈，搞定了。
用的hexo，去查了源码，发现有这个控制 id 大小写的选项，配置上了。

**Comment by neilsustc** [comment]
👌
