### ISSUE TITLE
Use of hard tabs in Table of Contents

### ISSUE THREAD

**Issue by espwarrior** [neilsustc/vscode-markdown#152]
Hi,

The VSCode extension 'markdownlint' I'm using to see if my markdown is sufficiently compliant generates errors MD010 (hard tabs) and MD007 (list indentation) on the TOC that your 'markdown-all-in-one' extention generates.

These errors are generated because the use of the horizontal tab character is generally discouraged.

The errors can be easily reproduced by inserting a table of contents for a document that has a couple of nested headings, per the example below. The indentation of the TOC items will be based on the horizontal tab character instead of spaces.

```
# One

## Two

### Three
```

A potential solution would be to make the string used for indentation of the (un)ordered list of the TOC configurable, such as for example `markdown.extension.toc.unorderedList.indentationString` and `markdown.extension.toc.orderedList.indentationString`. Changing the default configuration to two spaces (\x20\x20) instead of a single horizontal tab (\x09) would solve the errors and also be compatible with markdownlint out-of-the-box.

Markdownlint rules here:
<https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md>

Thanks!

**Comment by neilsustc** [comment]
This extension respects your per file indentation setting. You can change it here

![image](https://user-images.githubusercontent.com/7588612/39296322-3318e8b6-4973-11e8-9ece-4a3128b971c2.png)

Or if you would like to set it globally, use `"editor.insertSpaces": true` and `"editor.tabSize": 4`

**Comment by espwarrior** [comment]
Cool! I didn't know that! Thanks for clarifying this, and please consider this solved.
