### ISSUE TITLE
Use custom markdown list indentation configuration (e.g. from markdown lint) over global editor.tabSize

### ISSUE THREAD

**Issue by jpluimers** [neilsustc/vscode-markdown#155]
It would be nice if `vscode-markdown` could use a markdown specific tab setting over the global `editor.tabSize` one, for instance the one from `markdownlint`.

I tried the per-file setting as per https://github.com/neilsustc/vscode-markdown/issues/77#ref-commit-fd60143, but clicking on the "spaces: 4" does not allow me to change that.

# Problem

When installing, https://github.com/DavidAnson/vscode-markdownlint it will throw [MD007](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md007)

# Reproduce
Install https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md007, edit some markdown with lists, indent part of the lists, observe the [MD007](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md007) errors to appear.

# Console error messages

None

# Proposed solution

It would be really nice if `vscode-markdown` could use a markdown specific indentation setting over the `editor.TabSize`, for instance `vscode-markdown.config/lists/indent`:

```
    "vscode-markdown.config": {
        "lists": { "indent": 2 }
    }
```

Or even nicer: if `markdownlint` is installed, `vscode-markdown` could use the `markdownlint.config/MD007/indent` indentation setting for lists (and the global `editor.tabSize` for all other indentation).

# Notes

Related: https://github.com/neilsustc/vscode-markdown/issues/77

markdownlint has a markdown specific tab setting for lists:

```
    "markdownlint.config": {
        "MD007": { "indent": 2 }
    }
```

Of course one could change this to 4, but the vast majority of online markdown is using an indentation of 2, hence different proposed solutions.

**Comment by jpluimers** [comment]
One of my motivations for this suggestion is that I am moving from atom.io to vscode (which is far more responsive than atom.io and is a lot easier for doing .NET and PowerShell based projects).

In atom.io, markdown editing lists feels a lot more natural than vscode, hence the suggestion (more might follow as I recently started to make the switch and it takes time to get a proper feel for the differences).

I know how hard it is to write editors and plugins, so I understand your hesitation. Being a n00b at atom plugins, but willing to learn, maybe you do have some energy to help me guide and understand possible approaches? That way I could try to come up with pull requests to get a better feel for how hard it actually is and maybe get a bit closer.

[Markdown](https://wiert.me/category/development/software-development/lightweight-markup-language/markdown/), [reStructured text](https://wiert.me/category/development/software-development/lightweight-markup-language/restructuredtext/) and [plantUML](https://wiert.me/category/development/software-development/uml/plantuml/) are the text formats I write almost all my documentation in, so I am willing to put energy in making life as easy as possible for me editing them.

I am also aware that no tool is perfect (for instance atom.io has an issue with https://github.com/remarkjs/remark-lint/tree/master/packages/remark-lint-list-item-bullet-indent incorrectly flagging valid unordered lists), so I try to put in issue reports where appropriate and help where I can.

**Comment by jpluimers** [comment]
@neilsustc I was probably confused by this pop-up menu thinking it would convert all space indents to tabs or vice versa, or use spaces/tabs from now in stead of changing the number of characters to use for indentation:

> 
![screenshot 2018-04-28 22 38 17](https://user-images.githubusercontent.com/2033367/39400653-fc3eb528-4b34-11e8-9c84-e5ea3e461e75.png)

Where is that setting persisted?

**Comment by neilsustc** [comment]
"Indent Using Spaces/Tabs" is "start use spaces/tabs from now"
"Convert Indentation to Spaces/Tabs" is "convert indentation to spaces/tabs in current doc"
And as it is a per-file setting, I guess it is cached by vscode just like "recently opened files".

---

And FYI, the indent guides issue I mentioned above

![image](https://user-images.githubusercontent.com/7588612/39402851-35b3f7fa-4b9e-11e8-9694-0bd12c40b2a9.png) ![image](https://user-images.githubusercontent.com/7588612/39402845-16208b06-4b9e-11e8-90fa-0712684944f6.png)


Even though you can config unordered list indentation to 2, ordered list to 3, the indent guides don't know this behavior.

**Comment by neilsustc** [comment]
An update, we can have a self-adaptive indentation scheme option. See [#241-comment](https://github.com/neilsustc/vscode-markdown/issues/241#issuecomment-406998104).

**Comment by maelvalais** [comment]
I guess we can close this issue 👍

**Comment by neilsustc** [comment]
Uh, PR#319 does solve the indentation problem of TOC. But the indentation on enter/tab keys are still not changed.

I will work on it soon.

**Comment by neilsustc** [comment]
You can now try out [the dev build](https://github.com/neilsustc/vscode-markdown#latest-development-build).
