### ISSUE TITLE
minor TOC creation bug: does not correctly convert symbols to dashes

### ISSUE THREAD

**Issue by no-stack-dub-sack** [neilsustc/vscode-markdown#156]
The extension produces an incorrect TOC link for some headers.

For example, take the header `### BasicImmutable & TypeScript`; this should produce a link that looks like this:
```
[BasicImmutable & TypeScript](#basicimmutable--typescript)
```
However, it produces this:
```
[BasicImmutable & TypeScript](#basicimmutable-typescript)
```
These two are only off by one char, but the missing `-` in between the two words causes the link to fail. It seems like it is not accounting for symbols like `&` in between words, which markdown converts into dashes. There are a few other weird edge cases like this, but this is an easy one to point out off hand, and the only one I can 100% verify does not work correctly.

No error messages are produced.

Excellent extension by the way!! I just got finished writing a huge markdown file for a new package I published, and unfortunately did not find the extension until I was just about done, but will definitely be using it next time!!

**Comment by no-stack-dub-sack** [comment]
@neilsustc sure, that's interesting, I didn't realize markdown had different conventions across platforms, but I suppose that makes sense. I did notice that the link did work in vscode, however on Github (probably the most common use-case for these files), the above example holds true. The `&` symbol needs to be converted to a dash for github to correctly link to the `### Basic Immutable & TypeScript` header.

Thanks for looking in to this.

**Comment by neilsustc** [comment]
You can set `githubCompatible` to `true` when necessary 😉
