### ISSUE TITLE
Is there a way to disable keyboard shortcuts?

### ISSUE THREAD

**Issue by pzelnip** [neilsustc/vscode-markdown#159]
Many of the keyboard shortcuts on a Mac (ex: cmd+b, cmd+i) conflict with built-in VS Code shortcuts (for example: cmd+b is Toggle Side Bar Visibility, cmd+i is expandLineSelection).  While I find the menu options that are added to the command palette to be useful, I find the keyboard shortcuts get in my way.  Is there any way to disable just the keyboard shortcuts?

**Comment by neilsustc** [comment]
Yes, see [vscode doc](https://code.visualstudio.com/docs/getstarted/keybindings#_removing-a-specific-key-binding-rule).

**Comment by shilangyu** [comment]
Could you elaborate? What are the names of the commands? Like lets say i want to disable `toggle bold`, how would i do that?
