### ISSUE TITLE
Control + K V keyboard shortcut conflicts with Control + K for Clear Terminal

### ISSUE THREAD

**Issue by WalkerCodeRanger** [neilsustc/vscode-markdown#161]
The keybinding `ctrl+k v` added for `markdown.extension.togglePreviewToSide` conflicts with the default keybinding `ctrl+k` for `workbench.action.terminal.clear`. This causes the `ctrl+k` keypress to be sent to the terminal rather than clearing the terminal.

I'm running on windows, but I expect this will be the same on other platforms.

Steps to reproduce:
1. Open a Powershell Terminal
2. Press Control + K
3. Terminal displays `^K` instead of clearing.

If you disable this keybinding it will start working. To disable add the following to your keybindings.json:
```
{
	"key": "ctrl+k v",
	"command": "-markdown.extension.togglePreviewToSide"
}
```
I believe that many other bindings to `ctrl+k` place a condition like `editorFocus` or `editorTextFocus` on them to prevent this conflict. I think this binding needs one too. I'm not sure what the correct condition is.

**Comment by neilsustc** [comment]
Thanks. I'll check it

**Comment by WalkerCodeRanger** [comment]
I got the updated plugin with the fix. Thanks.

Sorry I wasn't able to test the plugin for you, It's been a busy week.

**Comment by neilsustc** [comment]
😉
