### ISSUE TITLE
Tables in math-mode don't render properly 

### ISSUE THREAD

**Issue by Splike** [neilsustc/vscode-markdown#163]
A table wrapped in a math block ($$ [TABLE] $$) doesn't display properly.

The preview will put everything on one long line.

Example table:

$$
| P     | Q     | \neg Q | \neg P | P \Rightarrow Q | \neg Q \Rightarrow \neg P |
| :---: | :---: | :----: | :----: | :-------------: | :-----------------------: |
| T     | T     | F      | F      | T               | T                         |
| T     | F     | T      | F      | F               | F                         |
| F     | T     | F      | T      | T               | T                         |
| F     | F     | T      | T      | T               | T                         |
$$

**Comment by Splike** [comment]
Hmm... Is there no way to mix the two, so they can work together?

As you probably have seen by my other two markdown/mathmode issues, I really want the two languages to go hand in hand and compliment each other.

**Comment by neilsustc** [comment]
I am afraid it is impossible. Different languages have different parsers.
Just like we have English grammar and Chinese grammar. But we don't have grammar for English-Chinese mixed language.
