### ISSUE TITLE
Unable to make math mode bold

### ISSUE THREAD

**Issue by Splike** [neilsustc/vscode-markdown#164]
Example: **If $n$ is even then $n^2$ is even**

Anything encapsulated by "$$" will not show as bold, which makes it look very weird.

**Comment by neilsustc** [comment]
That is because math mode is a different environment.

![image](https://user-images.githubusercontent.com/7588612/39609683-5aab16d2-4f7d-11e8-9f54-f83fc224db3a.png)

And note that bold style often has conventional meaning in math typing, such as vector rather than scalar.

**Comment by neilsustc** [comment]
> And note that bold style often has conventional meaning in math typing, such as vector rather than scalar.

My point is that the **bold**/*italic* styles have different meanings between normal text and math text.

![image](https://user-images.githubusercontent.com/7588612/39657786-d6aa3f5e-503d-11e8-8645-d50a0f3820b6.png)

Do you see the differences? `**bold**` only changes the font weight to emphasize the text. But `\mathbf{}` changes the whole font, and meaning. `\mathbf{x}` is not meant to emphasize `x`.

The same for *italic* style

![image](https://user-images.githubusercontent.com/7588612/39657932-8b46ab4a-503f-11e8-9c18-56eb02cfe367.png)

And you can try `$\mathbf{\mathit{x + y = z}}$` on your own. Doess the result look as you expect?
