### ISSUE TITLE
[Request] Shortcut for wrapping text in math mode

### ISSUE THREAD

**Issue by Splike** [neilsustc/vscode-markdown#165]
Just like "Ctrl+b" will wrap the selected text in "**", I think there should be a shortcut for wrapping selected text in "$".

**Comment by neilsustc** [comment]
There are many different "bold" styles in math mode (`\textbf{}`, `\mathbf{}`, etc.).
And there might be some small differences among them (in terms of meaning or style).
That is different from Markdown which is meant to write non-math text.

**Comment by Splike** [comment]
I think you misunderstand my request.

I'm not looking for a shortcut to bold the selected text, i'm looking for a shortcut to quickly put $-signs around my selected text.

**Comment by neilsustc** [comment]
I think snippet is what you need, which is to insert `$|$` instead of wrapping selected text.

Try to add this into your `keybindings.json` (`ctrl+shift+p`, `open keyboard shortcuts file`)

```json
{
    "key": "your key",
    "command": "editor.action.insertSnippet",
    "args": {
        "snippet": "$$0$"
    },
    "when": "editorTextFocus && editorLangId == markdown"
}
```

**Comment by neilsustc** [comment]
I will add it to the extension later
