### ISSUE TITLE
Add feature to automatically update numbered list numbers

### ISSUE THREAD

**Issue by garyking** [neilsustc/vscode-markdown#166]
When creating a numbered list, sometimes I need to add/remove items in the middle of the list.  It would be nice if this extension had a feature in the Command Palette to re-number numbered lists, when ran.

**Comment by neilsustc** [comment]
This is already implemented in the preview build 😉. See a GIF first

![list-renumbering](https://user-images.githubusercontent.com/7588612/39670507-ded8433c-5138-11e8-94db-7dd3006b565a.gif)

Download `v1.2.0-fix32` [here](https://github.com/neilsustc/vscode-markdown/releases/tag/beta)

It should be released yesterday, but I found that vscode has problem showing images in changelog...

**Comment by neilsustc** [comment]
v1.3.0 released
