### ISSUE TITLE
Ordered list not being re-numbered when adding an item to the middle of the list

### ISSUE THREAD

**Issue by garyking** [neilsustc/vscode-markdown#168]
If I add an item to the middle of an ordered list, then subsequent items should be re-numbered. It should at least happen after focus has left the list.

![markdown](https://user-images.githubusercontent.com/343940/39675323-75856eb6-5127-11e8-8d7f-45eb662efe0b.gif)

**Comment by neilsustc** [comment]
Thanks. [`v1.3.0-fix168`](https://github.com/neilsustc/vscode-markdown/releases)
