### ISSUE TITLE
New renumbering not working when changing indentation

### ISSUE THREAD

**Issue by michaelgwelch** [neilsustc/vscode-markdown#170]
The problem I'm having is that the new renumbering in 1.3.0 doesn't appear to work when indenting/outdenting.

![renumbering issue](https://user-images.githubusercontent.com/826112/39709853-9f8a596a-51e0-11e8-970b-7058501bb94e.gif)

Am I misunderstanding how this feature should work?

**Comment by neilsustc** [comment]
😂 let me have a look

**Comment by neilsustc** [comment]
Oh, I understand. You are indenting/outdenting with the vscode built-in commands.
The renumbering is triggered on <kbd>Tab</kbd>, <kbd>Backspace</kbd> and built-in moving line up/down commands.
Please observe the key strokes in the demo GIF 😉

**Comment by michaelgwelch** [comment]
I'm using Tab and Shift-Tab. Thanks for the instructions. Not sure I'll be able to train myself to use backspace instead of Shift-Tab. I'll give it a try.

I never even noticed that the GIF included keystrokes. I'm so busy looking at the demo. Thanks for the heads up.

**Comment by neilsustc** [comment]
You're welcome
