### ISSUE TITLE
Table formatter formating incorrect

### ISSUE THREAD

**Issue by Ash258** [neilsustc/vscode-markdown#171]
Consider table like this: 

    ```markdown
    | foo | bar |
    | --- | --- |
    ```

## Steps to reproduce

1. Create simple table like above
1. When you add longer text than header table formatter would move right collumn divider (Thats correct)
    ```markdown
    | foo           | bar |
    | ------------- | --- |
    | too long line |     |
    ```
1. But when you shrink that long line the right collumn stay same size.
1. If you remove some dashes it works as it should work.

![Gif](https://i.imgur.com/D98nQgU.gif "Gif")

This occured after latest update. No message in console.

**Comment by neilsustc** [comment]
Thanks for pointing out.

cc @StefanZi, I realize that the normalization of hyphen line shouldn't being removed...

**Comment by neilsustc** [comment]
Preview build `v1.3.0-fix171-175` is available [here](https://github.com/neilsustc/vscode-markdown/releases/)
