### ISSUE TITLE
Some unicode characters break the ToC links in HTML and PDF exports

### ISSUE THREAD

**Issue by FDerudderVL** [neilsustc/vscode-markdown#174]
Apologies, I was blaming the wrong extension, and realized after submitting the issue.
Feel free to close

for info, the issue I was wrongly reporting here is that one https://github.com/yzane/vscode-markdown-pdf/issues/69

**Comment by neilsustc** [comment]
Doesn't matter 😄

**Comment by arteika** [comment]
any update on the issue? It would be great to have the issue addressed...
