### ISSUE TITLE
Proposal: Omit specified custom headers from being added to the TOC

### ISSUE THREAD

**Issue by luav** [neilsustc/vscode-markdown#177]
All headers of the specified range (for example H2:H6) are added to the TOC. I have also H2 "Table Of Contents", which should be omitted from being included into the TOC. Also, it would be nice to omit some custom short subsections  (not all), which also belong to the specified range.

A special attribute in the comment can be used as a command to omit the required header from being added to the TOC like [specified here](https://github.com/AlanWalk/markdown-toc/issues/26).
```markdown
## Table of Contents   <!-- TOC omit:true --> 
```

By the way, the *comments are not recognized in the current version* (v.1.3.0), which yields the following TOC for this example:
```markdown
- [Contents  <!-- TOC omit:true -->](#contents----toc-omit-true)
```

**Comment by neilsustc** [comment]
Makes sense. I will look into it during the weekend. 

I prefer a short comment like `<!-- omit -->`.

---

> By the way, the comments are not recognized in the current version

Thanks for catching that

**Comment by luispabon** [comment]
This would be great, otherwise we have docs looking like this:

![image](https://user-images.githubusercontent.com/6388823/39868226-9329bd74-5450-11e8-9907-7b9352c0c8b9.png)

I would expect document headers (H1 equivalent) to be omitted from the TOC and the TOC's tree to start at H2.

**Comment by neilsustc** [comment]
@luispabon In this case, you can set `tocLevels` to `2..6` in the workspace setting then the H1 will be ignored.

**Comment by luispabon** [comment]
@neilsustc apologies, I didn't realise I could do this. It's exactly what I needed, thank you :+1:

**Comment by luav** [comment]
> I prefer a short comment like `<!-- omit -->`

It is convenient but you might would like to consider several aspects:
1. How would the user know that this comment relates to header omission from the TOC?  
Such comment might be occasionally removed by the user later, so it would be nice to include `TOC` as the *first term* to identify the relation, i.e. `<!-- TOC omit -->`
2. In case you would like to add any additional commands later, like explicit specification of the rendering headers via the comment or anything else (`<!-- TOC depthFrom:2 orderedList:true -->`) then it would require to desing a uniform format `attribute[:value]`. The format of the commands can unified from the start taking into account these possibilities and providing backward/forward compatibility.

**Comment by neilsustc** [comment]
Personally I don't like to introduce too many distracting things to Markdown writing (as said in the `README`).

![image](https://user-images.githubusercontent.com/7588612/39871105-640574fc-5496-11e8-8030-8073dde99a09.png)

So for point 2, I might be never willing to add this kind of features because they mess the document (unless there are many requests for them).

For point 1, I just don't like capitalized `TOC` characters. But I think I can make it in-casesensitive so I can choose to use `toc`.

What do you think about `<!-- omit in toc -->` or `<!-- toc omit -->`?
(And feel free to use `TOC` if you prefer)

**Comment by luav** [comment]
`<!-- omit in toc -->` is semantically perceivable.
Non-capitalized `<!-- toc omit -->` is not relly clear until some hints are made that this is a command or that we omit from the TOC but not the TOC: `<!-- toc: omit -->` (the *colon* sign makes it clear).

**Comment by neilsustc** [comment]
Thanks for the feedback. Will implement it later.

**Comment by neilsustc** [comment]
Please try [v1.3.0-fix177](https://github.com/neilsustc/vscode-markdown/releases/download/beta/markdown-all-in-one-1.3.0-fix48-fix177.vsix)

**Comment by luav** [comment]
Thanks,
` <!-- omit in toc -->` works fine!
