### ISSUE TITLE
公式中的下划线仍然被视为斜体格式的一部分

### ISSUE THREAD

**Issue by TheKiteRunning** [neilsustc/vscode-markdown#178]
**What is the problem?** 

公式中的下划线仍然被视为斜体格式的一部分参与编辑器的渲染，导致正常文本变为斜体，不过不影响使用
**How can I reproduce it?**

您输入一段文字$\dot{x}_i$比如说这样，当另一边公式也有$x_i$

奇怪的是$x_i$没有函数参与时，并没有出现问题$x_i$

![image](https://user-images.githubusercontent.com/24802332/39857781-2ae6da32-5467-11e8-9b19-a0337f71a8d5.png)

**Is there any error message in the console?**

没有

**Comment by neilsustc** [comment]
是的，不过这个语法高亮是官方的插件提供的，默认又不支持数学，暂时没有什么好办法

一个权宜之计是用 `<p>...</p>` 把这一行包住

**Comment by neilsustc** [comment]
不过我发现我这里倒是正常的。。。（不过印象里确实出现过你这种情况）

![image](https://user-images.githubusercontent.com/7588612/39862505-9e924390-5476-11e8-80d8-e6f92ff6ee5f.png)

我用的是预览版

**Comment by neilsustc** [comment]
https://code.visualstudio.com/insiders/

**Comment by dajuguan** [comment]
$z_i^{(2)} $

**Comment by HippogriffLh** [comment]
用\*\*...\*\*包裹文内公式，文内公式的显示效果不受加粗影响，而且限定了下划线的影响范围
