### ISSUE TITLE
Table of Contents does not work properly for Emoji, and non-BMP characters

### ISSUE THREAD

**Issue by liyuhang1997** [neilsustc/vscode-markdown#179]
# problem

TOC does not work properly for Emoji, and non-BMP characters.

similar problems 👉 #151 

## reproduce

create a md file ```test.md```

```markdown
# 测试

## 😀

## 🠖🠖🠖

## μ

```

### use ```Markdown All in One```

```>markdown: Create Table of Contents```

```markdown

- [测试](#)
  - [😀](#)
  - [🠖🠖🠖](#)
  - [μ](#)

```

### use another extension [```Markdown TOC```](https://marketplace.visualstudio.com/items?itemName=AlanWalk.markdown-toc)

```>Markdown TOC: Insert/Update```

```markdown
<!-- TOC -->

- [测试](#测试)
  - [😀](#😀)
  - [🠖🠖🠖](#🠖🠖🠖)
  - [μ](#μ)

<!-- /TOC -->

```

**Comment by neilsustc** [comment]
You can set `toc.githubCompatibility` to `true`. Then the result is below, (which is compatible with GitHub)

```
- [测试](#测试)
    - [😀](#)
    - [🠖🠖🠖](#)
    - [μ](#μ)
```

---

By default, this extension invokes the same `slugify` function used by vscode. However, it is not so good now (see [vscode#37079](https://github.com/Microsoft/vscode/issues/37079), [vscode#48482](https://github.com/Microsoft/vscode/issues/48482)).

**Comment by liyuhang1997** [comment]
OK, I just found it.
