### ISSUE TITLE
Underscore for italics

### ISSUE THREAD

**Issue by borekb** [neilsustc/vscode-markdown#18]
Would be good to have a user setting to use `_underscore for italics_`.

**Comment by neilsustc** [comment]
How do you think we deal with the bold text?
Sharing a setting or have another setting?

**Comment by borekb** [comment]
I actually thought that bold needs to always be `**`, I've never seen underscores used for that even though the CommonMark spec [seems to allow that](http://spec.commonmark.org/0.27/#emphasis-and-strong-emphasis). But I'd be happy with just a config variable for the italics character.

**Comment by neilsustc** [comment]
👌

**Comment by borekb** [comment]
Appreciate your responses, your extension makes the Markdown editing experience in VSCode much better!
