### ISSUE TITLE
Delay when deleting text with backspace

### ISSUE THREAD

**Issue by songxianpeng** [neilsustc/vscode-markdown#181]
I've just updated version 1.4.0, and when I use BACKSPACE to delete text, it's a delay, for example when you delete text on a list item

**Comment by neilsustc** [comment]
Reproduced on line 137. Thanks, I'll look into it.

**Comment by neilsustc** [comment]
I find it is a vscode issue. Would you mind me reporting this issue to vscode using your sample file?

**Comment by xpressSong** [comment]
I don't mind, thanks for the information provided.

**Comment by neilsustc** [comment]
Are you using vscode insider build? I can reproduce it with insider build `v1.24.0`, but `v1.23.1` works well.

**Comment by xpressSong** [comment]
I'm using version v1.23.1,and there is my vscode version info.
![image](https://user-images.githubusercontent.com/9303424/40878038-92efbc6c-66bd-11e8-8a9b-d680880b2075.png)

**Comment by xpressSong** [comment]
This issue looks much better with the new vscode version 1.24.0.

**Comment by neilsustc** [comment]
😂 I don't know why but am happy to hear that.

**Comment by lautumn1990** [comment]
文件大的话, 使用backspace删除内容特别卡

**Comment by neilsustc** [comment]
Should be fixed in v2.0.0

**Comment by rshawocf** [comment]
Note, this is an old issue but I found it through a google search when I encountered the same problem. Closing and reopening VS Code fixed it for me.
