### ISSUE TITLE
Uncatched table formatting case

### ISSUE THREAD

**Issue by Ash258** [neilsustc/vscode-markdown#186]
```markdown
| Foo  | Bar  |
| --- | --- |
| Alfa | cosi |
```

1. Create easy table (example above):
1. If you format, it works.
1. Add space after last hyphen collumn (space or space and other text) and press format shortcut.
1. Get undefined before text and console error.

![Undef](https://i.imgur.com/i2gwvkW.gif)

Offtopic: 
Also i noticed there is some exception when you delete hyphen

![Hyphen delete](https://i.imgur.com/XZrcSiP.gif)

> vscode: 1.24-insiders
> yzhang.markdown-all-in-one: 1.4.0

**Comment by neilsustc** [comment]
Thanks. You can get the latest build [here](https://ci.appveyor.com/project/neilsustc/vscode-markdown/build/artifacts).
