### ISSUE TITLE
Latin issue

### ISSUE THREAD

**Issue by Rabbit1623** [neilsustc/vscode-markdown#187]
I have some issues in typing LaTex in VSCode. 
On the another MD software I used, the math block or inline math with Latin like uppercase epsilon will type like this: \Epsilon. But on the all-in-one, it doesn't work. it just shown as $\Epsilon$ not the right letter. 

same issue happened in following letters with their uppercase:
α \alpha 
β \beta 
ε \epsilon 
ζ \zeta 
η \eta 
ι \iota 
κ \kappa 
μ \mu 
ν \nu 
ρ \rho 
τ \tau
χ \chi 

I searched it but don't know how to solve it. please help.

just type $\Epsilon$, and it will shown as \Epsilon.

**Comment by neilsustc** [comment]
[These](https://khan.github.io/KaTeX/function-support.html#letters) are the supported letters.

And as I know, `\Epsilon` is also not a valid LaTeX command.
