### ISSUE TITLE
Suggestion: show preview of actual image with autocompletion

### ISSUE THREAD

**Issue by sahil48** [neilsustc/vscode-markdown#188]
The autocompletion of file paths recently added is a very nice feature. I don't know if this is possible, but would be even really great if you could see of thumbnail of the images of the currently selected image in the autocompletion results using the up and down arrow keys.

**Comment by neilsustc** [comment]
Sounds good. I'll investigate it later.

**Comment by neilsustc** [comment]
Please give the latest CI build a try 😉 (find the download link at the end of `README`).

**Comment by neilsustc** [comment]
Shipped with v1.5.0
