### ISSUE TITLE
Can code block overflow in preview?

### ISSUE THREAD

**Issue by PaleNeutron** [neilsustc/vscode-markdown#189]
![Imgur](https://i.imgur.com/xjkeRyw.png)
Long line code in code block auto wrap and break the syntax.

Just write a long line to reproduce it.

**Comment by neilsustc** [comment]
This extension does nothing about code syntax highlight. You might need to report it to the vscode repository.

**Comment by PaleNeutron** [comment]
@neilsustc, The left one is vscode edit page, and the right one is preview page.

Do you mean preview code block style is done by vscode ?

**Comment by neilsustc** [comment]
> Do you mean preview code block style is done by vscode?

Yes, vscode has built-in Markdown support. You can find more information [here](https://code.visualstudio.com/docs/languages/markdown).

**Comment by PaleNeutron** [comment]
Thanks for answering, and I have issued this problem in the official vscode repo.

This issue could be closed.
