### ISSUE TITLE
Wrap word in bold or italics if no selection

### ISSUE THREAD

**Issue by borekb** [neilsustc/vscode-markdown#19]
`w|ord` -> press Ctrl+B -> `**w|ord**`

**Comment by neilsustc** [comment]
Let's considering the corner cases. What do you expect in these situations. 🤔

`some| words`
`some |words`

**Comment by borekb** [comment]
Tried in [Caret](https://caret.io/), my favorite MD editor that does many things well, and this is the result:

```
**some** words
some **words**
```

**Comment by neilsustc** [comment]
👌

**Comment by neilsustc** [comment]
One small question. Where is the cursor after ctrl+b?

**Comment by borekb** [comment]
It's here:

```txt
**some**| words
some |**words**
```

**Comment by neilsustc** [comment]
I will introduce a new setting `quickStyling` for these behaviors.

For the reason, it conflicts with our original logic. You can see some discussion [here](https://github.com/neilsustc/vscode-markdown/pull/1). What do you think of it?

**Comment by borekb** [comment]
I'd generally follow what other MD editors do. I think that most often, Ctrl+B and Ctrl+I just toggles. I personally do not need anything fancier.

**Comment by neilsustc** [comment]
Actually, I have implemented it for a period of time.
But I would like to add unit tests before releasing this feature.
And then I am blocked 😓.

**Comment by borekb** [comment]
Looking forward to it :)
