### ISSUE TITLE
Creating table of contents fails

### ISSUE THREAD

**Issue by TheOneSock** [neilsustc/vscode-markdown#191]
Creating table of contents fails with ```Cannot read property 'fromHeading' of undefined```

![bug](https://user-images.githubusercontent.com/18218893/40740142-533f1ada-6448-11e8-8500-76e3df0a4c2f.png)

This used to work for me. I noticed it didn't work today. I know I used it about 5 days ago.

**To reproduce it i can:**

create new markdown: 

```md
# TITLE
## SUBTITLE
```

try to create table of contents

**console message:**

![bug2](https://user-images.githubusercontent.com/18218893/40740216-81fa4a0c-6448-11e8-902f-da1854b976bf.png)

**Edit:**
some more info:
```
  ERR Cannot read property 'fromHeading' of undefined: TypeError: Cannot read property 'fromHeading' of undefined
	at Object.slugify (C:\Users\JanezP\.vscode-insiders\extensions\yzhang.markdown-all-in-one-1.4.0\out\src\util.js:47:30)
	at tocEntries.forEach.entry (C:\Users\JanezP\.vscode-insiders\extensions\yzhang.markdown-all-in-one-1.4.0\out\src\toc.js:76:81)
	at Array.forEach (native)
	at C:\Users\JanezP\.vscode-insiders\extensions\yzhang.markdown-all-in-one-1.4.0\out\src\toc.js:69:20
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\JanezP\.vscode-insiders\extensions\yzhang.markdown-all-in-one-1.4.0\out\src\toc.js:4:58)
	at <anonymous>
```

**Comment by neilsustc** [comment]
The internal interface was changed in the latest insider build. I'll fix it later.

**Comment by EricZQWon** [comment]
This question is at package.json ;lines :175
change default from false to true. Thanks @TheOneSock

**Comment by neilsustc** [comment]
Already fixed in the latest CI build

**Comment by dskeithbuck** [comment]
Just ran into this.

**Comment by proddy** [comment]
me too, thanks for the work around

**Comment by rlawre** [comment]
Ran in to this today. Code version 1.24.1 (windows)
Changed "markdown.extension.toc.githubCompatibility" from false to true
C:\Users\<myuser>\.vscode\extensions\yzhang.markdown-all-in-one-1.4.0\package.json
Thanks @TheOneSock @EricZQWon 

This workaround also fixed problems when invoking command Markdown: Print current document to Html

**Comment by neilsustc** [comment]
(In fact, you just need to set `githubCompatiblity` to `true` in your *user settings*. The `package.json` controls the default settings which will be overridden by user settings.)

**Comment by melMass** [comment]
@neilsustc But the defaults errors out as stated in the current issue, why not change the defaults to avoid it ?

Thanks a lot for this extension.

**Comment by neilsustc** [comment]
As is shown in the name `githubCompatibility`, this setting is meant to be compatible with GitHub Markdown link (which is slightly different with that of vscode).

I should have release an update to keep up with the vscode API change. But I didn't get enough time to get it done. We have some new features in the next version 😉

**Comment by neilsustc** [comment]
Should be fixed with v1.5.0

**Comment by schlichtanders** [comment]
this again fails in v1.7.0

**Comment by schlichtanders** [comment]
created new issue https://github.com/neilsustc/vscode-markdown/issues/311
