### ISSUE TITLE
Toggle checkboxes via preview

### ISSUE THREAD

**Issue by Splike** [neilsustc/vscode-markdown#193]
When I've made my task list, I like to only have the preview open. Would it be possible to implement the ability to click checkboxes in the preview, so the code is updated as well? The source file should save itself upon checking/unchecking via the preview.

**Comment by neilsustc** [comment]
It seems not feasible. Maybe you need a more powerful Markdown editor like Typora or Caret.

**Comment by nesl247** [comment]
I came to look for this. What is the limitation? I've seen this work in PhpStorm for example.

**Comment by neilsustc** [comment]
It is somehow possible but complicated to implement because of vscode extension APIs.

**Comment by nesl247** [comment]
Is there an open issue on VSCode for what would make it easier to implement?

**Comment by neilsustc** [comment]
I'm afraid no 😳

Markdown is rendered to HTML and then previewed in a new tab (done by vscode)

What we can contribute now is
- providing some Mardown engine ([`markdown-it`](https://github.com/markdown-it/markdown-it
)) plugins e.g. `markdown-it-task-lists`
- providing some stylesheets or scripts

To implement this feature, we need to
- add eventListener to each checkbox, which means we probably need to write a `markdown-it` plugin to change the output HTML
- communicate with vscode to change the Markdown source code, which I am not sure how to do. Although I know some extensions can do it.

**Comment by ogierm** [comment]
Has the situation changed, 2 years later? I'd love to work through a ToDo-list that way.

**Comment by yzhang-gh** [comment]
Not feasible as a plugin. But you may be interested in https://github.com/microsoft/vscode/issues/84520.

**Comment by Bludator** [comment]
Any updates?

**Comment by benjaminapetersen** [comment]
Man, so surprised VS Code doesn't have APIs to allow this feature, it would be so valuable!
