### ISSUE TITLE
Math rendering not working

### ISSUE THREAD

**Issue by barrysteyn** [neilsustc/vscode-markdown#195]
Math rendering in preview is not working. I am using VSCode version `1.23.1` on Ubuntu OS. When I type math, the following happens (see screenshot):
![screenshot from 2018-06-01 07-56-57](https://user-images.githubusercontent.com/1537348/40847573-a0a5a1c0-6571-11e8-867a-80b00db3c3a2.png)
Looking at dev console, I do see that I have an error with `workbench.main.js:sourcemap:2586 Webview: Cannot load resource outside of protocol root`

Help would be great.

**Comment by neilsustc** [comment]
Can you print the Markdown file to HTML and open it with the browser to see whether math is rendered.

**Comment by barrysteyn** [comment]
@neilsustc Sorry for taking so long. How exactly do I export the markdown to HTML?

**Comment by neilsustc** [comment]
We have a new CI build with the latest katex package. You can give it a try (find the download link at the end of `README`)
