### ISSUE TITLE
Math randering

### ISSUE THREAD

**Issue by caiyajing9210** [neilsustc/vscode-markdown#196]
Cannot align equations

when I typed: 
```
$$
\begin{align}
\sqrt{37} & = \sqrt{\frac{73^2-1}{12^2}} \\
 &= \sqrt{\frac{73^2}{12^2}\cdot\frac{73^2-1}{73^2}} \\ 
 &= \sqrt{\frac{73^2}{12^2}}\sqrt{\frac{73^2-1}{73^2}} \\
 &= \frac{73}{12}\sqrt{1 - \frac{1}{73^2}} \\ 
 & \approx \frac{73}{12}\left(1 - \frac{1}{2\cdot73^2}\right)
\end{align}
$$

```

**Comment by neilsustc** [comment]
You can find all supported functions [here](https://khan.github.io/KaTeX/function-support.html#environments).

For your case, you need to use `aligned`.

**Comment by caiyajing9210** [comment]
also about \tag{1}

**Comment by neilsustc** [comment]
`tag` seems to be a new feature. I will update the KaTeX version.

**Comment by caiyajing9210** [comment]
Sure
Thx

**Comment by neilsustc** [comment]
Updated. Please install the latest CI build. (the download link can be found at the end of `README`)

**Comment by neilsustc** [comment]
Shipped with v1.5.0

**Comment by kenng** [comment]
Thank for the nice extension. Very useful! 
Just to check if it supports any katex symbol for

N   - Natural Number ($\N$)
Z   - Integer Number ($\Z$)
R   - Real Number ($\R$)

as currently it will show as `\N, \R, \Z`

**Comment by kenng** [comment]
😄
just found a shortcut to workaround for it 
`$\mathbb{N}$` will give the right symbol for Natural Number, and etc
