### ISSUE TITLE
Add indentation setting for TOC

### ISSUE THREAD

**Issue by DOliana** [neilsustc/vscode-markdown#198]
When using the toc, the items are created using an indentation of 4 spaces. If an extension like markdownlint is installed, it expects indentations to be 2 spaces ([see according rule](https://github.com/DavidAnson/markdownlint/blob/v0.10.0/doc/Rules.md#md007)) It would be nice to be able to configure the indentation used by the extension.

**Comment by neilsustc** [comment]
This extension will detect your tab size in the current file and use it for indentation.
(check your tab size at the right bottom corner in vscode)

You can find more information in #77, #155.

**Comment by DOliana** [comment]
Allright. It seems that VSCode did not detect it correctly (I was using 2 spaces, but I have the general setting set to 2 ```"editor.tabSize": 2,```). After clicking here and there in VSCode it took it - even though I am not sure why it is working now...

Maybe you should mention this behaviour (detection of indentation) where you explain how to create the toc.

**Comment by maelvalais** [comment]
Thing is, in markdown we have two different tabSizes:
- for lists, [MD007/ul-indent](https://github.com/DavidAnson/markdownlint/blob/v0.11.0/doc/Rules.md#md007) dictates that we should use 2 spaces,
- on the other side, pre-formatted code blocks use 4 spaces

This is why we should have a specific parameter for the TOC, e.g., 
```json
{
    "markdown.extension.toc.tabSize": 2
}
```
