### ISSUE TITLE
Code formatter not respecting prettier.eslintIntegration

### ISSUE THREAD

**Issue by awmottaz** [neilsustc/vscode-markdown#199]
I have a markdown file in a project that uses ESLint. By setting `pretter.eslintIntegration` to `true` in my settings, JS files will be formatted according to my ESLint rules. I want JavaScript code blocks in Markdown files to be formatted in the same way.

Set up a project with an `.eslintrc` file with rules that disagree with the default formatter (such as disabling semi-colons). Install the ESLint and Prettier extensions and configure `prettier.eslintIntegration: true` in settings. JavaScript files will be formatted according to your `.eslintrc` rules, but JavaScript code blocks in Markdown files will not.

No.

**Comment by neilsustc** [comment]
It is out of the scope of this extension which is aimed to help Markdown editing. The code block is indeed a valid Markdown syntax, but Markdown doesn't care about the content inside a code block. You can write anything in it, Javascript, Java, Python... And each language may have various different formatters.

The Prettier extension is a more appropriate project for this feature request.

**Comment by awmottaz** [comment]
Okay, thanks
