### ISSUE TITLE
Range of levels for ToC

### ISSUE THREAD

**Issue by borekb** [neilsustc/vscode-markdown#21]
I usually want to skip H1 heading from table of contents and only care about levels 2..x. For example, I'd appreciate being able to set this:

```
"markdown.extension.toc.levels": "2..6"
```

This would probably replace the current `markdown.extension.toc.depth` setting.

**Comment by neilsustc** [comment]
Please check out v0.8.0 which has these new features

- toc range (this issue)
- quick styling (wrap words without selection #19)
- underscore for italic text (#18).

**Comment by borekb** [comment]
Very nice! For other people trying this, I had to add these user settings (most of the above is turned off by default):

```
"markdown.extension.toc.levels": "2..6",
"markdown.extension.italic.indicator": "_",
"markdown.extension.quickStyling": true
```

**Comment by neilsustc** [comment]
😉
