### ISSUE TITLE
TOC does not acknowledge duplicate headers

### ISSUE THREAD

**Issue by Purpzie** [neilsustc/vscode-markdown#211]
The Table of Contents currently does not acknowledge handling multiple headers that have the same name.

1. Set up a markdown file with a TOC
1. Add duplicate headers
1. Update the TOC and see how the anchor links are the same.

GitHub, at least, handles this by putting a number after the anchor name. Let's say you had something like this:

## woah a header

The first one would be linked to `#woah-a-header`, and the second one would be linked to `#woah-a-header-1`. However, the current TOC generation just prints the same thing without any numbers, leading to the first header each time.

I'm making a changelog file in markdown that has sections for each version, and each one may also have headers of its own that could have duplicates with other version descriptions. That's how I ran into the problem.

**Comment by neilsustc** [comment]
You are right. BTW, vscode also doesn't deal with this issue (I mean the built-in Markdown preview). Microsoft/vscode#47537

Maybe I need to deal with it if user sets `githubCompatibility` to `true`.

**Comment by neilsustc** [comment]
Should be fixed in v1.5.0
