### ISSUE TITLE
command 'markdown.extension.xxx' not found

### ISSUE THREAD

**Issue by quanzaiyu** [neilsustc/vscode-markdown#215]
#### What is the problem?

command 'markdown.extension.xxx' not found

#### How can I reproduce it?

vscode v1.23.1
markdown All in One v1.5.0

#### Is there any error message in the console?

`Ctrl+B`: `command 'markdown.extension.editing.toggleBold' not found`

`Backspace`: `command 'markdown.extension.onBackspaceKey' not found`

`Enter`: `command 'markdown.extension.onEnterKey' not found`
......

**Comment by neilsustc** [comment]
Please see #214.

**Comment by quanzaiyu** [comment]
When typing `Ctrl+B`，console doesn't  output anything

![](http://oss.xiaoyulive.top/%E6%88%AA%E5%9B%BE/QQ%E6%88%AA%E5%9B%BE20180625193828.png)

This is version of VSCode

![](http://oss.xiaoyulive.top/%E6%88%AA%E5%9B%BE/QQ%E6%88%AA%E5%9B%BE20180625195015.png)

**Comment by neilsustc** [comment]
I cannot find an old version of vscode (v1.23.1) to test. You might need to update your vscode to v1.24.0.

**Comment by quanzaiyu** [comment]
It works after upgrading to v1.24.1，thanks!

**Comment by pxlpnk** [comment]
@neilsustc I had the same problem with v1.22.x
In case you need older versions you can get them through the release announcements:
https://code.visualstudio.com/updates/v1_23

Just update the version and you should be to retrieve an older version.

Thank you for building this very helpful extension! 👏

**Comment by neilsustc** [comment]
@pxlpnk Really useful information, thank you.
