### ISSUE TITLE
数学代码会出现斜体

### ISSUE THREAD

**Issue by linsui** [neilsustc/vscode-markdown#218]
#### What is the problem?
$$
{def}_abc_{def}
$$
在以上代码中abc会显示为斜体，但对预览没有影响

**Comment by neilsustc** [comment]
确实是这样，因为 Markdown 和 LaTaX 的语法冲突

但是暂时没有什么好办法

**Comment by linsui** [comment]
谢谢你解开我长期的疑惑。在$$之间无法屏蔽markdown的语法吗？只是好奇

**Comment by neilsustc** [comment]
VSCode 的语法是用正则表达式匹配的，理论上来说是可以「实现」一个支持 LaTeX 语法的高亮规则，但是因为那并不在 Markdown 语法规范里，没人会花力气去做😂
