### ISSUE TITLE
lack of some codeinsight for math 

### ISSUE THREAD

**Issue by linsui** [neilsustc/vscode-markdown#219]
#### What is the problem?
lack of some code insight for math such as `\bigcup`
缺少部分数学代码提示比如 `\bigcup`。不过突然发现可以使用代码提示真是个惊喜。这个扩展比我之前用的不知高到哪里去。

**Comment by neilsustc** [comment]
🤣

已经加上了，你可以去下载安装最新版，`README` 最后有链接 (CI build)

**Comment by linsui** [comment]
哇，谢谢，更新神速。请问代码提示的数量有限制吗？我发现支持的只是katex中的一小部分。

**Comment by neilsustc** [comment]
我凭感觉加了一些常用的进去，具体是这里

https://github.com/neilsustc/vscode-markdown/blob/ca06ee2a9f94b3333c3423f3f05628a8d1a5f504/src/completion.ts#L13-L26

你有什么常用的可以告诉我一下

**Comment by linsui** [comment]
如果可以支持所有katex函数就最好啦。

[我整理了一些](https://github.com/linsui/home/blob/master/Function%20Support%20in%20KaTeX.txt)

**Comment by neilsustc** [comment]
有点疯狂，已加 👌

**Comment by linsui** [comment]
谢谢，太棒了
