### ISSUE TITLE
export html font-weight

### ISSUE THREAD

**Issue by image72** [neilsustc/vscode-markdown#220]
markdown-all-in-one 
导出html h1,h2,h3 出于什么样的原因 style font-weight: normal ?

**Comment by neilsustc** [comment]
This is inherited from vscode preview stylesheets. You can find that the exported HTML looks almost the same as it looks in the vscode preview.

And you can apply your own styles by setting `markdown.styles` to the paths to your stylesheets.

**Comment by image72** [comment]
thanks :-)
