### ISSUE TITLE
Feature request： customize the start and end symbols of math code corresponding to CTRL +m

### ISSUE THREAD

**Issue by linsui** [neilsustc/vscode-markdown#221]
#### What is the problem?
希望可以自定义`ctrl+m`对应的数学代码的起始符号和结束符号。主要是出于代码风格的原因。比如我习惯在公式外侧添加空格。

**Comment by neilsustc** [comment]
可以试试[自定义 snippet](https://code.visualstudio.com/docs/editor/userdefinedsnippets)，然后加上快捷键（链接里有介绍）

单独加一个设置的话感觉别人也用不上😂

**Comment by linsui** [comment]
😂原来有这种方法，非常感谢
