### ISSUE TITLE
raw ASCII char ^H inserted into document when backspace typed.

### ISSUE THREAD

**Issue by saturnman** [neilsustc/vscode-markdown#222]
#### What is the problem?
When editing doc, when I typed backspace under some condition, a raw ASCII char ^H was inserted into document and make docs goes wrong, a bit weird. I don't know how to write a vscode extension, but I've checked your code and the problem should be in the point where you modify editor content when backspace was pressed. Current may be temporarily ASCII char ^H, and you calculate RANGE and insert that into original document, then document now in wrong state.

#### How can I reproduce it?
here is the problematic file, please check it.
https://github.com/saturnman/deploy_easycloudapp/blob/master/deploy_sftp.md

**Comment by neilsustc** [comment]
I cannot produce. You may have other extensions resulting this. Could you please disable all other extensions except for this one and test again?

![image](https://user-images.githubusercontent.com/7588612/42161341-33ba78d6-7e2d-11e8-9eb1-56a53b4d0db5.png)

**Comment by saturnman** [comment]
THX for your quick response, I've tried your method. I have found this may be the problem of vscode with my input method, even when I  try to edit raw txt file in vscode, this problem also exists.  I will do more exploration and thx for your excellent editor extension.

**Comment by neilsustc** [comment]
You are welcome 😉
