### ISSUE TITLE
show codeinsight when input ( after $$

### ISSUE THREAD

**Issue by linsui** [neilsustc/vscode-markdown#223]
#### What is the problem?
在`$$`之后输入`(`时会弹出代码提示。包括所有katex函数。
另有个问题，请问代码提示能否设置为大小写敏感？比如现在输入`\gamma`时，第一个提示为`\Gamma`

**Comment by neilsustc** [comment]
已修复

代码提示是大写敏感的，因为一般大写肯定是刻意的，但是现在小写不敏感
我尝试了几个代码提示，发现 `gamma`, `delta`, `theta` 等是大写在前，但是 `lambda`, `phi`, `omega` 等又是小写在前
我猜测这是 vscode 排序的问题，大小写不稳定；vscode 自带的 sort lines 同样有这个问题

**Comment by linsui** [comment]
谢谢，修复神速:+1:

**Comment by linsui** [comment]
发现了另一个代码提示的问题:joy:，输入`\\`会弹出代码提示。

**Comment by linsui** [comment]
发现`\limits`的代码提示出现了两个相同的:joy:

**Comment by neilsustc** [comment]
你真是找 bug 小能手啊

**Comment by linsui** [comment]
:joy:，谢谢抽出时间修复
