### ISSUE TITLE
Outline view no longer appears in explorer bar

### ISSUE THREAD

**Issue by abastardi** [neilsustc/vscode-markdown#227]
#### What is the problem?

Using VS Code 1.24.1 on Windows 10 and Markdown All in One 1.5.1, the outline view no longer appears in the explorer bar.

#### How can I reproduce it?

Open a Mardown file and show the explorer bar -- no Outline section appears.

#### Is there any error message in the console?

There is no error message.

**Comment by neilsustc** [comment]
That is because vscode has implemented its own outline (see [here](https://code.visualstudio.com/updates/v1_24#_outline-view)).

I have made the outline (implemented by this extension) disabled by default with the latest version. And I will remove this feature several versions later.

**Comment by abastardi** [comment]
I was wondering about that. Hopefully the built-in outline view will improve for Markdown -- currently it simply lists all the heading lines (including the "#" characters), with no ability to expand or collapse levels. Not nearly as useful or visually pleasing as the vscode-markdown outline view.

**Comment by neilsustc** [comment]
It is still under developing and will become better in the coming June release.

And you can still enable this extension's outline by setting `showExplorer` to `true` (I won't remove it until the built-in outline is good enough)
