### ISSUE TITLE
加粗语法在左侧有字符时不高亮

### ISSUE THREAD

**Issue by linsui** [neilsustc/vscode-markdown#229]
#### What is the problem?
在 `一**二三四五**`这种情况下没有高亮，在`一，**二三四五**`的情况下可以高亮。

**Comment by neilsustc** [comment]
语法高亮是 vscode 自己提供的，具体来说是[这里](https://github.com/Microsoft/vscode-markdown-tm-grammar)，但是应该怎么改我就不知道了
