### ISSUE TITLE
Autoformatter?

### ISSUE THREAD

**Issue by jcrben** [neilsustc/vscode-markdown#232]
#### What is the problem?
Does this turn on some sort of autoformatter? And if so, how can I disable it? Not seeing an option at https://github.com/neilsustc/vscode-markdown#supported-settings

I cloned down https://github.com/StackExchange/blackbox/ to make a small PR to the README.md but when I hit save, it autoformatted the file.

When I disabled this extension, it didn't happen.

I also have prettier installed, but when I disabled that it still happened. Also, I have this in my user settings (among other things):
```
"[markdown]": {
  // per https://github.com/prettier/prettier-vscode/issues/275
        "editor.formatOnSave": false,
        "editor.wordWrap": "bounded",
        "editor.wordWrapColumn": 100,
    },
```
#### How can I reproduce it?
Install this extension, clone down above repo, try to edit README.md

**Comment by neilsustc** [comment]
What do you mean about "autoformatting" (the toc, or GFM table)?

There is an option `markdown.extension.toc.updateOnSave` defaults to `true`, which controls whether to update toc on file save.

**Comment by jcrben** [comment]
Looks like that's it. Thanks!
