### ISSUE TITLE
markdown export support DataURI

### ISSUE THREAD

**Issue by image72** [neilsustc/vscode-markdown#233]
markdown inline DataURI image ,use `Print current document to HTML` 
export incorrect url `"file:///Users/username/Desktop/data%3Aimage/png%3Bbase64%2C......`
![image](https://user-images.githubusercontent.com/243154/42504344-09d67c76-846e-11e8-8a5c-885e4f71eca3.png)

**Comment by neilsustc** [comment]
I don't understand. What is an inline DataURI image? How can I reproduce it (code snippet)? What results do you expect?

**Comment by image72** [comment]
https://gist.github.com/image72/28bfe94a2e42cf90e67ebf0fc5fab74a
vscode preview
![image](https://user-images.githubusercontent.com/243154/42553439-7bee5b76-8513-11e8-9fff-2f37c913ade5.png)

**Comment by neilsustc** [comment]
You need to set `markdown.extension.print.absoluteImgPath` to `false`.

And you don't need to include the image base64 content in your document. Please try `markdown.extension.print.imgToBase64` option.

**Comment by image72** [comment]
thanks a lot. :-)
