### ISSUE TITLE
Disable TOC detection

### ISSUE THREAD

**Issue by garyking** [neilsustc/vscode-markdown#234]
#### What is the problem?

This ext keeps trying to replace my code. Please allow us a way to disable TOC detection, rather than disabling `updateOnSave`, which still shows the TOC tooltip; or changing the `unorderedList.marker` to another setting, which still enables TOC for the set value. Please allow us to set `unorderedList.marker` to `""` for instance, so that would disable it.

#### How can I reproduce it?

Create a file with this:

```markdown
# Test

- [test](http://example.com/)
```

Save it. It will be replaced with:

```markdown
# Test

- [Test](#test)
```

This problem only started appearing about a week or two ago.

#### Is there any error message in the console?

No

**Comment by neilsustc** [comment]
You can set `markdown.extension.toc.updateOnSave` to `false`. The detection is not configurable currently.

**Comment by garyking** [comment]
Yes, I already tried that, but doing so still leaves the `Table of contents` tooltip hovering over my bulleted list.

**Comment by neilsustc** [comment]
I think it will disappear as you write more text to your document (more headings or more bulleted list items). It is rare to have a bulleted list which is identical to the TOC.

![image](https://user-images.githubusercontent.com/7588612/42729813-c6c12682-8816-11e8-91ea-44566e86321e.png)

![image](https://user-images.githubusercontent.com/7588612/42729811-b51adb12-8816-11e8-9a6d-32f255f15694.png)

![image](https://user-images.githubusercontent.com/7588612/42729819-f1b28fde-8816-11e8-886f-90a9ebf3b7d3.png)

**Comment by garyking** [comment]
Okay thanks. It must've been an edge case I was experiencing.
