### ISSUE TITLE
snippets only supports prefix begin with '\'

### ISSUE THREAD

**Issue by linsui** [neilsustc/vscode-markdown#235]
#### What is the problem?
关于用户代码片段，我在markdown.json添加了如下几个：
```
	"_": {
		"prefix": "_",
		"body": "_{$1}$0"
	},
	"left{": {
		"prefix": "\\left{",
		"body": "\\left\\{$1\\right\\\\}$0"	
	},

```
我发现似乎只有`\`开头的可以输入前缀时自动出现，其他的需要使用插入片段命令。而禁用此扩展后用户代码片段都无法自动出现。
如果可以的话，希望添加上下标和`\\left\\{$1\\right\\\\}$0`等这几个代码提示。
我没有找到自动显示用户代码片段的设置，如果没有的话，请问是否可以通过扩展实现这个功能？把markdown.json中的代码片段加入代码提示？谢谢:joy:
顺便问一下，是否考虑支持中文语言包？

**Comment by linsui** [comment]
咦。。我不清楚是什么原因，我禁用了其他所有扩展，但仍然会出现这个问题。当我禁用所有扩展后，用户代码片段提示只有在按下快捷键使用插入片段命令才会出现，但当我启用这个扩展后，在markdown文件内无论是否时数学模式，输入`\`时都会自动出现代码提示，而其他用户代码片段仍然不会自动出现。:sweat_smile:  也就是说，我添加的用户代码片段原本不能自动出现（似乎不是正常情况？我没有看到相关说明），但使用此扩展可以使`\`开头的用户代码片段自动出现。我在txt文件里也测试了一下，`_`开头的可以自动出现，而`\`开头的则必须在输入一个字符才会出现提示，但有一些代码片段仍然无法显示。我不知道是不是我有什么设置有问题？似乎和这个扩展有关系但好像不是扩展的问题。
这是txt的效果
<img width="560" alt="default" src="https://user-images.githubusercontent.com/36977733/42765077-c72d30fa-8949-11e8-98af-f165155316cc.PNG">

<img width="257" alt="default" src="https://user-images.githubusercontent.com/36977733/42765306-51f8c424-894a-11e8-8a1c-c62332ea51e8.PNG">

这是markdown的效果
<img width="582" alt="default" src="https://user-images.githubusercontent.com/36977733/42765174-fe1627a2-8949-11e8-9549-28b6f4612198.PNG">
<img width="337" alt="default" src="https://user-images.githubusercontent.com/36977733/42765212-13c2d14a-894a-11e8-8c4d-82007a647944.PNG">

***

中文语言包我也不清楚怎么添加，我看到[code-settings-sync](https://github.com/shanalikhan/code-settings-sync)添加了中文语言包的支持，把设置的注释和命令标题翻译成了中文。看起来是把需要翻译的内容单独放在一个配置文件里吧:joy:。

**Comment by neilsustc** [comment]
我想起来一个设置，`"editor.quickSuggestions": true`，默认是 `false`

![image](https://user-images.githubusercontent.com/7588612/42779047-c44ec11e-8971-11e8-9555-620a89c6a427.png)

---

显示语言的话官方有[例子](https://github.com/Microsoft/vscode-extension-samples/tree/master/i18n-sample)，看有没有人愿意帮我吧 😏

**Comment by linsui** [comment]
谢谢，确实是这个设置的作用。隐藏的太深了。:joy:
***
看起来似乎不难，我来尝试一下😏

**Comment by linsui** [comment]
我尝试了一下，似乎没有问题，不过有些消息我不知道怎么测试。我该怎样提交给你？:joy:

**Comment by neilsustc** [comment]
你先 clone 我这个仓库，在你自己的仓库上修改之后同步到 GitHub 上，网页上有提交 pull request 的按钮，然后按那个操作就好

![image](https://user-images.githubusercontent.com/7588612/43035473-2716c1e8-8d23-11e8-9b62-5c74b2446c9d.png)
