### ISSUE TITLE
This extended‘s preview function does not support the title that start with #. Can you add this feature?

### ISSUE THREAD

**Issue by SingleOne** [neilsustc/vscode-markdown#239]
#### What is the problem?
This extended‘s preview function does not support the title that start with #. 

#### How can I reproduce it?
preiview a md file which has a title start  with #

**Comment by neilsustc** [comment]
I don't understand. What's wrong with the current one?

![image](https://user-images.githubusercontent.com/7588612/43035120-6f840f3c-8d1c-11e8-8743-3210a089fef0.png)
