### ISSUE TITLE
Formatting - Wrong formatting when Table contains `I`

### ISSUE THREAD

**Issue by xa0082249956** [neilsustc/vscode-markdown#24]
新建一个 Markdown 文件，输入这些内容：
Create a Markdown file and type this:
```markdown
| 233 | 666 |
| --- | --- |
| `|` | 233 |
```

按下 `Alt` + `Shift` + `F`:
Press `Alt` + `Shift` + `F`:
```markdown
| 233 | 666 |
| --- | --- |
| `   | `   | 233 |
```

![vscode_1805](https://user-images.githubusercontent.com/9026813/28752436-cedc4cbc-7551-11e7-81c6-08e8c1256e64.gif)

**Comment by neilsustc** [comment]
好的，看到了
（话说你这个录动图的软件是什么呀）

**Comment by xa0082249956** [comment]
[ScreentoGif](http://www.screentogif.com/)
按键显示 [keycastOW](https://brookhong.github.io/2014/04/28/keycast-on-windows.html)

**Comment by neilsustc** [comment]
谢谢

**Comment by Lemmingh** [comment]
@yzhang-gh
@xa0082249956
@vonagam

https://github.github.com/gfm/#example-200

---

The **correct** behavior is:

```gfm
|HA|HB|
|-|-|
|`1|2`|3|

<!-- gets: -->

| HA  | HB  |
| --- | --- |
| `1  | 2`  | 3 |
```

```gfm
|HA|HB|
|-|-|
|`1\|2`|3|

<!-- gets: -->

| HA     | HB  |
| ------ | --- |
| `1\|2` | 3   |
```

---

GitHub made the decision in **April 2017**:
https://github.com/github/cmark-gfm/issues/24#issuecomment-298357389

**Comment by yzhang-gh** [comment]
I've pushed a change so that it aligns with the GFM spec.

Remaining issues:

- [ ] code span syntax decoration isn't right in this case
- [ ] VS Code hasn't updated its `markdown-it` to the latest version yet (so the preview tab still has the old behavior).

**Comment by Lemmingh** [comment]
VS Code Insiders is already using markdown-it 12.0.3, which aligns with the latest GFM.
