### ISSUE TITLE
Need add link shotcut

### ISSUE THREAD

**Issue by SunOddman** [neilsustc/vscode-markdown#242]
I can't find add link shotcut key in readme.md, Thank you!

**Comment by neilsustc** [comment]
Please see more information [here](https://github.com/neilsustc/vscode-markdown/issues/20#issuecomment-318393965).

**Comment by SunOddman** [comment]
My environment is VS Code 1.23.1，Mac 10.13.6, I either try 'Command + L' or 'Control + L'，it dosn't work. Is this feature dosn't support Mac? Could you add a whole key-shotcut list for mac and windows in readme.md?

**Comment by neilsustc** [comment]
Because of a limitation of vscode extension, we cannot register such a keybinding for you. You need to press `ctrl/cmd?+shift+p` and execute command `Preference: Open Keyboard Shortcuts File`. And then copy this

```
{
    "command": "editor.action.insertSnippet",
    "args": {
        "snippet": "[$TM_SELECTED_TEXT]($0)"
    },
    "key": "ctrl+l", // or "cmd+l" on Mac
    "when": "editorTextFocus && editorLangId == 'markdown'"
}
```

into the file `keybindings.json` in the right side.

Then it will work.

**Comment by SunOddman** [comment]
Thank you！Got it！👍

**Comment by Mehul** [comment]
This was super helpful, thanks! I'll suggest one change a friend recommended to me (@dwells). If you have a link copied to the clipboard first then this version will paste the link in, saving a little more time:

{
   "command": "editor.action.insertSnippet",
   "args": {
       "snippet": "[$TM_SELECTED_TEXT]($CLIPBOARD)"
   },
   "key": "ctrl+l", // or "cmd+l" on Mac
   "when": "editorTextFocus && editorLangId == 'markdown'"
}

Only change $0 to $CLIPBOARD. Thanks again.

**Comment by yzhang-gh** [comment]
Thanks for the information. Actually, it is now a built-in feature since [v2.1.0](https://github.com/yzhang-gh/vscode-markdown/blob/master/CHANGELOG.md#210-20190216).

![paste](https://raw.githubusercontent.com/yzhang-gh/vscode-markdown/master/images/gifs/paste.gif)

**Comment by Mehul** [comment]
Excellent, thanks!
