### ISSUE TITLE
自动格式化 Markdown 中文 TOC 异常？

### ISSUE THREAD

**Issue by rxliuli** [neilsustc/vscode-markdown#243]
那个，请问插件的格式化 markdown 文件时会出现将 TOC 部分的中文字符删除是什么问题呢？
例如原本 TOC 目录如下：
```markdown
- [Windows 上的工具清单](#windows - 上的工具清单)
    - [开发](# 开发)
```
格式化之后会得到：
```markdown
- [Windows 上的工具清单](#windows)
    - [开发](#)
```
老实说这很糟糕，每次在保存时都要禁用插件并且重新更新 TOC 目录。。。┐(￣ヮ￣)┌

**Comment by neilsustc** [comment]
你是不是还没更新最新的 vscode 😳，不过也有可能是 vscode 自带的生成目录链接的函数还没修复这个 bug（因为默认调用它）

不过不管如何，你如果设置 `toc.githubCompatibility` 为 `true` 肯定是没问题的，那样就会生成和 GitHub 兼容的目录

另外，保存文件时自动更新也是可设置的，`toc.updateOnSave`

**Comment by neilsustc** [comment]
是的😂
