### ISSUE TITLE
the enter perform continue list not enter when using vscodevim plugin to save file

### ISSUE THREAD

**Issue by enali** [neilsustc/vscode-markdown#245]
#### What is the problem?
I want to use your plugin with vscodevim, but when I save file using `:w<cr>`, the enter perform the continue list, not the enter to execute `:w` cmd.

#### How can I reproduce it?
install vscodevim plugin, then type markdown list `*`, then save file use cmd `:w`

#### Is there any error message in the console?

no.

**Comment by neilsustc** [comment]
Could you please download and install the latest CI build to test whether it is fixed? Thanks. (the download link can be found at the end of `readme`)

**Comment by enali** [comment]
Yeah, I try it. It's OK, it's fixed. THX~
