### ISSUE TITLE
二级列表缩进的问题

### ISSUE THREAD

**Issue by linsui** [neilsustc/vscode-markdown#246]
#### What is the problem?
一开始我看错了，抱歉。我才发现列表缩进是自动的。我的问题是对于二级列表，如果是
```
- aaaa
    - bbbbbbb
    -  

```
的形式使用退格和tab可以轻松改变新一行的级别，但缩进为一个制表符时，
```
-   aaaa
    -   bbbbbbb
    - 
```
tab仍然有用，但退格会删除空格而非改变列表级别

**Comment by neilsustc** [comment]
确实是这样，不过这里也没有什么好办法，因为不能确定 <code>-&nbsp;&nbsp;</code> 是用户故意的还是 <code>-&nbsp;</code> 多打了一个空格😂，盲目的缩进不如保守一点，只对 <code>-&nbsp;</code> 缩进

**Comment by linsui** [comment]
是否可以加入选项手动指定缩进或是根据上文判断？另外，刚刚发现表格自动格式化要求分隔符必须要至少3个以上的`-`。我一开始使用了2个结果格式化不起作用让我困惑了好久。:joy:是否可以更改这个判断条件或是在什么地方做出说明？

**Comment by neilsustc** [comment]
根据上文判断有点玄，比如没有上文的时候😂
表格的话那是语法的规定，少于三个的话预览出来也不是表格呀

**Comment by linsui** [comment]
就是因为预览出来很正常，所以我好久都没找到问题出在哪里:joy: 事实上vscode里只有一个`-`也会识别出表格

**Comment by neilsustc** [comment]
😳真的哎，并且 GitHub 上一个 `-` 貌似也可以，但是各个地方对表格语法的说明还不一样。。。

先不管吧，反正你已经知道了嘛

**Comment by linsui** [comment]
:joy:好的好的
