### ISSUE TITLE
Mermaid Feature Request

### ISSUE THREAD

**Issue by louagej** [neilsustc/vscode-markdown#249]
### **Mermaid Feature Request**
Repo: https://mermaidjs.github.io/

It would be awesome to include this in the print to html...

![2018_08_02_ 000](https://user-images.githubusercontent.com/7229592/43578755-0c4c368c-9650-11e8-9c65-31951cb62510.png)

**Comment by neilsustc** [comment]
Maybe I can add Mermaid support in HTML output if this extension finds user has [Markdown Preview Mermaid Support](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid) installed (which adds Mermaid to vscode built-in preview).

Another option is using [Markdown Preview Enhanced](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced) before I implement the feature above.

Related #69.

**Comment by louagej** [comment]
I'm curently using https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid in VS Code.
So this would be a very nice feature
