### ISSUE TITLE
"Automatically show preview" doesn't work for my VSC

### ISSUE THREAD

**Issue by laolai** [neilsustc/vscode-markdown#25]
I install markdown-all-in-one in my VSC and restart it. But when I open a .md file, it can't show preview automatically.

**Comment by neilsustc** [comment]
I cannot reproduce.
Could you please navigate to `Menu bar>Help>Toggle Developer Tools` to see if there is any useful information?

**Comment by coreyzev** [comment]
This is happening to me as well. 
No console errors in Developer tools.

My Environment: 
Mac OSX 10.12.6
VSCode Latest stable, downloaded from VSCode Website today
vscode-markdown: latest stable, installed via extensions tab within VSCode

**Comment by coreyzev** [comment]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-icons|rob|7.12.0
markdown-all-in-one|yzh|0.8.1



---

Steps to Reproduce:

1. Fresh Install of VSCode & Plugin
2. Open *.md file.
3. No preview appears.

**Comment by coreyzev** [comment]
So, i just followed the inherent instructions to preview a MD file in visual studio code, and it's not recognizing the command `⇧⌘V`

I have created an issue with VSCode: https://github.com/Microsoft/vscode/issues/31767

**Comment by coreyzev** [comment]
Deleted comments. Was able to get desired result. 

For me, my issue was PEBKAC

**Comment by neilsustc** [comment]
@coreyzev Thanks for your report 😄

@laolai Do you forget to change setting `markdown.extension.preview.autoShowPreviewToSide` to `true`?

**Comment by neilsustc** [comment]
@laolai Any updates?

**Comment by laolai** [comment]
@neilsustc 
Sorry, i'm busy these days.
"set markdown.extension.preview.autoShowPreviewToSide to true ". It works for me. Thanks.
But Why the default value is false in my computer.

**Comment by laolai** [comment]
@neilsustc
Sorry, i'm busy these days.
"set markdown.extension.preview.autoShowPreviewToSide to true ". It works for me. Thanks.
Why the default value is false in my computer?

**Comment by neilsustc** [comment]
Yes, `false` is the default setting
