### ISSUE TITLE
LaTeX 不能渲染 \case 标签。

### ISSUE THREAD

**Issue by STLGirlfriend** [neilsustc/vscode-markdown#250]
```latex
$\cases { 3 - x \ge 0, \\ 2x - 1 \ne 0, \\ 2x - 1 \ge 0。 }$
```
在 VS Code (with Markdown All in One) 中：
![image](https://user-images.githubusercontent.com/27623826/43618771-d39e2248-96fc-11e8-955f-40744b643c61.png)

在 Typora 中：
![image](https://user-images.githubusercontent.com/27623826/43618834-3ec8d3ba-96fd-11e8-96f5-c65365b270fe.png)

**Comment by neilsustc** [comment]
`\cases` is a MathJax non-standard function. You need to use `cases` environment. For example,

```
$$
\begin{cases}
    3 - x \ge 0, \\
    3 - x \ge 0 \\
    2x - 1 \ge 0.
\end{cases}
$$
```

![image](https://user-images.githubusercontent.com/7588612/43624856-7ae57226-971c-11e8-9975-d9f10829080e.png)

**Comment by STLGirlfriend** [comment]
Thank you.
But it can work in Typora and KaTeX. (You can ignore it.)
