### ISSUE TITLE
Inequality rendering is incorrect

### ISSUE THREAD

**Issue by JettHu** [neilsustc/vscode-markdown#252]
I find the inequality is incorrectly rendered while between `$$  $$` and behind a `\frac`. 

when I typed:
```
$$ R=\frac{1}{k}=\frac{(1+y'^2)^{\frac{3}{2}}}{|y''|}\quad(y''\ne0) $$
$$ \frac{1}{2}(y''\ne0) $$
```
the output is

![Snipaste_2018-08-06_15-26-10.png](https://i.loli.net/2018/08/06/5b67f8f31f138.png)

**Comment by neilsustc** [comment]
Khan/KaTeX#1553

**Comment by upupming** [comment]
Is it fixed now? Still got incorrectly rendered not equal sign.

**Comment by neilsustc** [comment]
The original issue was fixed. But there is another issue #349. I guess there is something strange when vscode applys contributed css.
