### ISSUE TITLE
Activating extension 'yzhang.markdown-all-in-one' failed: Cannot find module './types/bmp'

### ISSUE THREAD

**Issue by CombeeMike** [neilsustc/vscode-markdown#253]
#### What is the problem?
The plugin cannot be activated due to the following error:

![image](https://user-images.githubusercontent.com/30658772/43757913-b58caede-9a1a-11e8-9362-d12b3543852a.png)

#### How can I reproduce it?

The error happens on VSCode start/reload.

#### Is there any error message in the console?
See screenshot above.

**Comment by neilsustc** [comment]
I guess some of the extension files are missing. You can try to uninstall it, close/restart vscode (not reload) and then reinstall this extension.

**Comment by CombeeMike** [comment]
Reinstalling helped and I guess the error was caused on my end.

I'm syncing all VSCode settings & plugins via Dropbox & had some file conflicts with upper/lower case names lately. So I guess those conflicts caused the missing files.
