### ISSUE TITLE
Feature request:  Paste image directly from clipboard to markdown

### ISSUE THREAD

**Issue by creaink** [neilsustc/vscode-markdown#256]
Feature request:  Paste image directly from clipboard to markdown, and store image in the workplace, I would like to use the plugin with vscode and git or cloud as a sync notebook , if it support paste image directly in this plugin it will be very convenient. Thanks

**Comment by neilsustc** [comment]
As I know, vscode doesn't provide methods to access clipboard. Although there are some other libraries, they more or less have some bugs. (see [here](https://github.com/neilsustc/vscode-markdown/issues/129#issuecomment-387208188))

I know another extension [Markdown Paste](https://marketplace.visualstudio.com/items?itemName=telesoho.vscode-markdown-paste-image) is for this feature. You can give it a try.
