### ISSUE TITLE
Visual mode of Vim not honored when hitting Enter

### ISSUE THREAD

**Issue by SimonGustavsson** [neilsustc/vscode-markdown#258]
#### What is the problem?
If you have the extension VsCodeVim/Vim installed you cannot execute commands involving the enter key without a newline being inserted into the file.

#### How can I reproduce it?
Install https://github.com/VSCodeVim/Vim
Open any `.md` file with some content
Move the care to the middle of a line.
Press ESC (to ensure you're in visual mode)
type `:w` and press `enter` (this should save the document)

Instead of the Vim command being executed a newline is inserted into the document.
Not sure if this is a problem with the Vim extension or this one. But it works in all other file types and just stopped working in markdown files after installing this extension so thought I'd post it here.

#### Is there any error message in the console?
No

**Comment by neilsustc** [comment]
Thanks for reporting. (#245 related)

I have fixed it now. You can get this fix with the latest CI build (find the link at the end of `readme`)
