### ISSUE TITLE
表格中的KaTex内包含`|`渲染异常

### ISSUE THREAD

**Issue by JettHu** [neilsustc/vscode-markdown#259]
代码如下：
```
|$A$|$\lambda$|
|---|---|
|$A^*$|$|A|\lambda^{-1}$|
```
渲染结果：
![image](https://user-images.githubusercontent.com/35261585/44297587-933a4180-a306-11e8-8fc5-a5bfeccd1372.png)

**Comment by neilsustc** [comment]
由于表格和数学都是 Markdown 的扩展语法，这个冲突很难直接解决

不过还好 KaTeX 有替代的语法，可以使用 `\vert`，`\lvert`，`\rvert` 来替代 `\`

**Comment by JettHu** [comment]
😂忘了有这个，转义符用不了thx

**Comment by neilsustc** [comment]
😉
