### ISSUE TITLE
format table with Chinese characters will not align to vertical line

### ISSUE THREAD

**Issue by yingqiangyu** [neilsustc/vscode-markdown#26]
I format one table which contains Chinese characters will appear this issue.
One Chinese character will take 2 English character space in table.
We can put 2 space for Chinese table for blank.

| OSI中的层 | 功能                  | TCP/IP协议族                          |
|--------|---------------------|------------------------------------|
| 应用层    | 文件传输，电子邮件，文件服务，虚拟终端 | TFTP，HTTP，SNMP，FTP，SMTP，DNS，Telnet |
| 表示层    | 数据格式化，代码转换，数据加密     | 没有协议                               |
| 会话层    | 解除或建立与别的接点的联系       | 没有协议                               |
| 传输层    | 提供端对端的接口            | TCP，UDP                            |
| 网络层    | 为数据包选择路由            | IP，ICMP，RIP，OSPF，BGP，IGMP          |
| 数据链路层  | 传输有地址的帧以及错误检测功能     | SLIP，CSLIP，PPP，ARP，RARP，MTU        |
| 物理层    | 以二进制数据形式在物理媒体上传输数据  | ISO2110，IEEE802，IEEE802.2          |

**Comment by neilsustc** [comment]
我记得只有特定的字体会把中文显示为两个空格宽吧，这样即使我把中文看作两个空格，对于一般的字体仍然不能对齐。。。

见 [Microsoft/vscode #14589](https://github.com/Microsoft/vscode/issues/14589)

**Comment by neilsustc** [comment]
如果只是要求中文字符两格宽的话倒没什么问题，请提前尝试一下 [v0.8.2](https://github.com/neilsustc/vscode-markdown/releases/tag/v0.8.2)

**Comment by yingqiangyu** [comment]
试了新版本，原来的好些，中英文的宽度不一样，应该是显示的字体中英文不一样宽占主要原因

**Comment by neilsustc** [comment]
你可以尝试一下这个字体 [Inziu losevka](https://be5invis.github.io/Iosevka/inziu.html)，配合版本 v0.8.1 效果很好
