### ISSUE TITLE
Multi preview windows

### ISSUE THREAD

**Issue by zxeoc** [neilsustc/vscode-markdown#262]
If I open two markdown files, let's say A.md and B.md, and preview A.md with ctrl+shift+v. Then switch to B.md and preview it the same way. Then try to switch to another window (any opened window, even besides A and B), the former opened preview window (in this case, the preview of A.md) will close automatically.

**Comment by neilsustc** [comment]
What does "close automatically" mean? I notice that the preview tab changes from "Preview A" to "Preview B". This is a new feature introduced in the recent vscode updates.

**Comment by zxeoc** [comment]
![image](https://user-images.githubusercontent.com/4046320/44708837-bd47ec80-aada-11e8-8d84-e7f185ef305a.png)
I opened notes.md and zipkin.md, and preview them. Now there are two preview windows.
![image](https://user-images.githubusercontent.com/4046320/44708957-0b5cf000-aadb-11e8-92f6-68f70bd11483.png)
Then I switch from zipkin-preview to another window(in this case, to zipkin.md, but any window will do the same). The notes-preview closed automatically.

BTW, do you mean the plugin should open only one preview window at a certain time? I think it's quite useful to preview multi md files together.

**Comment by neilsustc** [comment]
Sorry for forgetting about it... 
Actually, this extension only does little for preview tab (auto open preview if you set `autoShowPreview` to `true`). It is more like a vscode issue. You can verify it by testing with this extension disabled.

**Comment by zxeoc** [comment]
got a little busy this month and forgot this thread, sorry.
I tried this once more, it seems got fixed. I think it's because I updated vscode several days ago.
I'll ask the vscode team if they plan to enable multi preview windows.
Thank you for your time.

**Comment by neilsustc** [comment]
Thanks for the infomation.
