### ISSUE TITLE
Make selection to link to URL on clipboard

### ISSUE THREAD

**Issue by GandalfSaxe** [neilsustc/vscode-markdown#263]
Would really like to see a command and corresponding shortcut to make selected text into link to URL on clipboard. It's a little tedious to manually make:

`this a link to somewhere`

into

`this a [link](https...) to somewhere`

**Comment by GandalfSaxe** [comment]
Oops like to #20 is already open about this. I see the problem is that no API give you access to the clipboard.

How about a keyboard shortcut where it transforms  this:

`this a link to somewhere`

into this:

`this a [link]() to somewhere`

and where the cursor is now placed in the parenthesis so we only have to press paste. It's probably possible via a snippet, but why not build it in? 🙂

**Comment by neilsustc** [comment]
As you can see in #20,

> BTW, this is the upstream issue vscode #31372 preventing this extension to configure the keybinding out-of-box for you.
> But it seems to have a low priority... You can vote for this.

You can add this snippet to your user snippets

```
{
    "command": "editor.action.insertSnippet",
    "args": {
        "snippet": "[$TM_SELECTED_TEXT]($0)"
    },
    "key": "ctrl+l", // or "cmd+l" on Mac
    "when": "editorTextFocus && editorLangId == 'markdown'"
}
```

**Comment by neilsustc** [comment]
Not feasible for now since this kind of snippet cannot be contributed by extension. (You can find more information in the upstream issue Microsoft/vscode#31372)

**Comment by GandalfSaxe** [comment]
I see. I've upvoted the upstream issue, and until then the snippet solution is a good fix. Thanks, and apologies for the duplicate issue.
