### ISSUE TITLE
Syncronous scrolling crashes when using summary tag

### ISSUE THREAD

**Issue by muuvmuuv** [neilsustc/vscode-markdown#264]
#### What is the problem?

When I use `<summary>` inside a markdown file it renders them correctly but the scrolling is killed.

#### How can I reproduce it?

Include a `<summary>` tag with content and more content then the viewport can view before.

#### Is there any error message in the console?

Nope

#### Suggested solution

I think it fixes this when the summaries are opened by default, so the height of both files would be more equal.

**Comment by neilsustc** [comment]
I tried but didn't observe anything wrong.

And actually, the "sync scrolling" feature is provided by the vscode built-in extension rather than this one. Microsoft/vscode might be a more appropriate repository who is related to the "sync scrolling" related issue.

**Comment by muuvmuuv** [comment]
Okay, I'll post it there thank you!
