### ISSUE TITLE
imgToBase64 : relative paths not working

### ISSUE THREAD

**Issue by vfabioux** [neilsustc/vscode-markdown#266]
#### What is the problem?

When converting markdown files which are not at the root of the current project (for exemple under a subdirectory), it is not possible to embed images using base 64 with relative paths, as the path will be searched from the root of the project instead of the markdown file directory as expected.

The only workaround for now is to open the directory where the markdown file is located as the root of the project.

#### How can I reproduce it?

[base64_bug_repro.zip](https://github.com/neilsustc/vscode-markdown/files/2335463/base64_bug_repro.zip)
- Open "TestProject" directory in the archive with VSCode, try to generate HTML file from example.md: it won't work.
- Now try to open "docs" directory inside "TestProject" instead and do the same: it will work.

#### Is there any error message in the console?

"Unable to read file <PathToProject>/example.png, . Reverting to image paths instead of base64 encoding"
Correct path should be <PathToProject>/docs/example.png since example.md is located under docs.

**Comment by neilsustc** [comment]
Good catch.

😔 But I am getting a little busy recently. Hope there is someone can help.

**Comment by neilsustc** [comment]
Fixed in [the development build](https://github.com/neilsustc/vscode-markdown/files/2407293/markdown-all-in-one-1.6.2-fix266.zip).

**Comment by linsui** [comment]
I get this `unableToReadFile \Figure_3.png, revertingToImagePaths` with `![图3](Figure_3.png)` on VSCode 1.33.1. Is it the same error?

**Comment by yzhang-gh** [comment]
Probably not the same issue. What's your folder structure?

**Comment by linsui** [comment]
The markdown file and images are in the samr folder.
