### ISSUE TITLE
enhancement request: unordered list toggle style

### ISSUE THREAD

**Issue by cdbattags** [neilsustc/vscode-markdown#269]
I recently migrated over from Atom and I use Markdown for my daily notes.

https://atom.io/packages/markdown-writer has a feature with (shift-cmd-u) that would style a list or block of text much like `>Markdown: Toggle unordered list` is I think supposed to work.

Any ideas?

I'd be more than willing to put in the dev time for this if needed.

**Comment by neilsustc** [comment]
You mean you would like to add a keybinding for it? It can be done with the user keybinding settings.
