### ISSUE TITLE
Table of Contents generates invalid links for dots

### ISSUE THREAD

**Issue by borekb** [neilsustc/vscode-markdown#27]
For example,

```
## Visit example.com
```

Will get ID of `visit-examplecom` by GitHub but this extension will generate a ToC link of

```
[Visit example.com](#visit-example-com)
```

I didn't do an extensive research about how all the possible ToC plugins behave but I've observer the non-dash behavior at least on GitHub, in marky-markdown and in Caret.

**Comment by neilsustc** [comment]
Yes, you are right. It seems that vscode also removes the dots.

I will have a look at how vscode generate id from header title. I remember it is a `markdown-it` plugin named `markdown-it-named-header`.

**Comment by neilsustc** [comment]
Okay, I find [it](https://github.com/Microsoft/vscode/blob/master/extensions/markdown/src/tableOfContentsProvider.ts#L72).

Will ship with next release.

**Comment by borekb** [comment]
Great, thanks for a quick response && fix.

**Comment by Netway-Warithar** [comment]
I am +1 for this.

**Comment by yzhang-gh** [comment]
Please check out the option `toc.slugifyMode`. (This issue is outdated)

**Comment by Netway-Warithar** [comment]
> Please check out the option `toc.slugifyMode`. (This issue is outdated)

slugifyMode : github

**Comment by yzhang-gh** [comment]
What is your heading? What result are you expecting?

**Comment by Netway-Warithar** [comment]
For example 
```
### Type a name for Database.
```
Will get id of `type-a-name-for-database.` 
**But** this extension will generate a ToC link of
```
[Type a name for Database.] (`#type-a-name-for-database` )
```
I want the dots to remain.
```
[Type a name for Database.] (`#type-a-name-for-database.` )
```

**Comment by yzhang-gh** [comment]
Thanks.

I checked with `# Visit example.com Type a name.`. GitHub generates a link `visit-examplecom-type-a-name`

![image](https://user-images.githubusercontent.com/7588612/88904573-d1c52e80-d287-11ea-9943-6edf58bc6b1e.png)

And the same result in VSCode.

![image](https://user-images.githubusercontent.com/7588612/88904723-046f2700-d288-11ea-82d3-433d382af1b7.png)

If there are dots, then the links won't work.

**Comment by Netway-Warithar** [comment]
> Thanks.
> 
> I checked with `# Visit example.com Type a name.`. GitHub generates a link `visit-examplecom-type-a-name`
> 
> ![image](https://user-images.githubusercontent.com/7588612/88904573-d1c52e80-d287-11ea-9943-6edf58bc6b1e.png)
> 
> And the same result in VSCode.
> 
> ![image](https://user-images.githubusercontent.com/7588612/88904723-046f2700-d288-11ea-82d3-433d382af1b7.png)
> 
> If there are dots, then the links won't work.

Thank you. Maybe from LaRecipe package.
