### ISSUE TITLE
multiple 'command not found' errors

### ISSUE THREAD

**Issue by peterschussheim** [neilsustc/vscode-markdown#271]
#### What is the problem?

- `command 'markdown.extension.onBackspaceKey' not found`
- `command 'markdown.extension.onCopyLineDown' not found`
- `command 'markdown.extension.onCopyLineUp' not found`

#### How can I reproduce it?

 macos insiders build updated today

#### Is there any error message in the console?

<img width="1911" alt="code - insiders009" src="https://user-images.githubusercontent.com/3654683/45237774-a9a43f00-b2ad-11e8-8ba2-66d0cde17556.png">

**Comment by espresso3389** [comment]
Same issue here.
Even disable all the extensions, Markdown All in One 1.6.0 does not work at all.
I'm not sure which one (VSCode or the extension) is wrong...

Version: 1.28.0-insider (user setup)
Commit: a3f9f2e7240106aeec2f1d4bc03d7876bd42e2e4
Date: 2018-09-07T05:20:29.346Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by neilsustc** [comment]
Should be fixed with v1.6.1

**Comment by peterschussheim** [comment]
fixed, thank you
