### ISSUE TITLE
Conflict persists with vscodevim

### ISSUE THREAD

**Issue by rightaway** [neilsustc/vscode-markdown#272]
I'm getting the same error as https://github.com/neilsustc/vscode-markdown/issues/93 with the latest vscode and all extensions. I've also tried it with all extensions disabled except those 2 and the problem persists.

What might help to reproduce this issue on your end is to search for a string that appears in one of the markdown headings, because I don't always get this bug when searching for a string that doesn't appear in any of the headings.

**Comment by neilsustc** [comment]
![vim](https://user-images.githubusercontent.com/7588612/45251508-2a5f4b80-b33f-11e8-9565-ef30fafd509e.gif)

Still cannot reproduce

VSCode v1.27.1
Markdown All in One v1.6.0
Vim v0.16.3

Please try to provide more details which can help reproduction. Only then I can help.

**Comment by rightaway** [comment]
I can reproduce it when I run a search when the cursor is over any of the letters in the word `Text` in this example, but not when the cursor is anywhere else.

```
# Heading

## Subheading

- Text
```

**Comment by neilsustc** [comment]
I can confirm. Further, I find that this issue exists even when in the vim normal mode.

It was compatible before, so I guess there might be something wrong in the mode context setting of the vim extension. I will invertigate. Thanks.

**Comment by rightaway** [comment]
Any news on it? I've had to disable the extension because it's pretty much unusable currently and would love to start using it again.

**Comment by neilsustc** [comment]
I just tested it and found no problem. It might be solved with recent Vim extension updates.

**Comment by rightaway** [comment]
I've tested it now with 0.16.9 of vim extension and 1.6.0 of this extension and it's the exact same problem. Are you on the same versions?

**Comment by neilsustc** [comment]
I guess you are using VSCode older than 1.28.0, so you didn't get 1.6.2 of this extension 😂.
