### ISSUE TITLE
Repeated "Toggle code span" should undo formatting

### ISSUE THREAD

**Issue by domdomegg** [neilsustc/vscode-markdown#279]
#### What is the problem?

Repeated `Toggle code span` should undo formatting, like repeated toggling of bold/italic/strikethrough.

#### How can I reproduce it?

Have cursor at end of a word, apply `Toggle code span`, apply `Toggle code span` again. Result is:

<code>\`word\`\`|\`</code>

expecting:

<code>word</code>

#### Is there any error message in the console?

No

**Comment by neilsustc** [comment]
Fixed in [dev build](https://github.com/neilsustc/vscode-markdown/files/2401670/markdown-all-in-one-1.6.2-fix279.zip)
