### ISSUE TITLE
Ordered List styles

### ISSUE THREAD

**Issue by pbzweihander** [neilsustc/vscode-markdown#283]
Currently this extension automatically numbers ordered lists in this style:

```markdown
1. ...
2. ...
3. ...
```

But I prefer other style:

```markdown
1. ...
1. ...
1. ...
```

Please add options for disable automatic numbering ordered lists feature.

**Comment by neilsustc** [comment]
Please find `markdown.extension.orderedList.marker`

**Comment by pbzweihander** [comment]
setting `markdown.extension.orderedList.marker` to `one` solves the issue. Thanks!
