### ISSUE TITLE
Give an option to render highlights for the two trailing spaces

### ISSUE THREAD

**Issue by KuangLei** [neilsustc/vscode-markdown#288]
#### What puzzles me

I wants to make sure that all of the line endings have the two trailing spaces in my file, but I can't quickly check it though the whole file.  

#### How to solve

So can you give an option to render highlights only for the two trailing spaces with a specified or a configurable character? A recognizable color highlights may also help.  

I would prefer two underline char `__` as [Kate](https://kate-editor.org/), an editor by KDE.  
In the preview below you could find it easy to recognize whether the two trailing space exists with `__`.  

```
This is a line with two trailing spaces.__
And this is a line without trailing spaces.
I wants to make sure__
that all of the line endings have the two trailing spaces in my file,__
but I can't quickly check it though the whole file.__
So can you give an option__
to render highlights only for the two trailing spaces
with a specified or a configurable character?__
A recognizable color highlights is also preferred.__
```

Thanks.

**Comment by neilsustc** [comment]
You can set the vscode option `renderWhitespace` to `boundary`.
