### ISSUE TITLE
Backticks in heading

### ISSUE THREAD

**Issue by borekb** [neilsustc/vscode-markdown#29]
This:

```md
# `make` targets
```

gets converted to this broken link in table of contents:

```md
- [`make` targets](#`make`-targets)
```

I believe it should be:

```
- [`make` targets](#make-targets)
```

**Comment by neilsustc** [comment]
If I use exactly the same code with vscode ([here](https://github.com/Microsoft/vscode/blob/master/extensions/markdown/src/tableOfContentsProvider.ts#L72))

```typescript
function slugify(header: string): string {
    return encodeURI(header.trim()
        .toLowerCase()
        .replace(/[\]\[\!\"\#\$\%\&\'\(\)\*\+\,\.\/\:\;\<\=\>\?\@\\\^\_\{\|\}\~]/g, '')
        .replace(/\s+/g, '-')
        .replace(/^\-+/, '')
        .replace(/\-+$/, ''));
}
```

I get this

```markdown
<!-- toc -->
- [`make](#%60make)
- [`make`](#%60make%60)
- [Chinese 中文](#chinese-%E4%B8%AD%E6%96%87)

# `make

# `make`

# Chinese 中文
```

But I have no idea why \`make\` doesn't work while \`make works well

![bug-iloveimg-compressed](https://user-images.githubusercontent.com/7588612/29491876-023b385c-859c-11e7-8def-8bdd8fc5b2f0.gif)

**Comment by borekb** [comment]
So it seems even VSCode is buggy in this, their pattern misses backtics. Here's a Gist demonstrating that the correct anchor should be ``[`make`](#make)``, not ``[`make`](#`make`)`` or ``[`make`](#%60make%60)``: https://gist.github.com/borekb/a04b0efd22f5c6906559a4fbd8aeda8c.

**Comment by borekb** [comment]
I've reported VSCode issue: https://github.com/Microsoft/vscode/issues/32844

**Comment by neilsustc** [comment]
Thanks

**Comment by neilsustc** [comment]
v0.9.0 released
