### ISSUE TITLE
Table Formatter doesn't support Chinese？

### ISSUE THREAD

**Issue by iCodyYang** [neilsustc/vscode-markdown#293]
Table Formatter for English is ok,but there're some problems in Chinese.
![markdown](https://user-images.githubusercontent.com/41809262/46577866-411ebe00-ca23-11e8-8a7c-0bb8728755d9.gif)

**Comment by neilsustc** [comment]
那是字体的原因，一个中文字符和两个英文字符的宽度不同

有一个能对齐的字体是[更纱黑体](https://github.com/be5invis/Sarasa-Gothic)，可以到 releases 页面下载安装 `Sarasa Mono SC`，重启 vscode 再设置一下字体就可以了

**Comment by iCodyYang** [comment]
> 那是字体的原因，一个中文字符和两个英文字符的宽度不同
> 
> 有一个能对齐的字体是[更纱黑体](https://github.com/be5invis/Sarasa-Gothic)，可以到 releases 页面下载安装 `Sarasa Mono SC`，重启 vscode 再设置一下字体就可以了

感谢，问题以解决。另外改完字体会有几行显示依然不正确，删除重新输入一次就好了。

**Comment by qzi** [comment]
> 那是字体的原因，一个中文字符和两个英文字符的宽度不同
> 
> 有一个能对齐的字体是[更纱黑体](https://github.com/be5invis/Sarasa-Gothic)，可以到 releases 页面下载安装 `Sarasa Mono SC`，重启 vscode 再设置一下字体就可以了

似乎字体在mac有点发虚，有没有mac原生的字体可以推荐

**Comment by yzhang-gh** [comment]
这个字体应该很成熟了，发虚有可能是别的问题，据我所知上个月的 VSCode 版本就会造成字体发虚（[链接](https://code.visualstudio.com/updates/v1_41#_improved-font-rendering-windows-linux)）

至于别的字体只能你自己找找了

**Comment by qzi** [comment]
> 这个字体应该很成熟了，发虚有可能是别的问题，据我所知上个月的 VSCode 版本就会造成字体发虚（[链接](https://code.visualstudio.com/updates/v1_41#_improved-font-rendering-windows-linux)）
> 
> 至于别的字体只能你自己找找了

试了好几种，确实只有sarasa宽度有严格限制，字体调大到了18才会好点

**Comment by qzi** [comment]
> 这个字体应该很成熟了，发虚有可能是别的问题，据我所知上个月的 VSCode 版本就会造成字体发虚（[链接](https://code.visualstudio.com/updates/v1_41#_improved-font-rendering-windows-linux)）
> 
> 至于别的字体只能你自己找找了

我找了一下后发现还有Noto CJK, 感觉这块需要有些总结，以后慢慢发现 ... 

[中文等宽编程字体](https://leonvision.online/technology/2019/12/26/中文等宽字体（monospace-chinese-font-family）/)

**Comment by yzhang-gh** [comment]
👍

**Comment by wenfangdu** [comment]
@qzi 你好，试了一下Noto CJK, Markdown 并不能对齐呢
` "editor.fontFamily": "Noto Sans Mono CJK SC"`
![image](https://user-images.githubusercontent.com/28700378/91684638-9f5e6800-eb8a-11ea-8b51-c32cad5b703e.png)

**Comment by reorx** [comment]
然而如果混入了 emoji，Sarasa 和 Noto Sans 也会出问题…

![image](https://user-images.githubusercontent.com/405972/189386325-ade77054-573a-4e2a-9fee-c4b9b2a77460.png)

**Comment by goofmi** [comment]
最新版本的 vscode<**版本: 1.81.0-insider (Universal)**> 只能用  Sarasa 字体，  Noto Sans 格式化后更糟糕了。
