### ISSUE TITLE
Open Preview close the current file

### ISSUE THREAD

**Issue by gajanak** [neilsustc/vscode-markdown#3]
Hi.

if i enable the extension Version 0.5.1, and enable preview of an markdown file, the Preview 'Tab' replaces the current file. If i am select 'Preview Side By Side'  the Editor split, the Preview opens on the right side, and after one second, the Preview is the current Tab and the orginal markdown file is closed.

If i disable this Plugin, this behavior disappear.

Using vscode 1.12.0-insider 2017-04-14

PS: Previous version of this extension does not show this.

**Comment by neilsustc** [comment]
You are right, that's because I have intended to solve #2 . But it seems not working well.

I'll roll back to v5.0.0 soon. 😅
