### ISSUE TITLE
ToC generation doesn't consider alternative header format

### ISSUE THREAD

**Issue by philippgille** [neilsustc/vscode-markdown#30]
I'm running Visual Studio Code x64 1.15.1 with Markdown All in One 0.8.3. When generating a ToC for my [repository's README file](https://github.com/philippgille/hello-netcoreapp/blob/57c4bb72b7f8de90d83d3a0713bff1674391b390/README.md) (linking a specific commit here for archiving purposes in case I change the header format in the future), the ToC is incomplete and only contains links to headers where I used `#` to mark a line as header. It looks like this:

```
        - [Via cloud service](#via-cloud-service)
            - [AppVeyor](#appveyor)
            - [Travis CI](#travis-ci)
            - [Docker Cloud](#docker-cloud)
        - [Locally](#locally)
            - [FDD + SCD + Chocolatey package + AppImage](#fdd-scd-chocolatey-package-appimage)
                - [Small footprint SCD](#small-footprint-scd)
            - [Docker image](#docker-image)
        - [FDD](#fdd)
        - [SCD](#scd)
        - [Docker container](#docker-container)
        - [Chocolatey package](#chocolatey-package)
        - [AppImage](#appimage)
```

As you can see from the original README (linked above), all h1 and h2 headers are missing.

Most Markdown flavors, including GFM and CommonMark support writing headers not only with leading `#` (for h1) and `##` (for h2), but also with a new line consisting of any number of `=` (for h1) or any number of `-` (for h2) though. The CommonMark spec calls these "setext heading underline", see [CommonMark Spec - setext heading](http://spec.commonmark.org/0.28/#setext-heading)

---

Example:

# Sharp h1

`# Sharp h1`

## Sharp h2

`## Sharp h2`

Underline h1
========

```
Underline h1
========
```

Underline h2
-------------

```
Underline h2
-------------
```

**Comment by neilsustc** [comment]
Yes, the extension just detects `#` for simplicity waiting for someone needs "setext heading underline" syntax.

**Comment by neilsustc** [comment]
I'm going to reuse the vscode built-in Markdown extension's TocProvider. But I find it also doesn't handle setext heading well. I've reported it [Microsoft/vscode#32859](https://github.com/Microsoft/vscode/issues/32859)

**Comment by HDYA** [comment]
Also hit the same problem, thanks a lot

**Comment by neilsustc** [comment]
I've made a PR to fix the upstream issue. It will be rolled out in the next vscode release.

**Comment by neilsustc** [comment]
v0.9.0 released
