### ISSUE TITLE
Markdown TOC is generated incorrectly when `#` appears in a code block.

### ISSUE THREAD

**Issue by spencerwooo** [neilsustc/vscode-markdown#301]
#### What is the problem?

Table of contents is generated incorrectly when I comment a line in a code block.

Such as:

```shell
# I commented this line.
echo 'The line above is commented.'
```

When I have a block of code similar to above in a Markdown file, the TOC auto-generation-tool thinks the line I commented is a header and tries to put it in the TOC as a independent title.

#### How can I reproduce it?

When I have such code block in a Markdown file.

Below is yet another example.

![img](https://i.loli.net/2018/10/15/5bc41d82cf24d.jpg)

👆 The TOC auto generated.

![img](https://i.loli.net/2018/10/15/5bc41c2c74d75.png)

👆 The original Markdown snippet.

#### Is there any error message in the console?

As far as I see, it's not an error, it's a design problem.

**Comment by neilsustc** [comment]
Good catch. This is fixed in the latest dev build.

[More information](https://github.com/neilsustc/vscode-markdown/issues/275#issuecomment-428255125)

**Comment by neilsustc** [comment]
（另外想问下你截图里的字是用笔在触屏上写的吗😂，有意思）

**Comment by spencerwoo98** [comment]
@neilsustc Cool, that's good to know. Looking forward to your next update.🎉🎉🎉
（是的哈哈哈哈哈哈哈哈哈哈哈，ThinkPad Yoga 💻）

**Comment by brogdonm** [comment]
Hey @neilsustc how long until it rolls into the normal distro?

**Comment by neilsustc** [comment]
Actually, I have been waiting for the stable version of `KaTeX` (an upstream module) for two months 😂

![image](https://user-images.githubusercontent.com/7588612/47391213-26ca2d00-d711-11e8-9201-20da83f9de10.png)

---

Anyway, I will release a new version this weekend.
