### ISSUE TITLE
Markdown TOC: how to set depthFrom?

### ISSUE THREAD

**Issue by ahmetb** [neilsustc/vscode-markdown#302]
If I use https://github.com/AlanWalk/markdown-toc, I can do `<!-- TOC depthFrom:2 -->` to prevent h1 titles ending up in TOC.

However this plugin README says "no annoying tags like `<!--TOC-->`". Then, how should users be configuring Markdown TOC settings?

**Comment by neilsustc** [comment]
See [settings](https://www.pornhub.com/view_video.php?viewkey=ph594e916111b9c).

**Comment by ahmetb** [comment]
@neilsustc that's a weird link.

**Comment by neilsustc** [comment]
The `toc.levels` setting can be set per workspace. And we have another solution, the `<!-- omit in toc -->` comment. I guess they can cover the most use cases?

**Comment by ahmetb** [comment]
Thanks.
