### ISSUE TITLE
Disable Auto-creation of TOC

### ISSUE THREAD

**Issue by leesoh** [neilsustc/vscode-markdown#304]
#### What is the problem?

When editing a page with a top-level title of #Foo, adding a link to a bulleted list later in the 
document of [Foo](https://foo.com) will cause that list to become a table of contents.

![image](https://user-images.githubusercontent.com/1276654/47105881-6d47f500-d202-11e8-9e4b-4206ce3800c0.png)

How can I disable this?

#### How can I reproduce it?

See above.

#### Is there any error message in the console?
No

**Comment by neilsustc** [comment]
This should be robustly fixed with the [dev build](https://ci.appveyor.com/project/neilsustc/vscode-markdown/build/artifacts).

List not in the form of `[...](#...)` will never be recognized as TOC starting from this build.

**Comment by leesoh** [comment]
Thank you very much!

**Comment by dialex** [comment]
Is there a configuration to depth limit of TOC? I don't mind the auto-update, as long as it stops at depth=3 (`###`).

**Comment by neilsustc** [comment]
You can control it with [settings](https://github.com/neilsustc/vscode-markdown#supported-settings). (Workspace level is also supported)

**Comment by lastobelus** [comment]
What if I need a list of internal links?

For example, I'm creating a document that has a section on goals, and a section on projects.

Each subsection in goals has a list of projects which relate to that goal. If I add more than three (four?) projects to the list it turns into a TOC. How can I prevent this? (I do want a TOC in the document, and have placed it at the beginning)

**Comment by yzhang-gh** [comment]
Can you provide a minimal example (code snippet)?

**Comment by DavidWells** [comment]
How do you turn this off? What is the setting name?

**Comment by yzhang-gh** [comment]
Please see [here](https://github.com/yzhang-gh/vscode-markdown#supported-settings) for more information about settings.

**Comment by damgot** [comment]
Same problem here.
is it possible to have an option to just turn off TOC detection ?
I've my own extension to generate TOC (because I customize it a little).

**Comment by yzhang-gh** [comment]
Currently, we don't have such an option. I have opened a new issue for it.

If you have a little time and don't mind making a PR, here is the code pointer

https://github.com/yzhang-gh/vscode-markdown/blob/d73116562d5163452d3bf05f5c51dc5d620a4c54/src/toc.ts#L13

We have a similar option (as shown below), just copy it

https://github.com/yzhang-gh/vscode-markdown/blob/d73116562d5163452d3bf05f5c51dc5d620a4c54/src/syntaxDecorations.ts#L61-L68
