### ISSUE TITLE
Math environment autocompletion incompatible with vim mode

### ISSUE THREAD

**Issue by yodahuang** [neilsustc/vscode-markdown#305]
#### What is the problem?

In Vim insert mode, when typing math and selection environment from auto completion, the picked item would not behave correctly. See example below:

If I would like to use the `aligned` environment, for example, then I expect it to be 
```markdown
$$
\begin{aligned}
\end{aligned}
$$
```
But in fact, when I just type `\beg`, the auto-complete shows up, then I select `\begin`, hit enter, and then I pick the environment name in the list, it ends up as follows:
```markdown
$$
\begin{alignedmatrix}
\end{alignedmatrix}
$$
```
Not the weird `matrix` there. It's the first option in the list, and normally it shall disppear, but it does not in the vim mode.

#### How can I reproduce it?

Enable vim mode and try to type any Math enviroment

**Comment by neilsustc** [comment]
This is an issue of Vim. I can reproduce it with this Markdown extension disabled.

To reproduce it, you just need to add a user snippet with "choices" (see [here](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_choice) for instruction), e.g.

```json
{
	"Snippet Choices": {
		"prefix": "choices",
		"body": "${1|one,two,three|}"
	}
}
```

Please report it to the Vim extension.
