### ISSUE TITLE
Is there a keyboard shortcut for code block?

### ISSUE THREAD

**Issue by nosalan** [neilsustc/vscode-markdown#308]
I am able to create keybinding for code span (markdown.extension.editing.toggleCodeSpan) which surrounds the text with backticks.

Is it possible to setup keybinding for code block (triple backticks or 4-space indent)?

**Comment by neilsustc** [comment]
You can add

```json
{
    "key": "your keybinding",
    "command": "editor.action.insertSnippet",
    "args": {
        "snippet": "```\n$0\n```"
    },
    "when": "editorTextFocus && editorLangId == markdown"
}
```

to your `keybindings.json` which can be opened here

![image](https://user-images.githubusercontent.com/7588612/47454081-28096180-d7c6-11e8-83d2-9392d8220931.png)

**Comment by nosalan** [comment]
Thanks, looks powerful. I enhanced it a bit to include the selected text, when shortcut is pressed on a selection.

    {
        "key": "ctrl+shift+C",
        "command": "editor.action.insertSnippet",
        "args": {
            "snippet": "```\n${TM_SELECTED_TEXT}$0\n```"
        },
        "when": "editorTextFocus && editorLangId == markdown"
    }

**Comment by myBestSoftAndPref** [comment]
Go to **Keyboard Shourtcuts** with `ctrl + k, ctrl + s`. Type `markdown code` and set any hot keys.
![image](https://user-images.githubusercontent.com/18548391/49576878-4337c700-f957-11e8-934c-1a5aa57054e7.png)
