### ISSUE TITLE
`(` after KaTeX render problem

### ISSUE THREAD

**Issue by upupming** [neilsustc/vscode-markdown#309]
#### What is the problem?

`(` after block math cannot be rendered properly. It seems only `(` cannot be rendered properly, and any other punctuation is okay.

#### How can I reproduce it?

1. Paste in md file:
```
$$
D_{KL}(P||Q) = \sum_i P(i)\ln\frac{P(i)}{Q(i)}

\tag{2}
$$

((((((((((((((((((((((((((((((((((((2) 式可以理解为
```

2. You will see:

![image](https://user-images.githubusercontent.com/24741764/47500662-01b2f700-d896-11e8-9b46-c78efb5b2451.png)

#### Is there any error message in the console?

No.

**Comment by neilsustc** [comment]
Could you please try the latest dev build (find it at the end of `README`)? I cannot reproduce on my laptop.

**Comment by upupming** [comment]
Sorry for the late reply, and I will test it soon.

I found another problem with this markdown plugin. When I write a long post(3000 Chinese words with plenty of KaTeX equations), vscode gets stuck from time to time, sometimes even has to be reloaded:

![image](https://user-images.githubusercontent.com/24741764/47580600-e02f3980-d981-11e8-8219-b9fd3160abaa.png)

Is there any plan to improve the performance for KaTeX rendering?

**Comment by neilsustc** [comment]
I also see this issue and the suspicious Python process. but I don't think that this is caused by this extension. I was working on LaTeX and Python files.

Any more findings are welcomed.

**Comment by upupming** [comment]
Hi, I have installed the latest build `v1.6.3 fix table formatter`. But the problem still exists:

![image](https://user-images.githubusercontent.com/24741764/47604192-a6fdd480-da28-11e8-84e2-4d39ccc6fb8d.png)

![image](https://user-images.githubusercontent.com/24741764/47604223-f3491480-da28-11e8-9003-fb74bb114600.png)

**Comment by neilsustc** [comment]
![image](https://user-images.githubusercontent.com/7588612/47604289-70579800-d9ef-11e8-90b7-d255d2ea48fb.png)

I find that you have other extensions that might change the Markdown preview. Could you disable all other extension and try again?

Version: 1.29.0-insider (user setup)
Commit: 4a29bd3731e40c07622bae0e9b0ac3b422b5672a
Date: 2018-10-25T05:48:41.485Z

**Comment by upupming** [comment]
It seems a problem caused by `Markdown+Math`. 
![markdown-math-bug](https://user-images.githubusercontent.com/24741764/47604445-8cc5f580-da2c-11e8-9b64-f71f37e715d8.gif)

I use it to generate HTML only(really convenient). If I uninstall it, can I generate html using `vscode-markdown`?

**Comment by neilsustc** [comment]
That's right. The "Markdown: Print current document to HTML" command provided by this extension supports KaTeX.

**Comment by JoeyRxy** [comment]
能问一下怎么升级`katex`吗？我的为什么不支持`\begin{align}`等好多语法啊？（奇怪的是竟然支持`\begin{aligned}`）
谢大佬们

**Comment by upupming** [comment]
插件现在用的已经是最新版 KaTeX了，而且 KaTeX 的更新频率较慢，`align` 在 KaTeX 本来就不受支持，所有可用的函数参见 https://katex.org/docs/supported.html
