### ISSUE TITLE
Add markdown Shortcut element's button  

### ISSUE THREAD

**Issue by Danilux** [neilsustc/vscode-markdown#31]
Hi, was wondering if one could add more markdown expander buttons in the top right bar, right now there's a bold, italic, strikethrough, and list buttons, I'd like to add buttons for code, headings, etc, but also some not standard like for highlighting things, a button that when clicked it would add `<mark>text</mark>` around the selected text, is that possible? Thanks

**Comment by neilsustc** [comment]
Could you please explain with an example? I don't understand.

**Comment by Danilux** [comment]
This plugin adds shortcuts like Ctrl + B to expand the selected text into `**text**`, but also adds button in the top right bar to do the same quicker?, like the b toggle (bold) button, I was wondering if one could add more buttons for toggling headings, code, etc, and also add buttons for things that are not part of the Commonmark spec, like adding a button to highlight text expanding the selected text into an HTML element '<mark>text</mark>', sorry my english is horrible

**Comment by neilsustc** [comment]
To add button to editor menu bar, you can see this image which is from vscode docs

<https://code.visualstudio.com/docs/extensionAPI/extension-points#_context-specific-visibility-of-command-palette-menu-items>

![image](https://code.visualstudio.com/images/extension-points_menus.png)

The code in the largest circle defines the command `markdown.showSource` and its icon. Another circle add the command to the editor title (top right corner) when some conditions are met.

---

May I know whether it is a feature request or just a question?
