### ISSUE TITLE
Table Of Contents are no longer created in v1.7.0 for githubflavored

### ISSUE THREAD

**Issue by schlichtanders** [neilsustc/vscode-markdown#311]
#### What is the problem?

with markdown.extension.toc.githubCompatibility set to true, unfortunately no table of contents is no longer created for text like

```md
Title
====

Subtitle
--------
```

for hashtags titles `#` everything works fine, but not for this...

Little extra: even if there is hashtag sign within a code-fence, it will be taken as a header and inserted in the table of contents. Right behaviour should of course be that it is considered as code and not header.

**Bottomline: githubCompatibility is broken with this new version**

#### How can I reproduce it?

using 
- VSCode 1.28.2
- Markdown All in One 1.7.0
- Windows 10 64bit

#### Is there any error message in the console?

nothing

**Comment by neilsustc** [comment]
This is fixed with the latest development build. You can find the download link at the end of `README`

**Comment by neilsustc** [comment]
I usually use the GUI

![install](https://user-images.githubusercontent.com/7588612/46199698-93ffc380-c307-11e8-84a5-62dbc138c900.png)

**Comment by myBestSoftAndPref** [comment]
Latest Ubuntu 18.04.1, latest VSCode, set your hot key. It works fine. 
![image](https://user-images.githubusercontent.com/18548391/49581988-b6940580-f964-11e8-81fe-0ad53609c618.png)
