### ISSUE TITLE
Chinese input method's First character cannot be caught when switching back using Alt + Tab

### ISSUE THREAD

**Issue by upupming** [neilsustc/vscode-markdown#313]
#### What is the problem?

When I switch back from another window using `Alt+Tab` shortcut, first Chinese character cannot be caught in Chinese input method. This happens sometimes, not always, but I didn't know exactly when this will happen, maybe when I write long markdown files. When I write Chinese in JavaScript files, the problem doesn't exist.  See this gif:

![markdown-input-bug](https://user-images.githubusercontent.com/24741764/47660962-1adbe080-dbd3-11e8-9f0e-e98148ae10cc.gif)

By the way, the problem exists on both Microsoft Pinyin & Sogou Pinyin.

#### How can I reproduce it?

1. Write some Chinese words
2. Use `Alt + Tab` to switch to another window
3. Use `Alt + Tab` to switch back
4. Continue writing

#### Is there any error message in the console?

No.

**Comment by neilsustc** [comment]
Could you disable this extension and test again? I cannot reproduce on my laptop.

**Comment by upupming** [comment]
After I disabled vscode-markdown, the problem still exists. I think it's relevant to vscode itself.
