### ISSUE TITLE
Syntax highlighting for reference link definitions broken

### ISSUE THREAD

**Issue by rbolsius** [neilsustc/vscode-markdown#315]
#### What is the problem?

Syntax highlighting for reference link definitions is broken in the current release.  Previously link definitions containing a hyphen in the name would be highlighted like all other reference link definitions.  Now the link definitions containing a hyphen are not highlighted like the rest.

#### How can I reproduce it?

Paste the following Markdown document into VS Code and change the language mode to Markdown.

```markdown
# Title

  - [link1][ref1]
  - [link2][ref-2]
  - [link3][ref_3]
  - [link4][ref 4]

[ref1]: http://localhost/
[ref-2]: http://localhost/
[ref_3]: http://localhost/
[ref 4]: http://localhost/
```

All the links in the unordered list are highlighted correctly.  However, the reference link definition with a hyphen in the name (ref-2) is not highlighted like the rest of the reference link definitions.

![reference-links-hyphen](https://user-images.githubusercontent.com/2106964/48020317-47c05400-e0fb-11e8-998b-b2b070e27120.png)

#### Is there any error message in the console?

None

**Comment by neilsustc** [comment]
It seems to be an issue of [Microsoft/vscode-markdown-tm-grammar](https://github.com/Microsoft/vscode-markdown-tm-grammar).

**Comment by rbolsius** [comment]
You're absolutely right.  It looks like it was caused by commit [2544443](https://github.com/Microsoft/vscode-markdown-tm-grammar/commit/2544443db4402b3271b1b99bd9a1efb2c757c3d5) (Add shortcut link support).

I will close this issue and open a new issue with vscode-markdown-tm-grammar.

**Comment by rbolsius** [comment]
Created issue https://github.com/Microsoft/vscode-markdown-tm-grammar/issues/39 for the syntax highlighting problems with reference link definitions that contain characters other than alphanumeric or underscore.
