### ISSUE TITLE
Renumber list items

### ISSUE THREAD

**Issue by borekb** [neilsustc/vscode-markdown#32]
Quite a common use case for me is moving items in ordered lists. In the end, I might end up with something like:

```md
1. Lorem ipsum
3. Dolor sit amet
2. Etc.
```

This obviously gets much worse in larger lists, e.g., instructions for something. It would be nice if the numbering could be fixed automatically by this extension.

**Comment by neilsustc** [comment]
A smart solution is always using `1.` as list marker. See discussion [here](https://github.com/neilsustc/vscode-markdown/pull/4#issuecomment-295750926).

**Comment by borekb** [comment]
I personally prefer real numbering as that makes raw markdown more readable (I not always read the rendered HTML version). This extension already has code to support natural numbering so hopefully it can be expanded to the scenario I've described above. Thanks for considering it anyway.

**Comment by neilsustc** [comment]
Yes, it's a good enhancement.

But it seems that currently there isn't any available API for us to listen to the reorder event.
An alternative solution is providing a command `format ordered list`.

Any suggestion?

**Comment by borekb** [comment]
Explicit command is perfectly fine for me. 👍

**Comment by neilsustc** [comment]
Will have a try when I get some free time

**Comment by Gruntfuggly** [comment]
I'd like auto renumbering too please. 8-)

**Comment by Yalhu** [comment]
On preview,I want to show the number what I used . Not renumber from 1.
```
// code
1. list1
2. list2 
some desc ..
3. list3
4. list4
some description ..
5. list5
```
#### Preview: the origin  what I want 
1. list1
2. list2 

some description ..

3. list3
4. list4

some description ..

5. list5

#### Preview now: I don't want
1. list1
2. list2 

some desc ..

1. list3
2. list4

some description ..

1. list5


### Can this work?

**Comment by Yalhu** [comment]
Sorry ,my fault. I generate a localhost page displaying that via `hexo server`.

**Comment by neilsustc** [comment]
Please try [v1.2.0-fix32](https://github.com/neilsustc/vscode-markdown/releases/download/beta/markdown-all-in-one-1.2.0-fix32.vsix).
Works like a charm ✨

**Comment by willhains** [comment]
@yzhang-gh 👋 
I found this doesn't work in the following cases:
- Using tab to indent between the number and the text.
- Using another bound keyboard shortcut for moving lines up/down.
