### ISSUE TITLE
Markdown TOC does not work anymore

### ISSUE THREAD

**Issue by pigreco** [neilsustc/vscode-markdown#322]
from today Markdown TOC does not work anymore:
yesterday:
![image](https://user-images.githubusercontent.com/7631137/48414264-7fa64780-e74a-11e8-9b78-3f428a497796.png)

today:
![image](https://user-images.githubusercontent.com/7631137/48414278-8765ec00-e74a-11e8-9f5b-d6de06660b25.png)

use vscode
![image](https://user-images.githubusercontent.com/7631137/48414288-8f259080-e74a-11e8-8dc3-3475f6545a1a.png)

I have uninstalled and reinstalled but it does not work anymore

**Comment by pigreco** [comment]
https://github.com/AlanWalk/markdown-toc/issues/65

**Comment by neilsustc** [comment]
I don't think it is caused by this extension. Please test with the other extension disabled.

**Comment by grantcurell** [comment]
I have the same problem - what extension had to be disabled to get it to work?
