### ISSUE TITLE
Show progress of task list

### ISSUE THREAD

**Issue by xzzh999** [neilsustc/vscode-markdown#324]
#### What is the problem?
not a bug, just ask if the progress bar is support, or have any plans on it?
like this:
[90%]  [||||||||||||||||||||||||||||||||||     ]

#### How can I reproduce it?
none

#### Is there any error message in the console?

none

**Comment by neilsustc** [comment]
Where do we need a progress bar? 😳

**Comment by xzzh999** [comment]
@neilsustc 
In this case:
I made a ```todolist``` use markdown, and i want show a progress bar so i can know the completion percent of total  works(such as 86% done)  in a more intuitive way.

**Comment by neilsustc** [comment]
It is out of the scope of this extension. I would suggest other extensions like [Todo+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus).

**Comment by xzzh999** [comment]
ok, thanks. close this for now.
