### ISSUE TITLE
auto completion missed in vscode 1.29.1

### ISSUE THREAD

**Issue by nkbai** [neilsustc/vscode-markdown#326]
#### What is the problem?
auto completion missed in vscode 1.29.1

#### How can I reproduce it?

**test** 

$\int$

$\a$

![sp](./doc)

#### Is there any error message in the console?
no

just auto completion doesn't work. it cannot give any hint when I type \a

**Comment by neilsustc** [comment]
![image](https://user-images.githubusercontent.com/7588612/48850544-d8a45a00-eda0-11e8-9107-ce517e9bdaf4.png)

Works well on my laptop. It is strange if there is also no error message.

Could you disable all other extensions and try again?

![image](https://user-images.githubusercontent.com/7588612/48850757-36d13d00-eda1-11e8-85ca-e231a2e5c86b.png)

**Comment by neilsustc** [comment]
What will happen if you manually execute `Trigger Suggest` in the command palette (`ctrl/cmd+shift+p`)

**Comment by nkbai** [comment]
I don't know what happened, it can work now. I just renamed .vscode to .vscode_bak, then started a new environment, exited vscode, and changed .vscode_bak back to .vscode. It is now automatically prompted.

**Comment by nkbai** [comment]
thanks @neilsustc

**Comment by neilsustc** [comment]
😂

**Comment by hannesfrank** [comment]
@neilsustc I struggled with this too. I think this happens somehow for files which are not in the current workspace.

To reproduce:

- Open a workspace/project.
- Open its `README.md` or any other `.md` -> autocomplete works.
- Move file out of the project folder -> autocomplete stops working.

Alternatively:

- It also does not work on if you just open a single markdown file (by double click) or create a new buffer with `ctrl+n` and change the language with `ctrl+k m` to `Markdown`.

Maybe this is the problem in #330 too?

**Comment by hannesfrank** [comment]
Another case where autocomplete does not work perfectly (possibly confusing people with `"editor.suggestOnTriggerCharacters": false`) is when the completion process is invoked after a non-`\` character, i.e.:

1. Type `\` -> autocomplete panel shows automatically.
2. `esc` -> abort/hide panel
3. `ctrl-space` -> autocomplete works
4. Type `a` -> autocomplete shows `\And`, ...
5. `esc` -> abort/hide panel
6. `ctrl-space` (cursor after `\a`) -> __only basic text completes__

**Comment by neilsustc** [comment]
> Maybe it should only check this when completing an image path and not in a math context?

Makes sense! Thank you

> `ctrl-space` (cursor after `\a`) -> **only basic text completes**

Will have a look later
