### ISSUE TITLE
Custom CSS style overridden by vscode defaults

### ISSUE THREAD

**Issue by sataset** [neilsustc/vscode-markdown#329]
- File: `vscode-markdown/src/print.ts`
- Line: 143
- Problem: `getSettingsOverrideStyles()` called at the end of `<head>` which overrides previous custom CSS settings.
- Results: compiling with custom CSS file will contain overridden `font-family, font-size, line-height`.
- Hot Fix (vscode settings):
	```json
	"markdown.preview.fontFamily": "",
	"markdown.preview.fontSize": -1,
	"markdown.preview.lineHeight": -1
	```

**Comment by neilsustc** [comment]
Should be fixed in the [development build](https://ci.appveyor.com/project/neilsustc/vscode-markdown/builds/20495106/artifacts)
