### ISSUE TITLE
Auto completion

### ISSUE THREAD

**Issue by michaeldai7** [neilsustc/vscode-markdown#330]
#### What is the problem?
Image auto completion doesn't work 

#### Is there any error message in the console?

No

**Comment by neilsustc** [comment]
Are you opening a single Markdown file instead of opening a folder containing the Markdown file?

**Comment by neilsustc** [comment]
Then it is not a known issue and I cannot reprodice on my laptop.

Further information might be helpful, such as you sample folder (containing the Markdown and image files, compressed to `zip`)

**Comment by neilsustc** [comment]
I can reproduce now.

It should be fixed with the [development build](https://github.com/neilsustc/vscode-markdown#latest-ci-build).

**Comment by neilsustc** [comment]
Well, there is a critical security issue in the upstream package. We cannot have a development build now.

**Comment by michaeldai7** [comment]
> Well, there is a critical security issue in the upstream package. We cannot have a development build now.

I can wait, thanks
