### ISSUE TITLE
Toggle Preview does not work

### ISSUE THREAD

**Issue by PierreMarchand20** [neilsustc/vscode-markdown#334]
#### What is the problem?

It seems like the extension does not override the "Open Preview" keybinding as described in the documentation.

#### How can I reproduce it?

I am on macOS Mojave with VSCode 1.29.1 and the version 1.7 of the extension.

#### Is there any error message in the console?

No, there is just no "Toggle Preview" when searching commands in the command palette and the keybinding for opening preview, just open and not toggle.
![capture d ecran 2018-11-29 a 15 41 43](https://user-images.githubusercontent.com/15056323/49229185-4aa62000-f3ed-11e8-9049-0b16469a4fd0.png)

**Comment by PierreMarchand20** [comment]
Sorry, I was unclear. The ```Toggle Preview``` does not exist at all. When I use the keybindings you mentioned, it just *open* the preview.

**Comment by neilsustc** [comment]
What do you expect of "toggle preview"? It does "open" the preview if there is not. And it will "close" the preview if you press it again.

Sometimes they will fail if you have changed the focus after toggling the preview. It is hard given the current vscode APIs.

As for why you cannot find them in the command palette, they are not exposed as commands, but only keybindings.

**Comment by PierreMarchand20** [comment]
Well then it does not "close" the preview if I press again.

**Comment by neilsustc** [comment]
Then could you please check whether they are shown in the keybinding settings page (you can find it in the gear icon in the left bottom corner)

![image](https://user-images.githubusercontent.com/7588612/49235291-af637980-f3f1-11e8-90a4-f9622ea973a4.png)

**Comment by PierreMarchand20** [comment]
![capture d ecran 2018-11-29 a 17 50 18](https://user-images.githubusercontent.com/15056323/49237840-6ca89e00-f3ff-11e8-8730-e2015d646c60.png)
it seems that it is there, may be there is something wrong with the focus ?

**Comment by PierreMarchand20** [comment]
Wait ! I understood... it uses the ```ctrl``` key but on macOS, all the keybindings use ```cmd``` instead of ```ctrl```

**Comment by neilsustc** [comment]
So they should be `cmd+shift+v` and `cmd+k v`, right?
I will change them so they will truly "override" the default ones 😂

**Comment by PierreMarchand20** [comment]
Ok, actually, it would be a good idea to change all your keybindings from ```^``` to ```cmd```, so also toggle math environment and others. I did not about the keybinding setting page ! thank you 😄

**Comment by neilsustc** [comment]
Done! You can install the [development build](https://ci.appveyor.com/project/neilsustc/vscode-markdown/build/artifacts) if you want to try it immediately

**Comment by PierreMarchand20** [comment]
Not sure how to do this 😄 I will try it when it will be released ! (and then I will close the issue) Thank you 🙏
