### ISSUE TITLE
Cannot use backspace or enter after first opening markdown file

### ISSUE THREAD

**Issue by HolisticDeveloper** [neilsustc/vscode-markdown#335]
We have written the n
Issue Type: <b>Bug</b>

When first opening a markdown file or changing the languague mode to markdown, the editor does not respond to the backspace and enter keys. This is correlated to seeing the "Activating Extensions" message in the status bar. Sometimes this activation takes several seconds (10+) to complete.

Repro steps:

1. Open VS Code.
2. Open an existing markdown file.
3. Immediately try to use the enter key or backspace key.

Actual results:
The enter key and backspace keys have no effect. Two small warnings are displayed in the lower right hand corner that state:
command 'markdown.extension.onEnterKey' not found
command 'markdown.extension.onBackspaceKey' not found

Expected results:
Basic keyboard commands like enter and backspace should always work.

Extension version: 1.7.0
VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (2.22GB free)|
|Process Argv|C:\Repos\trip-event-service\CHANGELOG.md|
|Screen Reader|no|
|VM|0%|

</details>
eeded data into your clipboard because it was too large to send. Please paste.

**Comment by neilsustc** [comment]
This is the vscode "lazy loading" mechanism. The extension will only be activated on certain events, e.g. the first time you open a Markdown file.

For this issue, we can do nothing since the activation process does need a few seconds. I would suggest to not be that hurry and life will be better...

**Comment by ptrant** [comment]
For me it takes almost a minute per opened Markdown file. When I disable the Markdown-all-in-One extension then enter and backspace become instant.

**Comment by upupming** [comment]
Actually, things are the same with the Python extension. When I write Python code, I have to wait half a minute for Intelligence to work properly. But Intelligence is very fast when writing js code. 

So I think this is an issue of VS code itself. We need a gentle way to handle other files besides js flies

**Comment by neilsustc** [comment]
This should be much better in v2.0.0. Please feel free to open a new one if you still have this issue.

**Comment by MattixNow** [comment]
Same issue on 2.3.1

**Comment by Herman-Wu** [comment]
Same issue in 2.4.0

**Comment by yzhang-gh** [comment]
If you are experiencing a huge lag, please consider filing a new issue with more information (e.g. an example document). There might be some other performance issues.

If it is just about 1 second, I am afraid there isn't much space to improve.

**Comment by reneweteling** [comment]
Happening again in v3.6.3
