### ISSUE TITLE
Add shortcut for strikethrough

### ISSUE THREAD

**Issue by zakkhoyt** [neilsustc/vscode-markdown#35]
Greetings! I'd love to have a keyboard shortcut for strikethrough (for crossing off list items)

Looking through the source code it looks like you can duplicate/modify formatting.ts

// Copy this function
function toggleBold() {
    return styleByWrapping('**');
}

// Rename and change the constant to '~~'. Something like

function toggleStrikethrough() {
    return styleByWrapping('~~');
}

I'd love to submit a PR, but I am not familiar with this dev environment. Seems simple enough (from my perspective), assuming binding a keystroke is also as straight forward. If you have the time, I'd love to have this. Thanks

**Comment by zakkhoyt** [comment]
// package.json
// Add keybinding. I picked T for "todo" as s is taken for save. What ever key...
"keybindings": [
            {
                "command": "markdown.extension.editing.toggleStrikethrough",
                "key": "ctrl+t",
                "mac": "cmd+t",
                "when": "editorTextFocus && editorLangId == markdown"
             },

**Comment by neilsustc** [comment]
How about <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>`</kbd> which means <kbd>ctrl</kbd> + <kbd>~</kbd>

**Comment by neilsustc** [comment]
Shipped with v0.10.0.

You can configure your own keybinding for `markdown.extension.editing.toggleStrikethrough`.
