### ISSUE TITLE
Add a shortcut for adding blockquote

### ISSUE THREAD

**Issue by rosekc** [neilsustc/vscode-markdown#350]
#### What is the problem?

In github or other markdown editor, we can add one blockquote symbol `>`  to quote like this. 

```markdown
> This a line
This is another line
```

> This a line
This is another line

But in vscode it will be rendered like this

> This a lineThis is another line

It seems that it must add a blockquote at the beginning of each line, which is a difficult work as you want to quote a snippet with a lot of lines.

A way to walkaround is to insert cursors (`alt + click`) at the begining of each line to add blockquote symbol . 

Is it ok to add a shortcut for adding blockquote?

**Comment by neilsustc** [comment]
I'm away from my laptop but I would suggest to change the vscode setting `linebreak` first.

**Comment by rosekc** [comment]
It works, though it adds  `<br/>` for each line 😂. Thanks
