### ISSUE TITLE
allow configuration to disable autocomplete

### ISSUE THREAD

**Issue by ksnyde** [neilsustc/vscode-markdown#351]
I love this plugin but the huge list of autocomplete options is a nightmare. I would prefer to turn off ALL markdown autocomplete options and would love it if this were an option of this plugin.

**Comment by ksnyde** [comment]
I will for sure, give me an hour or two to get in front of my computer again.

**Comment by ksnyde** [comment]
In the image below you see what I get every time I press the spacebar; that appears to be the most prominent example of this happening but it may happen in other places too.

![example image](https://content.screencast.com/users/ksnyde/folders/Snagit/media/61e96281-9307-4044-9cda-ff7174672a54/2019-01-05_11-09-30.png)

**Comment by ksnyde** [comment]
This didn't used to happen for me and my colleague's vscode still doesn't. Maybe it's my VS Code Intelisense? Whatever it is it's happened somewhat recently

**Comment by neilsustc** [comment]
Those "snippets" are provided by vscode itself. This might be a vscode issue of your version.

As a workaround, I know an option named "editor.quickSuggestion". Disabling that can resolve this issue but as it says, all suggestions (snippets, completions, ...?) won't show up until you toggle them manually.
