### ISSUE TITLE
请问一些简单的问题

### ISSUE THREAD

**Issue by WangShuoran** [neilsustc/vscode-markdown#353]
请问在vscode中如何显示数学公式，是自动的吗？
请问设置在哪里进行设置？
非常感谢！

**Comment by neilsustc** [comment]
[这里](https://github.com/neilsustc/markdown-it-katex#examples) 有一些例子
支持的数学公式可以到 KaTeX 官网查看 [链接](https://katex.org/docs/supported.html)
