### ISSUE TITLE
Activation event is too generic

### ISSUE THREAD

**Issue by usernamehw** [neilsustc/vscode-markdown#355]
For some people activation event `"workspaceContains:README.md"` is identical to `*`. Extension is loading for nothing.

Is there a good reason why it does this?

**Comment by neilsustc** [comment]
That is because this extension needs 1~2 seconds to load at the very first time opening a Markdown file. Many people complain about this lag. So we pre-activate this extension assuming people might need to edit some MD files later if there is a `README.md`.

**Comment by usernamehw** [comment]
That's how vscode works. It lazy loads language features the first time you open file. You think it would be a good idea if everyone loaded their languages and extensions as `*` (people might use them = true)?

**Comment by neilsustc** [comment]
It is a hard problem. I will keep an eye on how other people feel about it. Thanks for raising it.
