### ISSUE TITLE
VSCode Vim command mode: backspace/delete modifies document

### ISSUE THREAD

**Issue by goek-han** [neilsustc/vscode-markdown#362]
- Extension (Markdown All in One) version: 1.8.0 (2018.12.08)
 - VSCode version: 1.30.2
 - OS: Linux x64 4.15.0-43-generic (Ubuntu 18.04)

#### What is the problem?
When in command mode ´:´, try to edit the command, e.g. press Backspace and the instead of deleting a character in the command, a character in the document gets deleted.

See also https://github.com/VSCodeVim/Vim/issues/3239#issuecomment-454758645

#### How can I reproduce it?

`:asdfasdfas` , try to delete a character by bressing backspace or move with arrow keys and press delete. `:asdfasdfas` stays the same but your document gets modified.

#### Is there any error message in the console?
no

**Comment by neilsustc** [comment]
There was the same issue for <kbd>Enter</kbd> key (#258).

I have fixed it for <kbd>Backspace</kbd> now. You can get it in the [dev build](https://github.com/neilsustc/vscode-markdown#latest-development-build).

**Comment by goek-han** [comment]
Thanks, @neilsustc ! Works perfectly!
