### ISSUE TITLE
Support for Task List

### ISSUE THREAD

**Issue by gitzhuoer** [neilsustc/vscode-markdown#38]
For 

```
- item1
``` 

It's very convenient to get this when hit `return`

```
- item1
- 
```

But for

```
- [ ] task 1
```

hit `return` can only get

```
- [ ] task 1
- 
```

It would be very desirable to get this 

```
- [ ] task 1
- [ ]
```

**Comment by gitzhuoer** [comment]
It works. Thank you so much!

**Comment by PascalZh** [comment]
Good Job!

**Comment by Yalhu** [comment]
Why I can't use task list?
```markdown
- [ ] task 1
- [ ] task 2
```
It just like this:
· [ ] task 1
· [ ] task 2
On vscode preview , `-` becomes unorder list dot.

**Comment by neilsustc** [comment]
Do you have any other md extensions installed? And is there any error message in the console (menubar>help>toggle develop tools)

**Comment by Yalhu** [comment]
othter extension:markdown pdf.
error message:
```
Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
at C:\Users\Administrator\.vscode\extensions\yzhang.markdown-all-in-one-0.9.0\out\src\toc.js:133:51     
at Generator.next (<anonymous>)           
at C:\Users\Administrator\.vscode\extensions\yzhang.markdown-all-in-one-0.9.0\out\src\toc.js:7:71
...
```

**Comment by neilsustc** [comment]
I recommend you update the extension first as task list is supported after v0.11.0 ...

![image](https://user-images.githubusercontent.com/7588612/32088758-63d9dc88-bb18-11e7-9fd5-c66946cea803.png)

**Comment by Yalhu** [comment]
When use task list below, commond `alt + C` doesn't work and there is no error log.
```markdown
1. - [ ] task1
2. - [ ] task2
```

**Comment by neilsustc** [comment]
Task list looks like this

```markdown
- [ ] task 1
- [ ] task 2
```

or

```markdown
1. [ ] task 1
2. [ ] task 2
```

<https://help.github.com/articles/about-task-lists/>

**Comment by Yalhu** [comment]
Thanks for your help.
