### ISSUE TITLE
bug in list editing

### ISSUE THREAD

**Issue by gitzhuoer** [neilsustc/vscode-markdown#39]
For

```
1. list
    1. backspace before me
```
press `backspace` before b will produce 

```
1. list
1. backspace before me
```

That's great. But, for

```
1. list
1.  backspace before me
```

now press `backspace` before b will produce 

```
1. list
backspace before me
```

That isn't what it should be, user just want to delete a extra space

**Comment by neilsustc** [comment]
Please checkout v0.10.3

**Comment by gitzhuoer** [comment]
It works. Thank you so much!
