### ISSUE TITLE
Auto replace text when using Unikey.

### ISSUE THREAD

**Issue by MagicPro1994** [neilsustc/vscode-markdown#41]
Hello there,

Your extension has some problems with Unikey.
Unikey worked well if I disabled your extension.

The bug happened when I tried to type Vietnamese with Unikey.
As I typed "Mo65t" (Unikey will convert to "Một"), the text in markdown file replaced it to Mot.

Can you show me where the function to replace the text is?

**Comment by neilsustc** [comment]
That's really strange.

I don't know Unikey but I guess it automatically replaces `Mo65t` with `Một` when you are typing. Since `Mo65t` was replaced to `Mot` in your case, I think Unikey did do its operation but there is something wrong.

As for the extension, it will listen to <kbd>Enter</kbd>, <kbd>Tab</kbd> and <kbd>Escape</kbd> keys and will do some different operations when you are editing Markdown list. Are you using this keys?

**Comment by MagicPro1994** [comment]
Thanks for you information.
I will check it on my Laptop then feedback to you.

**Comment by MagicPro1994** [comment]
After checking, I found that Unikey used Backspace. There was a conflict between your extension and Unikey.
I'm trying to fix my own problem. If I could solve them, I will give you a pull as a patch for those who uses Unikey.

**Comment by MagicPro1994** [comment]
@neilsustc 
I solved my problem but it didn't work at all cases.
If I typed "Mo65t", it works well. But when I typed "Mot65", it doesn't work.

By the way, do you know how to extend Default Key Handler?
For example:
if (something) {
    doCustomFunction();
} else {
    callDefaultHandler();
}

**Comment by neilsustc** [comment]
If you are talking about vscode key handler, it can be override by *add new keyboard shortcuts* which execute your code.

```
if (your condition) {
    // your code here
} else {
    // default behavior
}
```

**Comment by MagicPro1994** [comment]
@neilsustc : No, I want to ask to use the default handler.
If you disable all extension, when you press backspace, the default handler will be executed.
Command "deleteLeft" is just a case of the default handler. That's the reason why I can use Unikey by disabling your extension.

**Comment by neilsustc** [comment]
Okay, that is the problem.

But according to vscode [doc](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-rules), I think `deleteLeft` should be the default handler. Maybe we should report this to vscode?

**Comment by neilsustc** [comment]
The only one "backspace" in the default keybindings

![image](https://user-images.githubusercontent.com/7588612/31614289-79ab847a-b2b8-11e7-9e3c-d1ee976b62c6.png)

**Comment by MagicPro1994** [comment]
@neilsustc When I press "backspace", it delete 4 spaces. But when I use "deleteLeft", it just delete one space. I think we should report to VSCode.
As I know, VSCode solved the problem of Vietnamese Input a year ago.

**Comment by neilsustc** [comment]
Have you ever tried to change the `onBackspaceKey` function to only execute `deleteLeft`, I mean

```javascript
function onBackspaceKey() {
    return commands.executeCommand('deleteLeft');
}
```

And then test whether the problem is still there?

**Comment by MagicPro1994** [comment]
Yes, there it is.
"Thien Ha Dai Su" should be replaced "Thiên Hạ Đại Sự"
![image](https://user-images.githubusercontent.com/8509065/31618566-7fcbcd2a-b2bc-11e7-8cc6-ea5c6c7da6ca.png)

**Comment by MagicPro1994** [comment]
Fixed but still has some minor bugs (typing fast).
Please grant me permissions to push to your repository.

**Comment by neilsustc** [comment]
I have to disable you handler, because <https://github.com/neilsustc/vscode-markdown/blob/master/src/unikeyHandler.ts#L15-L16> results this

![vn](https://user-images.githubusercontent.com/7588612/32305800-7641a52e-bfb2-11e7-99b4-154f2db7adaa.gif)

**Comment by MagicPro1994** [comment]
@neilsustc Ok. I have another way to solve my problem. I just need change key "Backspace" to "Shift+Backspace" or "Alt+Backspace". No need to modify the code.

**Comment by neilsustc** [comment]
Good to hear that

**Comment by Lemmingh** [comment]
This is now tracked at #200
Thank you again.
