### ISSUE TITLE
Hide Outline view in explorer panel

### ISSUE THREAD

**Issue by cprogrammer1994** [neilsustc/vscode-markdown#42]
I would like to hide/remove the "Outline view in explorer panel" feature.
Is there any settings for this?

**Comment by neilsustc** [comment]
Currently you can right click on the view and select "hide"

**Comment by cprogrammer1994** [comment]
Thank you, but my problem is that when I open VS Code it appears then I have to fold / hide it.

**Comment by MagicPro1994** [comment]
@cprogrammer1994 You can go to extension folder.  ~\.vscode\extensions\yzhang.markdown-all-in-one-0.10.3\package.json.
Search element "Views" and remove it from the JSON file.

**Comment by cprogrammer1994** [comment]
Thank you!

I close this issue.
I realized it should be vscode feature to save "Hidden" state of any of the panels.

**Comment by sprasad19** [comment]
right click on outline then select hide option.

**Comment by nachbarshund** [comment]
> Currently you can right click on the view title "OUTLINE" and select "hide".
Sometime it can be so easy. Thank you 👍

**Comment by BrianBNguyen** [comment]
how do I unhide it?

**Comment by BrianBNguyen** [comment]
> right click on outline then select hide option.

how do i unhide it?

**Comment by yzhang-gh** [comment]
<img src="https://user-images.githubusercontent.com/7588612/83317620-96df5400-a260-11ea-8ba2-2e8f07272670.png" alt="unhide" width="301px">

**Comment by BrianBNguyen** [comment]
yeah see how folder is hided (in gray) I can't unhide it I tired right clicking but it won't give me the option to unhide folders.

**Comment by yzhang-gh** [comment]
You want to hide/unhide "Folders"? I don't think you can do that. (It is always present.)

<img src="https://user-images.githubusercontent.com/7588612/83342418-e33e9880-a321-11ea-9313-26e87cd96ec8.gif" alt="hide" width="306px">

**Comment by BrianBNguyen** [comment]
you did it with outline. But can you try it with your Folders (See how the Folders is in gray I can't make it ungray and unhide it)

**Comment by yzhang-gh** [comment]
> You want to hide/unhide "Folders"? I don't think you can do that. (It is always present.)

**Comment by BrianBNguyen** [comment]
> > You want to hide/unhide "Folders"? I don't think you can do that. (It is always present.)
> 
> (BTW, this extension provided an outline view a long time ago, which has been removed as VSCode implemented it. If you have more questions about hiding/unhiding views, probably you need to ask VSCode directly.)

thanks :D
