### ISSUE TITLE
Engine looses track of TOC when renaming first section title of TOC

### ISSUE THREAD

**Issue by baflo** [neilsustc/vscode-markdown#48]
When I rename the first heading used by the TOC, the engine does not recognize the TOC anymore. 

I know one of the measures to find the table is to match the first item. However, maybe one could extend this behaviour such that if the first item was not found, try to match the second.

**Comment by neilsustc** [comment]
Will improve it when I get a good Internet connection

**Comment by TotallyInformation** [comment]
The TOC updates don't seem to be working at all on my installation. I can create one but updates never work.

v 1.1.2, vscode v1.22.1, W10, 64bit.

**Comment by neilsustc** [comment]
@TotallyInformation could you please provide a sample snippet/file?

**Comment by neilsustc** [comment]
Close with v1.4.0
