### ISSUE TITLE
user defined snippets for markdown no longer work after enable Markdown All in One

### ISSUE THREAD

**Issue by zhanglix** [neilsustc/vscode-markdown#49]
steps to reproduce 

1. define some snippets for Markdown, and ensure them working. e.g.:
```json
{
"math inline" : {
	"prefix": "$",
	"body": ["$`$1`$"],
	"description": "inline math"
}
}
```
2. install Markdown All in One v0.11.0
3. user defined snippets no longer work
4. disable Markdown All in One
5. user defined snippets work again

**Comment by neilsustc** [comment]
Yes, I find that the first time you type `$` there is no snippet.

But after that (typing `$` again) it will work. Is it?

![image](https://user-images.githubusercontent.com/7588612/32043861-81903ede-ba6e-11e7-8eb7-1c7b80063785.png)

**Comment by zhanglix** [comment]
I found that after typing "$",

- if you type "ctrl + <space>", the snippet will show again.
- if you type "<tab>", the snippet will not show. (with setting: "editor.tabCompletion": true)

Maybe there are some conflicts between the build-in tabCompletion setting with "Markdown All in One".

Anyway, the "ctrl + <space>" solution  work for me very well. 

Thank you for sharing such a great VS extension. 👍

**Comment by ketozhang** [comment]
Quick suggestion is disabled on Markdown by default. To get your behavior without the need for `ctrl + space`, add this to your **User Settings**:

```json
    "[markdown]": {
        "editor.wordWrap": "on",
        "editor.quickSuggestions": true
    },
```

The `editor.tabCompletion:true` actually does not behave like I'd expect regardless if `editor.quickSuggestions` is true or false. I am not sure why tabCompletion without quickSuggestion won't work

**Comment by neilsustc** [comment]
@ketozhang <kbd>tab</kbd> key is overridden for the usage of indenting list

![image](https://user-images.githubusercontent.com/7588612/32691265-da460bac-c73f-11e7-9d48-5b7455b535c4.png)

**Comment by ketozhang** [comment]
@neilsustc Shouldn't that <kbd>tab</kbd> only refer to listing environment after:

```markdown
# snippet tabCompletion is active here but not listing tab

* Item 1
    * Item 1a  #listing tab is active here but not tabCompletion
```

**Comment by neilsustc** [comment]
`tabCompletion` will work with v0.11.2!
