### ISSUE TITLE
Table formatter bug

### ISSUE THREAD

**Issue by rightaway** [neilsustc/vscode-markdown#51]
When I save this file it tries to turn it into a table which isn't what I want. This bug should be fixed but more importantly there should be a setting for this plugin not to change the file at all automatically. There's a setting for that but just for the TOC, not for everything.

```
  ## heading

  - one
    - this is `|two|`
      - three
```

**Comment by neilsustc** [comment]
It is a bug to recognize that snippet to be a table.

For the second point, the table formatter is registered for markdown language. You can use this vscode setting `"editor.formatOnSave": false`.

**Comment by rightaway** [comment]
But I'd like to continue having my other code be formatted on save, just not my markdown files. Could you please add it as a configurable option?

**Comment by neilsustc** [comment]
Added to next version

**Comment by rightaway** [comment]
Thanks! Is there any other formatting that happens automatically on save with this extension, or was it only the table formatter?

**Comment by neilsustc** [comment]
Currently only GFM table.
