### ISSUE TITLE
0.11.1 fix breaks backspace, tab and enter

### ISSUE THREAD

**Issue by mankewd** [neilsustc/vscode-markdown#52]
The fix implemented in 0.11.1 to use tab/backspace to indent/outdent task lists seems to have broken the behaviour of tab, backspace and enter in normal editing mode. I.E. When not on a task list.

Pressing any of these keys throws a warning 'command markdown.extension,onbackspacekey not found',etc. and the action is not performed. 

If I disable the extension and reload the editor page then the keys work as expected. 

It limits the extension's usefulness. Was this really the intended behaviour of tab, backspace and entered with the extension. Thanks.

**Comment by neilsustc** [comment]
When you open a markdown file for the first time, the extension requires a period of time to be loaded.

Could you please just open a markdown file and wait for a while (several seconds) and then see whether it will work normally?

**Comment by neilsustc** [comment]
🤔 That's strange. Is there any error in the console (from menubar>help>toggle developer tools)

**Comment by mankewd** [comment]
No, nothing at all as far as I can see....

![image](https://user-images.githubusercontent.com/32249235/32475399-ad3ec48c-c3c5-11e7-868d-d0278d4badfe.png)

**Comment by mankewd** [comment]
Sorry, there are some errors....

![image](https://user-images.githubusercontent.com/32249235/32475529-526d37ae-c3c6-11e7-8865-9ba9d8870155.png)

**Comment by neilsustc** [comment]
It seems that the extension files are broken. You can try uninstall it and then reinstall

**Comment by mankewd** [comment]
That seems to have fixed it. I can now use all of the keys normally without any warnings being thrown.

I'll close this issue. 

Thanks!
