### ISSUE TITLE
toc

### ISSUE THREAD

**Issue by no5ix** [neilsustc/vscode-markdown#53]
作者qq.com暴露了是国人, 所以直接飙中文啦

希望可以添加toc里的链接不转码的选项, 以及支持大小写, 

现在如果我标题里有大写, 生成的toc是小写的

**Comment by neilsustc** [comment]
可以是可以，不过我比较好奇现在这样不是挺好的吗？😳

在链接里把中文编码和转成小写是通行的做法，vscode 也是这样做的

**Comment by no5ix** [comment]
转成小写之后，我点击那个链接就不能跳转了，所以我希望这些可以配置，我用的是主流的hexo加next主题，应该所有用hexo加next的都会遇到我这种情况，所以希望可以添加转码选项和不改变大小写选项，我们自己配置就好

**Comment by no5ix** [comment]
或者你告诉我怎么改你的源码，我自己撸，🤣

**Comment by neilsustc** [comment]
那就更好了。我是直接调用了 vscode 的 `slugify` 函数，看来你需要给 vscode 提 PR 😁

<https://github.com/neilsustc/vscode-markdown/blob/master/src/toc.ts#L126>

<https://github.com/Microsoft/vscode/blob/master/extensions/markdown/src/tableOfContentsProvider.ts#L85-L92>

**Comment by no5ix** [comment]
圣光会制裁你！😆
