### ISSUE TITLE
Why is markdown.extension.orderedList.marker defaulted to 'one'?

### ISSUE THREAD

**Issue by ketozhang** [neilsustc/vscode-markdown#54]
Not an issue just a discussion on convention. Why is the default `"markdown.extension.orderedList.marker": "one"` when naturally most people would think ordered list are increasing in order? Either way I don't see why someone would use `"one"` (inspire me)

This behavior is very weird to me:
```markdown
1. Item 1 #press enter 
1. Item 2
```

Of course I can just change the setting. But default settings should functional, convenient, conventional, and then popular opinion.

**Comment by neilsustc** [comment]
There is another vscode extension Markdownlint, and it use 'one' by default
<https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md029---ordered-list-item-prefix>

Another discussion [vscode-markdoen#4](https://github.com/neilsustc/vscode-markdown/pull/4)

---

Let's leave this issue open to see what do other people think of.

**Comment by ketozhang** [comment]
🙁 unfortunately those rules really don't explain the motivation for it that well.

Welp thank god there is a settings sync extension.

**Comment by neilsustc** [comment]
Now `ordered` is the default setting
