### ISSUE TITLE
Extension does nothing if file isn't *.md, should be mentioned in readme. Also, option to enable for .txt files too

### ISSUE THREAD

**Issue by yaomtc** [neilsustc/vscode-markdown#56]
I understand why you wouldn't want the keyboard shortcuts to be changing for files that aren't Markdown, but regardless, README.md and the Overview page should mention this requirement. I would also like a option, perhaps disabled by default, to allow this extension to work on .txt files as well.

Thanks for this great extension!

**Comment by neilsustc** [comment]
The activation events is before we can register command and configs. In `.txt` file, the extension is not activate at all.

A solution is to select language manually using the right bottom button in vscode

![image](https://user-images.githubusercontent.com/7588612/32922146-cc28566c-cb6b-11e7-841f-b988115f69aa.png)

(using markdown mode in txt file)
