### ISSUE TITLE
Tab doesn't indent list item

### ISSUE THREAD

**Issue by DWFlanagan** [neilsustc/vscode-markdown#59]
When I am writing a list, hitting tab puts a tab in between the list marker and the text rather than indenting the list item.

Expected:

```
* One
* Two
    * Three 
```

I get:

```
* One
* Two
*   Three
```

VS Code 1.18.1 (OS X 10.2.6), Markdown All in One 0.11.2

There are no errors in the console.

**Comment by neilsustc** [comment]
It works well on my side (on Windows, I don't have Mac)

![no-iloveimg-compressed](https://user-images.githubusercontent.com/7588612/33460957-65a44378-d66b-11e7-8a59-c891063ac600.gif)

Do you have other extensions related to the <kbd>tab</kbd> key?

**Comment by DWFlanagan** [comment]
I disabled all other extensions and reloaded – same behavior.

I also tried uninstalling and reinstalling.

Are there any custom settings I should enable? Here is my user settings file:

```
{
    "jupyter.appendResults": true,
    "window.zoomLevel": 1,
    "python.formatting.formatOnSave": true,
    "vsnotes.defaultNotePath": "/Users/dflanagan/Documents/VS-notes",
    "workbench.startupEditor": "newUntitledFile",
    "python.linting.pylintEnabled": false,
    "python.linting.flake8Enabled": true,
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/.vscode": true
    },
    "git.confirmSync": false,
}
```

**Comment by neilsustc** [comment]
Thanks for your detailed report.
This feature is always enabled. So it's strange.
Does <kbd>enter</kbd> key work as expected (auto add list marker for new line)?
(I will make a debug version for you if we still cannot find the cause. Maybe several hours later)

**Comment by DWFlanagan** [comment]
`Enter` key does work, it creates a new line with a bullet or a dash as expected.

Thanks!

**Comment by neilsustc** [comment]
Please install this [debug version](https://github.com/neilsustc/vscode-markdown/releases/tag/v0.11.2) and  then inspect the console output :)

**Comment by DWFlanagan** [comment]
I installed the linked debug version, but the behavior is still the same. 🙁 There are no errors in the Developer Tools console.

**Comment by neilsustc** [comment]
I guess there should be some output information, such as "[listEditing] 'onTabKey' registered", etc. Could you find those debug output (not error)

**Comment by DWFlanagan** [comment]
Sorry. OK, I disabled all other extensions and when I do that I get a single line in console when I try tabbing in/editing a list:

`[Extension Host] [listEditing] 'onTabKey' registered.     console.ts:123 `

**Comment by neilsustc** [comment]
It seems that the callback function `onTabKey` is not invoked at all.

If you press `ctrl+shift+p`, 'open keyboard shortcuts file', can you see settings like this
```json
{
    "key": "tab",
    "command": "markdown.extension.onTabKey",
    "when": "editorTextFocus && !editorReadonly && !editorTabMovesFocus && !inSnippetMode && !suggestWidgetVisible && editorLangId == 'markdown'"
}
```

**Comment by DWFlanagan** [comment]
I deleted my custom keybindings and replaced with only your snippet above. This resolved it! There must have been a conflict somewhere.

Thanks for your help!

**Comment by neilsustc** [comment]
Glad to hear that
