### ISSUE TITLE
Table source beautifier

### ISSUE THREAD

**Issue by Ash258** [neilsustc/vscode-markdown#6]
Do you plan to add automatic table code formatter / beautifier? Table code is mess sometimes and it's good to have automatic way to align.

![LIke this](https://image.prntscr.com/image/6VP01FlRTBegCZUeNJgQww.png "Example")

**Comment by neilsustc** [comment]
I'd like to but I have some questions about your screenshot,

This is the table you showed,

```
|_. name           |_. age |
|   John Doe       |>.  35 |
|   Jane Doe       |<. 19  |
|   Nanashi Gonbei |=.  6  |
```

1. Do you expect space before `_.`, `>.`?
2. Should `name` and `John Doe` be aligned as in your screenshot? What is the alignment rule?
3. How are the `age`, `35` and `19` aligned? I don't understand ...

**Comment by neilsustc** [comment]
![table formatter](https://raw.githubusercontent.com/neilsustc/vscode-markdown/master/images/gifs/table-formatter.gif)

😉

**Comment by neilsustc** [comment]
I'll close this since there is no more request beyond the current solution.
