### ISSUE TITLE
Outline in Explorer View is only shown when inside a folder context

### ISSUE THREAD

**Issue by erichiller** [neilsustc/vscode-markdown#60]
This may be similar to #40 or somehow related to the update as I *think* it worked prior but am not sure.

The problem and how you can reproduce it are the same:
- open the a *.md file directly with code and no Outline will be shown in the Explorer sidebar.
- open the folder containing said file then click on the very same file x.md and the Outline will appear as it is expected to.

Nothing in the Console is output related to this.

**Comment by neilsustc** [comment]
You are right. That is because 21b0c38, adding a restriction `resourceLangId == markdown`.

I also test another extension "LaTeX Workshop" and find the same issue. So it looks like a upstream issue.

**Comment by neilsustc** [comment]
Issue created

**Comment by qingkong1998** [comment]
Markdown outline preview and file manage function ,just i need, thank you.

**Comment by neilsustc** [comment]
Please try v1.0.1
