### ISSUE TITLE
Issues regarding the function 'convert to html'

### ISSUE THREAD

**Issue by zhongliwu** [neilsustc/vscode-markdown#61]
When I use the markdown tools to convert .md file to .html file, a problem occurred:
"Running the contributed command:'markdown.extension.printToHtml' failed"

Is this a bug? Or did I miss something in my vscode?

Thanks for help!

**Comment by neilsustc** [comment]
Could you please open the console to see if there is any error message?
(menubar > help > toggle developer tools)

**Comment by zhongliwu** [comment]
Neilsustc, did you update the plugin? I tried today (Dec 5th at UTF+8), and it works all well! 

Anyway, thanks for help! I will let you know if it happen again (but I hope it will never happen again ^_^).

**Comment by neilsustc** [comment]
No updates these days. But it is okay since it works now 😉
