### ISSUE TITLE
Whitespace issues with Markdown in VSCode

### ISSUE THREAD

**Issue by carlca** [neilsustc/vscode-markdown#62]
The problem is that VSCode (Insiders) is messing up the whitespace on my Markdown files.

This is my Markdown code before Cmd S

![](https://user-images.githubusercontent.com/260612/33775183-7ffae6b2-dc35-11e7-8daf-5a9125853c12.png)

This is my Markdown code after Cmd S

![](https://user-images.githubusercontent.com/260612/33775275-bcd79cc4-dc35-11e7-9366-f2dc48f9ccf8.png)

As an obvious expert in Markdown and VSCode, is this something you've noticed and do you have any ideas about what's causing the problem?

I have your extension installed and haven't seen any features directly related to this issue, but I thought you might have the necessary expertise to be able to advise!

Disabling extensions doesn't make any difference, and as I said VSCode (Stable) the problem doesn't occur but it does in VSCode (Insiders)

**Comment by neilsustc** [comment]
I am on code insiders (commit d8989c9, Windows) and everything seems to work well.
Could you please provide more information for me to reproduce it? (e.g. your vscode version; code snippets)

According to your description, one thing relevant might be "auto format on save". But I also don't know why.

**Comment by carlca** [comment]
The suggestion you made about the other word wrap issue also helped me here. I updated my VSCode (Insiders) with the settings from my VSCode (Stable) and everything seems to be as I want! Thanks again, I really appreciate your help!

**Comment by carlca** [comment]
I think setting the `"editor.formatOnSave": false,` may have been the fix here. The "format on save" mechanism for Markdown seems to be problematic, whereas the Alt-Z formatting works just fine.

**Comment by carlca** [comment]
A difference with our setups may be the fact that I am using VSCode for the Apple Mac.

**Comment by neilsustc** [comment]
😉
