### ISSUE TITLE
Wordwrap issues in Markdown with VSCode

### ISSUE THREAD

**Issue by carlca** [neilsustc/vscode-markdown#63]
Once again I am looking to call upon your knowledge of Markdown/VSCode and tell me if this issue is something that your extension could support in the future.

The default behaviour of VSCode (both Stable and Insiders) appears to be to Wordwrap at 70 columns, regardless of settings. I have settled for a compromise solution of disabling the formatting entirely for Markdown:

![screen shot 2017-12-10 at 11 07 16](https://user-images.githubusercontent.com/260612/33804324-5ef7084a-dd9a-11e7-9952-eff075125aa4.png)

The `editor.wordWrap` settings are my attempt to fix the word wrap at 100 columns, but it doesn't seem to work. I use Markdown for Hugo pages which is why I have chosen 100 columns as the preferred width. 

Instead, I have to rely on the `"editor.rulers": [100],` setting, and do the word wrap manually, which is a bit of a nuisance! 

It does seem that Markdown support in VSCode is somewhat broken. Do you have any thoughts on this and is it something that you will be able to help with in the future?

Thanks in advance!

**Comment by neilsustc** [comment]
It seems that you need to use **`"editor.wordWrap": "wordWrapColumn"`** along with `"editor.wordWrapColumn": 100`

**Comment by carlca** [comment]
That suggestion, combined with the Alt-Z shortcut achieves just what I wanted. Thanks very much. That's going to make my life much easier!

**Comment by rudolfolah** [comment]
for Markdown mode I had to adjust the setting like this:

```javascript
// settings.json
{
    "[markdown]": {
        "editor.wordWrap": "wordWrapColumn",
        "editor.wordWrapColumn": 100,
    }
}
```
