### ISSUE TITLE
Outline preview like MSword

### ISSUE THREAD

**Issue by qingkong1998** [neilsustc/vscode-markdown#67]

**Comment by qingkong1998** [comment]
outline preview function , I need it , Can you add it , thank you.

**Comment by neilsustc** [comment]
现在就有大纲视图的功能呀

![outline](https://raw.githubusercontent.com/neilsustc/vscode-markdown/master/images/outline.png)

**Comment by qingkong1998** [comment]
没有啊，我说的是直接单个Markdown文档，比如像MSWord侧边栏大纲，不是TOC，单独侧边显示的大纲浏览：
![image](https://user-images.githubusercontent.com/13163880/34085282-2558b874-e3c9-11e7-98c8-aa91e654ebff.png)
或者马克飞象的大纲：

![snipaste_20171218_080419](https://user-images.githubusercontent.com/13163880/34085350-4a0cbafc-e3ca-11e7-9b3a-96f2c8a81e20.png)

Ulysses的大纲功能也不错，Can you offer this function，I just need it ！

**Comment by qingkong1998** [comment]
最好像MsWord这样有折叠功能的大纲浏览功能，那是最完美的，这样使用vsc做笔记就不用使用Word了，自己再搞个vim插件就行了，现在问题是vim不能直接编辑和实时浏览，要不我更喜欢在终端下使用vim，配合各种命令非常好，就是实时预览问题，要是vim能实时左右两窗口编辑和预览Markdown那就完美了。

大纲浏览功能，马克飞象还不错：
![image](https://user-images.githubusercontent.com/13163880/34085437-cf39c412-e3cb-11e7-808f-2ed88c5751be.png)

**Comment by neilsustc** [comment]
我还是没有理解，目录不也可以折叠，浏览吗

![outline-iloveimg-compressed](https://user-images.githubusercontent.com/7588612/34086084-f6413fc4-e3d3-11e7-96a3-ab56a1f620ab.gif)

你所希望的功能和这个差别在哪？

---

我猜测是因为 #60 这个 vscode 自己的 bug 让你误以为目录是整个文件夹的。目录本来就是每个 Markdown 文件都有的，只不过现在有这个 bug「你不打开整个文件夹，左侧的视图就不会激活」
