### ISSUE TITLE
Dynamic outline instead of static

### ISSUE THREAD

**Issue by john-cj** [neilsustc/vscode-markdown#68]
Just came here to post my issue, but I see that something very similar was already posted an hour ago (https://github.com/neilsustc/vscode-markdown/issues/67). But, since I don't know, are these issues are really related or not, I will post my own.

The problem with outline is that it doesn't updates during adding/removing/renaming sections. For example, if I open some document with the following contents:

``` md
# Foo

...

# Bar

...
```

the outline will be correct. But - if I add, remove or rename some headings in document, the outline will not change.

If you plan to somehow implement **dynamic** outline in future releases, please let us know! :smiley:

**Comment by neilsustc** [comment]
I will take a look at it in two days 😉

**Comment by john-cj** [comment]
Thank you very much! :smiley:

**Comment by neilsustc** [comment]
I just released v1.0.0. The outline view will be updated when you save the file.
(And there is a known issue that the collapse states are not correct, but it seems to be an upstream issue)
