### ISSUE TITLE
It seems to detect and format a TOC where there is none

### ISSUE THREAD

**Issue by Ytrog** [neilsustc/vscode-markdown#7]
When I have a header with a list beneath it containing links it seems to think it is a TOC (marking it as not up to date) and regenerating a TOC in place on saving. You should be able to save without it creating TOC's.

Example:

```md
## Tasks
- [A task](http://link-to-task)
- [Another task](http://link-to-another-task)
```

On saving this is replaced by a TOC of the entire document.

Edit
Got it disabled using:
"markdown.extension.toc.updateOnSave": false

However it's still strange it detected a TOC here.

**Comment by neilsustc** [comment]
Thank you for the feedback. I'll look into it this weekend.

**Comment by neilsustc** [comment]
It seems that I cannot reproduce that with the snippet you provided 🤔.
Could you please provide more details? (e.g. vscode version, the text which was misrecognized as TOC)

![image](https://user-images.githubusercontent.com/7588612/27470807-20bb44b2-5828-11e7-95d7-74b739f9924a.png)

**Comment by Ytrog** [comment]
VSCode 1.13.1 
![image](https://user-images.githubusercontent.com/2880376/27475090-2fb25ff6-5804-11e7-835b-15173605aeb4.png)

As I don't want to leak information I obfuscated the actual text (it shouldn't really matter):
![image](https://user-images.githubusercontent.com/2880376/27475281-db89d50c-5804-11e7-9fcc-c8c7cf24d724.png)

**Comment by neilsustc** [comment]
Okay, I see the bug.
But I have no idea about why. Can you try to reproduce it with some not secret text? 😅

---

Below is the current behaviors,

> To avoid distractive HTML comments, this extension will 'guess' where the TOC is. Currently, a TOC will be recognized if 
> - It's a list block in Markdown syntax
> - Its first list item title matches the first heading in the file

**Comment by Ytrog** [comment]
Ah, the first item matches the title (a level 1 header) so the second rule triggers.

It would be like

```md
# PR-123456 Build a new window

## Issues
- [PR-123456 Build a new window](http://issuetracker/PR-123456)
- [PR-123457 A related issue](http://issuetracker/PR-123457)
```

**Comment by neilsustc** [comment]
I'll add an additional rule which is

- It should be a within-document anchor (something like `#header-title`) not a link (`http://...`)

**Comment by Ytrog** [comment]
I like the idea 👍

**Comment by neilsustc** [comment]
I've fixed it. But I cannot publish the new version because of the bad network connection. Let's ship it tomorrow.

**Comment by neilsustc** [comment]
Published! If you are satisfied with it, please give me a 5 stars 😉

**Comment by Ytrog** [comment]
It seems fixed 😄

**Comment by neilsustc** [comment]
Thanks 😎
