### ISSUE TITLE
Unable to install offline

### ISSUE THREAD

**Issue by dotlnk** [neilsustc/vscode-markdown#70]
After I download the vsix package, I try to install it **offline**, but I get the "xhr" error. I did not encounter this error when I installed some extensions like python from vsix.

**Comment by neilsustc** [comment]
I have no idea but you can try to download the latest [v0.11.2.1](https://github.com/neilsustc/vscode-markdown/releases/download/v0.11.2/markdown-all-in-one-0.11.2.1.vsix) from GitHub

**Comment by dotlnk** [comment]
![123](https://user-images.githubusercontent.com/3285467/34345955-0668e6a8-ea2e-11e7-98c3-3bfccc74978a.png).
Any ideas?

**Comment by dotlnk** [comment]
It works by using `code --install-extention markdown-all-in-one-0.11.2.1.vsix`, thank you!

**Comment by neilsustc** [comment]
😉
