### ISSUE TITLE
Create a new set of Mac bindings to not override VSCode/Mac semantic navigation

### ISSUE THREAD

**Issue by deepakrb** [neilsustc/vscode-markdown#71]
Right now by default 'Markdown All in One' overrides some semantic navigation shortcuts used to navigate around the editor on a Mac.

For instance
- `Cmd + shift + [` -> Switch One Tab to the left
- `Cmd + shift + ]` -> Switch One Tab to the right
- `Cmd + b` -> Toggle Sidebar

Switching tabs like that is standard across loads of Mac applications (Chrome for instance). It'd be nice if we could either change the defaults to be similar to Windows shortcuts (`Ctrl` replacing `Cmd`) or just have a totally different set of Mac bindings (pretty common solution)

The obvious fix for this is to manually modify the keyboard shortcuts (Cmd K Cmd S) for the extension and change these to an option which doesn't override those shortcuts used to navigate around VScode but that doesn't seem to be the best going forward.

Cheers

**Comment by neilsustc** [comment]
For `cmd + b`, I believe most of the text/Markdown editors use it to toggle bold (MS Word, Typora, Caret).

As for `cmd + shift + [/]`, I have no idea because I don't use Mac.
Is `ctrl` scheme good enough for you?

**Comment by deepakrb** [comment]
Sure, I would leave `Cmd + b`, it isn't the greatest shortcut VSCode implemented and it really shouldn't be sidebar toggle by default.

The `Ctrl + shift + [ | ]` alternative works well for me, I checked the key mappings for VSCode and nothing is bound to it by default so it's a good alternative.

**Comment by neilsustc** [comment]
Good, will change it in v1.0.0 (coming in several days) 😉

Thanks!

**Comment by deepakrb** [comment]
Awesome thank you!
