### ISSUE TITLE
can generate image to base4 while useing "Print your Markdown to HTML"

### ISSUE THREAD

**Issue by simonbaker** [neilsustc/vscode-markdown#73]
###  What is the problem? 
like this:
![image](https://user-images.githubusercontent.com/6262452/34506556-f60d1536-f068-11e7-970f-a100b1705b26.png)
after usering "Print your Markdown to HTML"，preview the html file, like this:
![image](https://user-images.githubusercontent.com/6262452/34506584-24cb809c-f069-11e7-92e3-9d8aa650d240.png)
![image](https://user-images.githubusercontent.com/6262452/34506592-4142564c-f069-11e7-86d2-ac2b287a3735.png)

### I wish 
can turn the image file to base64 while useing "Print your Markdown to HTML"?
![image](https://user-images.githubusercontent.com/6262452/34506623-881cca3e-f069-11e7-8205-a5dc76f208dc.png)

**Comment by neilsustc** [comment]
It is a good idea, thank you.

But I have a question, why the absolute `file://` path doesn't work? Is the generated image path correct?

**Comment by simonbaker** [comment]
Because the html file is independent. I will send the html file to other one, while he double-click the file, becasue his computer dont had the image files, so will look like this:
![image](https://user-images.githubusercontent.com/6262452/34507632-eebeb500-f072-11e7-92ec-61349ff0fa7b.png)

**Comment by neilsustc** [comment]
Okay, I see.

Generally speaking, I recommend using PDF to share documents. It is more reliable.
You can open the exported HTML in your browser and press <kbd>ctrl</kbd>+<kbd>p</kbd> to print it to PDF.
