### ISSUE TITLE
Add option to change toc unordered list style?

### ISSUE THREAD

**Issue by wenkanglin** [neilsustc/vscode-markdown#74]
### What is the problem?

The unordered list style of toc created by `vscode-markdown` is `-`(**dash**):
```
- [toc](#toc)
  - [section1](#section1)
  - [section2](#section2)
```

But when I used [prettier-vscode](https://github.com/prettier/prettier-vscode) extension to format markdown files, it changed the toc's unordered list style to `*`(**asterisk**), just as below:
```
* [toc](#toc)
  * [section1](#section1)
  * [section2](#section2)
```

Because this, the  `vscode-markdown` couldn't automatically update toc. Also the command `Markdown: Update Table of Contents` didn't work.

So I hope there will be an option to change the unordered list style of toc to `*`(**asterisk**)

###  How can I reproduce it?

1. Install `prettier-vscode` at your vscode
2. Restart vscode
3. Pick up a markdown file that has toc created by `vscode-markdown`
4. Format it

###  Is there any error message in the console?

none

**Comment by neilsustc** [comment]
Thanks for your report

**Comment by neilsustc** [comment]
v1.0.0 is out but I forgot to mention this in the changelog...

**Comment by wenkanglin** [comment]
I have a try, pretty good ! Thank you for your hlep
