### ISSUE TITLE
Table formatting is not working

### ISSUE THREAD

**Issue by KlodAyzak** [neilsustc/vscode-markdown#75]
Table formatting is not working after installing the extension

Formar document command does not work event with the following config:
  "markdown.extension.tableFormatter.enabled": true
Version: 0.11.2

No

**Comment by neilsustc** [comment]
Could you give me a snippet of code for example?

**Comment by KlodAyzak** [comment]
Here a snippet of code: 
        | Parameter | Value     |
        | --- |---   |
        | ousi   | oui       |
        |la     | loaool    |

**Comment by KlodAyzak** [comment]
Wondering whether, I do not have a conflict with another extension. 
PS: All addition Markdown extension are disabled

**Comment by neilsustc** [comment]
It seems to work well in my vscode.

Do other features work well? e.g. keyboard shortcuts

**Comment by KlodAyzak** [comment]
Shortcut: Bold, italic, check/uncheck task list works well. 

The table formatting does not work with the right click neither

**Comment by neilsustc** [comment]
You can try [v0.11.2.1](https://github.com/neilsustc/vscode-markdown/releases/download/v0.11.2/markdown-all-in-one-0.11.2.1.vsix) (although there is no changes on table formatting)
