### ISSUE TITLE
Configure indentation

### ISSUE THREAD

**Issue by mikemol** [neilsustc/vscode-markdown#77]
I use `markdownlint`, and the TOC generator causes linting issues.

1. Install vscode-markdown and markdownlint extensions.
1. Generate a markdown document with a handful of header levels.
1. Generate a ToC
1. Observe "PROBLEMS' tab for document.

No problems from developer tools (that I noticed), but from "PROBLEMS" tab:

```
[markdownlint] MD007/ul-indent: Unordered list indentation [Expected: 2; Actual: 4] (4,1)
[markdownlint] MD007/ul-indent: Unordered list indentation [Expected: 6; Actual: 8] (5,1)
[markdownlint] MD007/ul-indent: Unordered list indentation [Expected: 10; Actual: 12] (7,1)
```

I'm going to look to see if I can tune markdownlint, but I'd like to be able to tune this tool.

**Comment by neilsustc** [comment]
Currently this ext respects the global `tabSize`. So you can put `"editor.tabSize": 2` into your user settings.
The disadvantage is that it is a global setting.
I am going to make it use the per file setting in the right bottom.

**Comment by neilsustc** [comment]
![image](https://user-images.githubusercontent.com/7588612/34883398-7e1f68ec-f7f4-11e7-8b7c-c85bf403596d.png)

Please try v1.0.1
