### ISSUE TITLE
HotKey for toggle sidebar and toogle bold crashes

### ISSUE THREAD

**Issue by ColinTree** [neilsustc/vscode-markdown#79]
They are both ctrl+b :( but i prefer it is for sidebar toggling more

So how can I disable this part (using keys to toggle bold)?

BTW, the toc part is great, I like it :P

zh-hans: 侧边栏和粗体都是ctrl+b，我想把粗体的禁用掉，咋整

**Comment by neilsustc** [comment]
😂

点击左下角设置图标，键盘快捷方式，输入 ctrl + b 筛选，

![image](https://user-images.githubusercontent.com/7588612/35192510-27a1b754-fecf-11e7-8f8a-d1576a522d1d.png)

可以改成你想要的键

**Comment by ColinTree** [comment]
TKX🙏
