### ISSUE TITLE
Chinese character does not convert well as excepted.

### ISSUE THREAD

**Issue by ColinTree** [neilsustc/vscode-markdown#80]
## This is what toc generaged

![image](https://user-images.githubusercontent.com/22613139/35196310-2bbccd06-ff0b-11e7-929e-ef4a03bf80ea.png)

![image](https://user-images.githubusercontent.com/22613139/35196338-9a2df940-ff0b-11e7-9891-c7d13919c746.png)

And it does not works (no jumping to the heading)

## And this is the code that works (by hand)

![image](https://user-images.githubusercontent.com/22613139/35196314-3d484f78-ff0b-11e7-87e8-356b41eb54b2.png)

![image](https://user-images.githubusercontent.com/22613139/35196331-8197b826-ff0b-11e7-86a5-c4ba34cd18da.png)

## Analyzing..

I believe that it is because that the heading tags are using this kind of encoding:
![image](https://user-images.githubusercontent.com/22613139/35196352-d2d5ce9e-ff0b-11e7-9250-a0189a055f03.png)
which is not url encoding, so the linking url "does not equal" to the id in heading tag. 
And gitbook would not recognize it and the the jumping action.

**Comment by ColinTree** [comment]
说到底就是编码问题，目前来看只能拓展向平台妥协了

**Comment by neilsustc** [comment]
看起来中文被 HTML 转义了，你的 HTML 是用什么生成的？

这个插件用的是 vscode 自带的[把标题转换成链接的函数](https://github.com/Microsoft/vscode/blob/master/extensions/markdown/src/tableOfContentsProvider.ts#L85-L92)，在 vscode 的预览和用插件导出的 HTML 里面应该都是正常的，应该没法改动了

**Comment by ColinTree** [comment]
用的Gitbook

**Comment by neilsustc** [comment]
个人觉得是 gitbook 不合常规，所以我这边不好解决

Related: [gitbook#702](https://github.com/GitbookIO/gitbook/issues/702)

**Comment by ColinTree** [comment]
我在想有没有什么比较两全的解决方法…
比如我本地找时间给改改🌝
也只能这样了
