### ISSUE TITLE
keep image relative path

### ISSUE THREAD

**Issue by CaptainJH** [neilsustc/vscode-markdown#81]
Hi, 

I notice when I export markdown to HTML, all the images using relative path are all converted to absolute path, no matter I use the standard markdown syntax or the insert html.

However, I also notice if I insert html element like iframe, the relative path will not be converted.

So, my question is, can I keep using the relative image path when export html, because it makes it easier to share it with others.

**Comment by neilsustc** [comment]
I can add an option to do this.

But I recommend printing to PDF if you want share some documents

**Comment by neilsustc** [comment]
Please try v1.0.3

**Comment by CaptainJH** [comment]
Thanks, really appreciate
