### ISSUE TITLE
TOC entries that contain links do not generate correctly

### ISSUE THREAD

**Issue by syegulalp** [neilsustc/vscode-markdown#83]
If I have a TOC entry with a link in it, such as 

```
## const [(link)](const.md)
```

the link is mangled in the TOC entry:

```
- [const [(link)](const.md)](#const-linkconstmd)
```

It would be useful if there was some internal setting that would allow any links already in a given TOC heading to be stripped out in the TOC itself and replaced with just the link to the item in the page. E.g., from the above example, we could get just:

```
- [const](#const)
```

**Comment by neilsustc** [comment]
Please try v1.0.4.

The solution is `- [const (link)](const-link)`, which keeps the link text

**Comment by syegulalp** [comment]
That seems to do it. Thank you!
