### ISSUE TITLE
markdown.extension.print.absoluteImgPath=false does not work

### ISSUE THREAD

**Issue by ryo-neyama** [neilsustc/vscode-markdown#84]
Even if I set "markdown.extension.print.absoluteImgPath": false, the extension still generates absolute path for img.

Just set "markdown.extension.print.absoluteImgPath": false in the configuration, then "Markdown: Print current document to HTML".

No error message.

[FIX]
print.ts:70:
  now
>    if (vscode.workspace.getConfiguration("markdown.extension.print.absoluteImgPath", doc.uri)) {
  fix
>    if (vscode.workspace.getConfiguration("markdown", doc.uri).get("extension.print.absoluteImgPath")) {

**Comment by neilsustc** [comment]
Yes, you are right. I didn't test it before I released it 😅
