### ISSUE TITLE
In my hexo tags, how to close the table of content

### ISSUE THREAD

**Issue by xuoutput** [neilsustc/vscode-markdown#85]
```
---
title: 
date: 2018-02-03 14:48:00
tags:
- vue-router  //here is the problem
- vuejs

---


when I `ctrl+s` , it beacomes

date: 2018-02-03 14:48:00
tags:
- [vue-route](#vue-route)   //what is it, how to close it
catogories:
```

**Comment by neilsustc** [comment]
用中文描述一下吧，我没有很了解问题具体是什么。。

代码块可以放在两行 <code>```</code> 之间

**Comment by xuoutput** [comment]
![markdown2](https://user-images.githubusercontent.com/16385443/35764109-81bb3cda-08f5-11e8-9678-06df3f32e2af.png)
![markdown1](https://user-images.githubusercontent.com/16385443/35764108-7c1879be-08f5-11e8-93e8-ac288628a861.png)

**Comment by neilsustc** [comment]
可以去设置里面改下 `markdown.extension.toc.updateOnSave`

**Comment by xuoutput** [comment]
稳

**Comment by neilsustc** [comment]
你可以安装[这个版本](https://github.com/neilsustc/vscode-markdown/releases/download/beta/markdown-all-in-one-1.0.5.vsix)，就不会识别为目录了
