### ISSUE TITLE
TocProvider.slugify is not a function

### ISSUE THREAD

**Issue by wayneashleyberry** [neilsustc/vscode-markdown#87]
_What is the problem?_

Running the "Markdown: Create Table of Contents" command results in the following error:

> TocProvider.slugify is not a function

_How can I reproduce it?_

1. Install the extension in VS Code Insiders
2. Open a simple markdown file
3. Markdown: Create Table of Contents

_Is there any error message in the console?_
```
TocProvider.slugify is not a function
e.doShow @ workbench.main.js:sourcemap:2930
e.show @ workbench.main.js:sourcemap:2930
e.resume @ workbench.main.js:sourcemap:2929
(anonymous) @ workbench.main.js:sourcemap:4649
e.fire @ workbench.main.js:sourcemap:162
(anonymous) @ workbench.main.js:sourcemap:3404
```

**Comment by neilsustc** [comment]
Thanks for your detailed report

**Comment by neilsustc** [comment]
Can you try [this beta version](https://github.com/neilsustc/vscode-markdown/releases/tag/beta)?

**Comment by wayneashleyberry** [comment]
That fixes the issue, thanks @neilsustc
