### ISSUE TITLE
Ctrl+(Shift+)Space shortcut for checking to-dos

### ISSUE THREAD

**Issue by MisterY** [neilsustc/vscode-markdown#88]
Most outliners use Ctrl+Space as the shortcut for toggling checkboxes in to-do lists. This extension uses Alt+C.

Edit: As Ctrl+Space seems to be used by the editor, Ctrl+Shift+Space is also very convenient.

Would it be possible to add/change the shortcut or enable customizing it? Is it possible to add custom shortcuts in vscode? If so, what would be the command to bind to?

Thanks for the awesome extension! This was the missing bit to move from other outliners (whether online or offline) to markdown files.

**Comment by neilsustc** [comment]
![image](https://user-images.githubusercontent.com/7588612/36058911-67928b66-0e67-11e8-98bd-2868adf794b8.png)

![image](https://user-images.githubusercontent.com/7588612/36058926-c0df00a0-0e67-11e8-9492-85465aa6051e.png)

**Comment by MisterY** [comment]
Thanks a lot! That's what I was looking for but was obliviously ignorant of the existance and easy accessibility of this feature.

**Comment by neilsustc** [comment]
😉
