### ISSUE TITLE
Bold command overrides the command used to close the sidebar

### ISSUE THREAD

**Issue by Nathaniel-Pankhurst** [neilsustc/vscode-markdown#92]
## The Problem
The command to make text bold in markdown is the same command that is used to hide the sidebar in the editor. Potentially change the bold command to Ctrl+shift+B?

## How to reproduce
Press Ctrl+B whilst editing a markdown file, this makes the text bold rather than closing the sidebar

**Comment by neilsustc** [comment]
Please refer to #89.
