### ISSUE TITLE
Conflict with VSCodeVim / search mode

### ISSUE THREAD

**Issue by ylns1314** [neilsustc/vscode-markdown#93]
In VSCodeVim / search mode, "Enter" will be recognized as "insert a newline" instead of "start search" since the second time using / search in the session.

The problem only happens when both VSCodeVim and Markdown All in One are enabled; and only for markdown files.

(under MacOS 10.13.3 with VSCode 1.20, did not test under other env)
1. install and enable VSCodeVim and Markdown All in One.
2. open a markdown file.
3. type "/" to enter the search mode, type anything and then press "Enter".
4. type "/" again to enter the search mode, type anything and then press "Enter". This time "Enter" will be recognized as "insert a newline" and the file will be modified (which should not happen), a newline is inserted at the cursor position.
5. Repeat step 4.

![issue_demo](https://user-images.githubusercontent.com/2519878/36133125-83c99d86-1049-11e8-993d-0abc8fd5c2ac.gif)

After pressing ESC to go back to normal mode of VSCodeVim from / search, press "u" (undo) will generate an error as follow:

> [Extension Host] invalid value for set cursor position. This is probably bad? console.ts:123
> [Extension Host] Error: Illegal value for `line`
	at t._lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:487:34)
	at Object.lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:485:801)
	at Function.getLineAt (\~/.vscode/extensions/vscodevim.vim-0.10.13/out/src/textEditor.js:121:56)
	at ModeHandler.<anonymous> (\~/.vscode/extensions/vscodevim.vim-0.10.13/out/src/mode/modeHandler.js:486:67)
	at Generator.next (<anonymous>)
	at fulfilled (\~/.vscode/extensions/vscodevim.vim-0.10.13/out/src/mode/modeHandler.js:4:58)
	at <anonymous>
t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:394
(anonymous) @ extensionHost.ts:211
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104

**Comment by neilsustc** [comment]
Thanks for your detailed report.
But I cannot reproduce with vscode 1.21.0-insider (ef42990) on Windows. (vim-0.10.13)
It seems that everything goes well. Do you have any personal configuration?

**Comment by ylns1314** [comment]
Thank you for the quick response.
My only non-default VSCodeVim setting is:
```
    "vim.useSystemClipboard": true,
```
And all Markdown All in One settings are kept default.

Also, two keybinding related to "Enter" in editor are:
```json
    {
        "key": "enter",
        "command": "markdown.extension.onEnterKey",
        "when": "editorTextFocus && !suggestWidgetVisible && editorLangId == 'markdown'"
    },
    {
        "key": "enter",
        "command": "acceptSelectedSuggestionOnEnter",
        "when": "acceptSuggestionOnEnter && editorTextFocus && suggestWidgetVisible && suggestionMakesTextEdit"
    },
```

Tried to disable the first "Enter" keybinding, which solves the problem but loses functions of Markdown All in One as well.

**Comment by neilsustc** [comment]
I have an idea. You can try to add another condition to the first "Enter" keybinding.

```json
{
    "key": "enter",
    "command": "markdown.extension.onEnterKey",
    "when": "editorTextFocus && !suggestWidgetVisible && editorLangId == 'markdown' && vim.mode != 'SearchInProgressMode'"
}
```

**Comment by ylns1314** [comment]
Tried but the issue persists.

**Comment by neilsustc** [comment]
![vim](https://user-images.githubusercontent.com/7588612/36237537-4d22489c-1237-11e8-9cf8-8ca51f13360e.gif)

I still have no idea since it works well on my PC...

Maybe you can try:
1. Disable all other extensions except for these two.
2. Or try insider build of vscode (if you do this, you might need to install this version of [md extension](https://github.com/neilsustc/vscode-markdown/releases))
