### ISSUE TITLE
Check boxes rendering unaligned

### ISSUE THREAD

**Issue by jsmedmar** [neilsustc/vscode-markdown#94]
### What is the problem?

Check boxes are unaligned:

<a href="http://tinypic.com?ref=312a6c1" target="_blank"><img src="http://i64.tinypic.com/312a6c1.png" border="0" alt="Image and video hosting by TinyPic"></a>

### How can I reproduce it?

Just this simple markdown:

```
# Level 1
## Level 2
### Level 3

- [ ] an example
```

**Comment by neilsustc** [comment]
![image](https://user-images.githubusercontent.com/7588612/36237299-e1b30e08-1235-11e8-8f59-de63382bef47.png)

Do you have other custom `css` applied to your preview. I guess there might be some conflicts.

**Comment by jsmedmar** [comment]
That makes sense, ill explore more if i cant figure it out I’ll reopen

**Comment by jsmedmar** [comment]
I realized this issue happens when using the plugin Markdown Preview Github
