### ISSUE TITLE
command 'markdown.extension.onEnterKey' not found

### ISSUE THREAD

**Issue by luispabon** [neilsustc/vscode-markdown#95]
Today all of a sudden, when I edit a markdown document and try to press enter, I get the following warning:

`command 'markdown.extension.onEnterKey' not found`

Reinstalling the extension doesn't help

Open a markdown document, click anywhere on it and press enter.

Nothing:

![image](https://user-images.githubusercontent.com/6388823/36210449-5ae39cd4-1196-11e8-9a10-6bf6071c9bbc.png)

**Comment by neilsustc** [comment]
A few more questions
1. Are you using vscode **insider** build?
2. Do "waiting for a few seconds after opening a MD file" help?

**Comment by rarnoldmobile** [comment]
Receiving the same - this has been recurring since I installed the extension on my windows pc (the past 30 days) - this behavior does not happen on my osx computer.

To add an additional item - the behavior does go away for after ~2 minutes.  My first thought is there may be another extension conflicting/adding to extension load times - causing this delay - but disabling other extensions does not seem to resolve it.

**Comment by neilsustc** [comment]
Thanks for the report. This issue seems to be the most common problem. I'm considering to add something in this extension to help users troubleshooting.

**Comment by albertored** [comment]
Same here with vscode insiders
```
Version 1.21.0-insider
Commit ce13bb0dabd06981913c46b5a94456647864c2e0
Date 2018-02-23T06:15:51.754Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

It happens with all markdown extensions keyboard shortcuts

**Comment by neilsustc** [comment]
@albertored Since you are using insider build, the root cause might be different. You can try manually install [this version of extension](https://github.com/neilsustc/vscode-markdown/releases/tag/beta)

**Comment by krumware** [comment]
Installing the beta version does not fix it on my end.
![image](https://user-images.githubusercontent.com/17303782/36813297-1c315532-1ca2-11e8-854c-094577b721fa.png)

**Comment by neilsustc** [comment]
Because insider build change again during the past few days. You need [one more step](https://github.com/neilsustc/vscode-markdown/issues/103#issuecomment-368295280) now.
You can also wait for several days as I will release a new version after vscode Feb stable build.

**Comment by neilsustc** [comment]
Please try v1.1.0

**Comment by krumware** [comment]
Took a couple of restarts, but working in latest insider build (1.22.0-insider)

**Comment by Floriferous** [comment]
There's no way to solve this without using the insider build?

**Comment by neilsustc** [comment]
It (v1.1.0) should work well with vscode v1.21.0 (or later of course).

**Comment by m451** [comment]
Workaround: without manually messing with the extension: copy a CRFR char sequence and copy&paste if you need a new line rather then using enter. Yeh, I know. It's messy. But it does the job if you just need to fix something in your markdown RIGHT_NOW...

**Comment by luispabon** [comment]
I can confirm this is fixed now with the latest plugin and vscode.

**Comment by pernix84** [comment]
Got the same problem, but can confirm also! Updating VSCode solved the problem (1.21.0)

**Comment by penut85420** [comment]
@pernix84 thx, I solve the problem

**Comment by MitchK** [comment]
I had the same issue, with the latest stable version of the plugin installed. Updating VS Code solved the issue.

My current version of VSCode:
```
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:01:43.521Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by ulysses4ever** [comment]
I have VS Code 1.21.1 (NOT insider) and plugin version 1.1.2 and still have the same problem. The issue should be reopened.

**Comment by neilsustc** [comment]
@ulysses4ever You need to provide more information otherwise I have no idea why it happens.
Does this issue still exist if you wait 2 second after opening the MD file?
Is there any error message in the dev tools console? (menu>help>toggle dev tools)

**Comment by ulysses4ever** [comment]
@neilsustc after Disabling/Enabling it it seems to start working right. Thanks!

**Comment by Agarwal-Nikhil** [comment]
I have VS Code 1.22.2 (NOT insider) still have the same problem. The issue should be reopened.

**Comment by Agarwal-Nikhil** [comment]
The issue remains even after 10 minutes of starting VS Code

**Comment by Agarwal-Nikhil** [comment]
Also I am getting this error as well: command 'markdown.extension.onBackspaceKey' not found

**Comment by neilsustc** [comment]
@Agarwal-Nikhil Any error message in the dev tools console (menu>help>toggle dev tools)?

**Comment by Agarwal-Nikhil** [comment]
@neilsustc Yes, I get this error: extensionService.ts:848 Activating extension 'yzhang.markdown-all-in-one' failed: Cannot find module 'katex'.

**Comment by neilsustc** [comment]
It seems that some files are missing. Please uninstall the extension, restart vscode and then reinstall it.

**Comment by Agarwal-Nikhil** [comment]
@neilsustc Did reinstallation. But the problem still persists.

**Comment by neilsustc** [comment]
That's really strange. Could you check whether the directory `C:\Users\[username]\.vscode\extensions\yzhang.markdown-all-in-one-1.3.0\node_modules\@iktakahiro\markdown-it-katex\node_modules\katex` exists?

**Comment by Agarwal-Nikhil** [comment]
Yes it exist. It has following contents: 
![image](https://user-images.githubusercontent.com/18417820/40224558-da253bc2-5a86-11e8-9374-7ce135ae41b9.png)

**Comment by neilsustc** [comment]
It looks perfect. I have no idea why vscode still says "cannot find katex"

One last option is to try it with vscode-insider build because its extensions are isolated from the stable build.

**Comment by cbejensen** [comment]
This happens to me when I open a new tab (a brand new, unsaved file). If I save the file, everything works. However, I'd like this to work on unsaved files, because setting `files.defaultLanguage` to `markdown` makes new files markdown automatically, which I can use to quickly jot down notes with style. This works fine without the extension installed, but of course I'd prefer to use the tools this extension provides.

Is there any way to do this?

**Comment by neilsustc** [comment]
@cbejensen You can try the latest build [`v1.3.0-0519`](https://github.com/neilsustc/vscode-markdown/releases/download/beta/markdown-all-in-one-1.3.0-0519.vsix).

**Comment by sasukeh** [comment]
@neilsustc 
For me, latest build works well thanks.

**Comment by maoxiaoke** [comment]
This is caused by markdown-all-in-one. Uninstall the extension were help.

**Comment by Triamus** [comment]
not working for me even after restart and reload
windows 7
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by neilsustc** [comment]
@Triamus Your vscode version is old. Please update it first and you will get it work.

And this issue itself is also out-of-date. Please find the latest one 😂.

**Comment by mantasindrasius** [comment]
Have just recently worked, but started getting out of a sudden.
`onBackspaceKey` and `onEnterKey`

MacOS X High Sierra
Version 1.25.1 (1.25.1)
Extension: v1.5.1

Reinstall/Reload IDE did not work.

**Comment by neilsustc** [comment]
For the problem like "command '...' not found", please try to
1. wait for a few seconds after you open a Markdown file for the first time
2. doesn't work? -> update vscode
3. doesn't work? -> reinstall this extension
4. still doesn't work? 😵 -> please open the developer tools to see whether there is any error message, and then paste it below. (Menu Bar -> Help -> Toggle Developer Tools)

---

And please discuss this in #217. This thread is out-of-date.
