### ISSUE TITLE
Use a. or i. for ordered lists highlighted

### ISSUE THREAD

**Issue by ldsands** [neilsustc/vscode-markdown#96]
What is the problem? (more of a feature request)
- Ordered List will not highlight when using a. (for letters) or i. (for roman numerals)

How can I reproduce it?
- type in a. or i. for an ordered list and there will not be any highlights

**Comment by neilsustc** [comment]
It is the problem of color theme you choose. (In fact, this extension doesn't provide syntax highlighting)

![color](https://user-images.githubusercontent.com/7588612/36237782-162e2606-1239-11e8-8739-e84fa6c06bc9.gif)

**Comment by ldsands** [comment]
Sorry to bother you then. Also, thank you for a great extension!

**Comment by neilsustc** [comment]
It doesn't matter 😉
